import ProximityPrize.SubmissionLower.BCHKSFrobeniusAmplitude6400

/-!
# Cofactor identity from a Frobenius amplitude atom

On a retained source agreement, factor the witness polynomial as
`L * Cof`, where `L` is the locator of the agreements outside the source.
The amplitude decomposition and its Frobenius relation eliminate both `L`
and the pointwise amplitude.  The result is a bounded polynomial identity.

The loss charged by the two gcd normalizations is carried through the root
count explicitly.  Under the two expected coprimality conditions, the affine
direct factor then divides the witness cofactor.
-/

namespace ProximityPrize.SubmissionLower

open Polynomial

variable {F : Type} [Field F]

/-- The affine polynomial pencil generated by two direct multipliers. -/
noncomputable def affinePolynomial (P Q : F[X]) (w : F) : F[X] :=
  P + Polynomial.C w * Q

@[simp]
theorem affinePolynomial_eval (P Q : F[X]) (w x : F) :
    (affinePolynomial P Q w).eval x = P.eval x + w * Q.eval x := by
  simp [affinePolynomial]

theorem affinePolynomial_natDegree_le (P Q : F[X]) (w : F) :
    (affinePolynomial P Q w).natDegree ≤ max P.natDegree Q.natDegree := by
  exact (Polynomial.natDegree_add_le _ _).trans
    (max_le_max le_rfl (Polynomial.natDegree_C_mul_le w Q))

theorem affinePolynomial_map (sigma : F ≃+* F) (P Q : F[X]) (w : F) :
    (affinePolynomial P Q w).map sigma.toRingHom =
      affinePolynomial (P.map sigma.toRingHom)
        (Q.map sigma.toRingHom) (sigma w) := by
  simp [affinePolynomial]

variable {S : Finset F} {error₀ error₁ : F → F}
  {sigma : F ≃+* F} {z : F} {h : ℕ}

/-- Every affine direct combination paired with the amplitude multiplier
retains the atom's compensated `2*h` degree budget. -/
theorem FrobeniusAmplitudeAtom.affine_amplitude_degree
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h) (w : F) :
    (affinePolynomial atom.direct₀ atom.direct₁ w).natDegree +
        atom.amplitudeMultiplier.natDegree +
      (atom.baseLoss + atom.gcdLoss) < 2 * h := by
  have hcomb := affinePolynomial_natDegree_le atom.direct₀ atom.direct₁ w
  have h₀ := atom.direct₀_amplitude_degree
  have h₁ := atom.direct₁_amplitude_degree
  omega

/-- The analogous compensated budget with the scroll denominator. -/
theorem FrobeniusAmplitudeAtom.affine_denominator_degree
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h) (w : F) :
    (affinePolynomial atom.direct₀ atom.direct₁ w).natDegree +
        atom.denominator.natDegree +
      (atom.baseLoss + atom.gcdLoss) < 2 * h := by
  have hcomb := affinePolynomial_natDegree_le atom.direct₀ atom.direct₁ w
  have h₀ := atom.direct₀_denominator_degree
  have h₁ := atom.direct₁_denominator_degree
  omega

/-- The polynomial whose vanishing is forced by one bad witness cofactor. -/
noncomputable def FrobeniusAmplitudeAtom.cofactorRelation
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h)
    (w : F) (Cof : F[X]) : F[X] :=
  atom.denominator * affinePolynomial atom.direct₀ atom.direct₁ w *
      Cof.map sigma.toRingHom -
    atom.amplitudeMultiplier *
      (affinePolynomial atom.direct₀ atom.direct₁ w).map
        sigma.toRingHom * Cof

/-- At a retained source agreement, the outside-source locator and the
pointwise amplitude cancel and the cofactor relation evaluates to zero. -/
theorem FrobeniusAmplitudeAtom.cofactorRelation_eval_eq_zero
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h)
    (w x : F) (hx : x ∈ atom.valid) (hfixed : sigma x = x)
    (L Cof : F[X]) (hLfixed : L.map sigma.toRingHom = L)
    (hLne : L.eval x ≠ 0)
    (hagreement : (L * Cof).eval x = error₀ x + w * error₁ x) :
    (atom.cofactorRelation w Cof).eval x = 0 := by
  let Cw := affinePolynomial atom.direct₀ atom.direct₁ w
  have hdirect : (L * Cof).eval x = Cw.eval x * atom.amplitude x := by
    rw [hagreement, atom.decomposition₀ x hx, atom.decomposition₁ x hx]
    simp only [Cw, affinePolynomial_eval]
    ring
  have hconjugate :
      L.eval x * (Cof.map sigma.toRingHom).eval x =
        (Cw.map sigma.toRingHom).eval x * sigma (atom.amplitude x) := by
    have hsigma := congrArg sigma hdirect
    have hleftMap := polynomial_map_eval_of_fixed sigma (L * Cof) x hfixed
    have hrightMap := polynomial_map_eval_of_fixed sigma Cw x hfixed
    rw [Polynomial.map_mul, hLfixed, Polynomial.eval_mul] at hleftMap
    calc
      L.eval x * (Cof.map sigma.toRingHom).eval x =
          sigma ((L * Cof).eval x) := hleftMap
      _ = sigma (Cw.eval x * atom.amplitude x) := hsigma
      _ = sigma (Cw.eval x) * sigma (atom.amplitude x) := by
        simp only [map_mul]
      _ = (Cw.map sigma.toRingHom).eval x *
          sigma (atom.amplitude x) := by rw [hrightMap]
  have hamplitude := atom.amplitude_relation x hx
  have hscalar :
      atom.denominator.eval x * Cw.eval x *
          (Cof.map sigma.toRingHom).eval x =
        atom.amplitudeMultiplier.eval x *
          (Cw.map sigma.toRingHom).eval x * Cof.eval x := by
    apply mul_left_cancel₀ hLne
    calc
      L.eval x *
          (atom.denominator.eval x * Cw.eval x *
            (Cof.map sigma.toRingHom).eval x) =
        atom.denominator.eval x * Cw.eval x *
          (L.eval x * (Cof.map sigma.toRingHom).eval x) := by ring
      _ = atom.denominator.eval x * Cw.eval x *
          ((Cw.map sigma.toRingHom).eval x *
            sigma (atom.amplitude x)) := by rw [hconjugate]
      _ = Cw.eval x * (Cw.map sigma.toRingHom).eval x *
          (atom.denominator.eval x * sigma (atom.amplitude x)) := by ring
      _ = Cw.eval x * (Cw.map sigma.toRingHom).eval x *
          (atom.amplitudeMultiplier.eval x * atom.amplitude x) := by
        rw [hamplitude]
      _ = atom.amplitudeMultiplier.eval x *
          (Cw.map sigma.toRingHom).eval x *
          (Cw.eval x * atom.amplitude x) := by ring
      _ = atom.amplitudeMultiplier.eval x *
          (Cw.map sigma.toRingHom).eval x * (L * Cof).eval x := by
        rw [← hdirect]
      _ = L.eval x *
          (atom.amplitudeMultiplier.eval x *
            (Cw.map sigma.toRingHom).eval x * Cof.eval x) := by
        simp only [Polynomial.eval_mul]
        ring
  simp only [FrobeniusAmplitudeAtom.cofactorRelation,
    Polynomial.eval_sub, Polynomial.eval_mul]
  exact sub_eq_zero.mpr hscalar

/-- Exact degree bound for the cofactor relation, including the atom's
removed-root budget. -/
theorem FrobeniusAmplitudeAtom.cofactorRelation_degree_add_loss_lt
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h)
    (w : F) (Cof : F[X]) :
    (atom.cofactorRelation w Cof).natDegree +
        (atom.baseLoss + atom.gcdLoss) <
      Cof.natDegree + 2 * h := by
  let Cw := affinePolynomial atom.direct₀ atom.direct₁ w
  have hCmap : (Cw.map sigma.toRingHom).natDegree = Cw.natDegree :=
    Polynomial.natDegree_map_eq_of_injective sigma.injective Cw
  have hCofmap : (Cof.map sigma.toRingHom).natDegree = Cof.natDegree :=
    Polynomial.natDegree_map_eq_of_injective sigma.injective Cof
  have hleft :
      (atom.denominator * Cw * Cof.map sigma.toRingHom).natDegree ≤
        atom.denominator.natDegree + Cw.natDegree + Cof.natDegree := by
    calc
      (atom.denominator * Cw * Cof.map sigma.toRingHom).natDegree ≤
          (atom.denominator * Cw).natDegree +
            (Cof.map sigma.toRingHom).natDegree :=
        Polynomial.natDegree_mul_le
      _ ≤ (atom.denominator.natDegree + Cw.natDegree) +
          (Cof.map sigma.toRingHom).natDegree := by
        exact Nat.add_le_add_right Polynomial.natDegree_mul_le _
      _ = atom.denominator.natDegree + Cw.natDegree + Cof.natDegree := by
        rw [hCofmap]
  have hright :
      (atom.amplitudeMultiplier * Cw.map sigma.toRingHom * Cof).natDegree ≤
        atom.amplitudeMultiplier.natDegree + Cw.natDegree +
          Cof.natDegree := by
    calc
      (atom.amplitudeMultiplier * Cw.map sigma.toRingHom * Cof).natDegree ≤
          (atom.amplitudeMultiplier * Cw.map sigma.toRingHom).natDegree +
            Cof.natDegree := Polynomial.natDegree_mul_le
      _ ≤ (atom.amplitudeMultiplier.natDegree +
          (Cw.map sigma.toRingHom).natDegree) + Cof.natDegree := by
        exact Nat.add_le_add_right Polynomial.natDegree_mul_le _
      _ = atom.amplitudeMultiplier.natDegree + Cw.natDegree +
          Cof.natDegree := by rw [hCmap]
  have hden := atom.affine_denominator_degree w
  have hamp := atom.affine_amplitude_degree w
  by_cases hDA : atom.denominator.natDegree ≤
      atom.amplitudeMultiplier.natDegree
  · have hleft' :
        (atom.denominator * Cw * Cof.map sigma.toRingHom).natDegree ≤
          atom.amplitudeMultiplier.natDegree + Cw.natDegree +
            Cof.natDegree := hleft.trans (by omega)
    have hrelation :
        (atom.cofactorRelation w Cof).natDegree ≤
          atom.amplitudeMultiplier.natDegree + Cw.natDegree +
            Cof.natDegree := by
      exact (Polynomial.natDegree_sub_le _ _).trans
        (max_le hleft' hright)
    dsimp only [Cw] at hrelation hamp
    omega
  · have hAD : atom.amplitudeMultiplier.natDegree ≤
        atom.denominator.natDegree := Nat.le_of_not_ge hDA
    have hright' :
        (atom.amplitudeMultiplier * Cw.map sigma.toRingHom * Cof).natDegree ≤
          atom.denominator.natDegree + Cw.natDegree + Cof.natDegree :=
      hright.trans (by omega)
    have hrelation :
        (atom.cofactorRelation w Cof).natDegree ≤
          atom.denominator.natDegree + Cw.natDegree + Cof.natDegree := by
      exact (Polynomial.natDegree_sub_le _ _).trans
        (max_le hleft hright')
    dsimp only [Cw] at hrelation hden
    omega

/-- If enough of the raw source agreements survive the atom's exact loss,
the bounded pointwise relation is a global polynomial identity. -/
theorem FrobeniusAmplitudeAtom.cofactorRelation_eq_zero
    [DecidableEq F]
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h)
    (w : F) (L Cof : F[X]) (E : Finset F) (rawCount c : ℕ)
    (hE : E ⊆ atom.valid)
    (hfixed : ∀ x ∈ E, sigma x = x)
    (hLfixed : L.map sigma.toRingHom = L)
    (hLne : ∀ x ∈ E, L.eval x ≠ 0)
    (hagreement : ∀ x ∈ E,
      (L * Cof).eval x = error₀ x + w * error₁ x)
    (hcoverage : rawCount ≤
      E.card + (atom.baseLoss + atom.gcdLoss))
    (hcofactor : Cof.natDegree + c < rawCount)
    (htwo : 2 * h ≤ c) :
    atom.cofactorRelation w Cof = 0 := by
  have hroot : ∀ x ∈ E, (atom.cofactorRelation w Cof).eval x = 0 := by
    intro x hx
    exact atom.cofactorRelation_eval_eq_zero w x (hE hx) (hfixed x hx)
      L Cof hLfixed (hLne x hx) (hagreement x hx)
  have hdegree : (atom.cofactorRelation w Cof).natDegree < E.card := by
    have hrel := atom.cofactorRelation_degree_add_loss_lt w Cof
    omega
  exact Polynomial.eq_zero_of_natDegree_lt_card_of_eval_eq_zero'
    (atom.cofactorRelation w Cof) E hroot hdegree

/-- Outside the two explicit coprimality failures, the direct affine factor
must divide the bad witness cofactor. -/
theorem affinePolynomial_dvd_cofactor_of_cofactorRelation_eq_zero
    (atom : FrobeniusAmplitudeAtom S error₀ error₁ sigma z h)
    (w : F) (Cof : F[X])
    (hidentity : atom.cofactorRelation w Cof = 0)
    (hcoprimeAmplitude :
      IsCoprime (affinePolynomial atom.direct₀ atom.direct₁ w)
        atom.amplitudeMultiplier)
    (hcoprimeConjugate :
      IsCoprime (affinePolynomial atom.direct₀ atom.direct₁ w)
        ((affinePolynomial atom.direct₀ atom.direct₁ w).map
          sigma.toRingHom)) :
    affinePolynomial atom.direct₀ atom.direct₁ w ∣ Cof := by
  let Cw := affinePolynomial atom.direct₀ atom.direct₁ w
  have hdvdProduct : Cw ∣
      atom.amplitudeMultiplier * (Cw.map sigma.toRingHom) * Cof := by
    refine ⟨atom.denominator * (Cof.map sigma.toRingHom), ?_⟩
    have hidentity' :
        atom.denominator * Cw * Cof.map sigma.toRingHom -
          atom.amplitudeMultiplier * Cw.map sigma.toRingHom * Cof = 0 := by
      simpa only [Cw, FrobeniusAmplitudeAtom.cofactorRelation] using hidentity
    have hrel := sub_eq_zero.mp hidentity'
    calc
      atom.amplitudeMultiplier * Cw.map sigma.toRingHom * Cof =
          atom.denominator * Cw * Cof.map sigma.toRingHom := hrel.symm
      _ = Cw * (atom.denominator * Cof.map sigma.toRingHom) := by ring
  have hcoprimeProduct :
      IsCoprime Cw (atom.amplitudeMultiplier * Cw.map sigma.toRingHom) :=
    hcoprimeAmplitude.mul_right hcoprimeConjugate
  exact hcoprimeProduct.dvd_of_dvd_mul_left hdvdProduct

end ProximityPrize.SubmissionLower
