import ProximityPrize.SubmissionLower.BCHKSMultiPinRankAccumulation6401

/-!
# The unconditional global affine-residual normal space

For any fixed affine polynomial line `p0+z*p1`, the residuals

`D_z = P_z-(p0+z*p1)`

span one fixed polynomial space `W`.  Evaluation at a domain coordinate is
therefore one fixed normal in `W^*`, independent of the owner.  This is the
normal space needed by multi-pin rank accumulation; no Frobenius selector or
rational locator is used.

The key flat statement is stronger than the generic received-direction cap.
As long as a prefix has not spanned `W^*`, a nonzero polynomial in `W`
annihilates its normal span.  Hence every coordinate in the flat is a root of
one degree-at-most-`131071` polynomial, and the flat has at most `131071`
coordinates.  This includes the last rank before spanning.

This file deliberately stops before claiming a benchmark owner bound.  The
remaining combinatorial adapter is to turn the backward multi-pin recurrence
into a count of spanning injective tuples and then apply weak-curve failure to
their owner fibres.
-/

namespace ProximityPrize.SubmissionLower
namespace BCHKSGlobalAffineResidualNormalSpace6401

open Polynomial
open scoped BigOperators
open BCHKSResidualFlatBasisCount6401

set_option maxHeartbeats 3000000
set_option maxRecDepth 1000000

def residualPolynomialDegreeCap6401 : Nat := 131071

section ResidualSpace

variable {F : Type*} [Field F]

/-- Residual from an arbitrary fixed affine polynomial line.  Taking the line
through two owners is the dimension-minimizing canonical choice. -/
noncomputable def globalAffineResidual6401
    (P : F → F[X]) (p0 p1 : F[X]) (z : F) : F[X] :=
  P z - (p0 + Polynomial.C z * p1)

/-- The affine polynomial line through two owner polynomials. -/
noncomputable def anchoredOwnerSlope6401
    (P : F → F[X]) (r s : F) : F[X] :=
  (s - r)⁻¹ • (P s - P r)

noncomputable def anchoredOwnerIntercept6401
    (P : F → F[X]) (r s : F) : F[X] :=
  P r - r • anchoredOwnerSlope6401 P r s

theorem anchoredOwnerLine_degree_le6401
    (P : F → F[X]) (r s : F)
    (hr : (P r).natDegree ≤ residualPolynomialDegreeCap6401)
    (hs : (P s).natDegree ≤ residualPolynomialDegreeCap6401) :
    (anchoredOwnerIntercept6401 P r s).natDegree ≤
        residualPolynomialDegreeCap6401 ∧
      (anchoredOwnerSlope6401 P r s).natDegree ≤
        residualPolynomialDegreeCap6401 := by
  have hslope : (anchoredOwnerSlope6401 P r s).natDegree ≤
      residualPolynomialDegreeCap6401 := by
    apply (Polynomial.natDegree_smul_le _ _).trans
    exact (Polynomial.natDegree_sub_le _ _).trans (max_le hs hr)
  exact ⟨(Polynomial.natDegree_sub_le _ _).trans
    (max_le hr ((Polynomial.natDegree_smul_le _ _).trans hslope)), hslope⟩

theorem anchoredOwnerResidual_at_anchors6401
    (P : F → F[X]) (r s : F) (hrs : r ≠ s) :
    globalAffineResidual6401 P
        (anchoredOwnerIntercept6401 P r s)
        (anchoredOwnerSlope6401 P r s) r = 0 ∧
      globalAffineResidual6401 P
        (anchoredOwnerIntercept6401 P r s)
        (anchoredOwnerSlope6401 P r s) s = 0 := by
  have hden : s - r ≠ 0 := sub_ne_zero.mpr hrs.symm
  constructor
  · simp only [globalAffineResidual6401, anchoredOwnerIntercept6401]
    rw [smul_eq_C_mul]
    ring
  · simp only [globalAffineResidual6401, anchoredOwnerIntercept6401,
      anchoredOwnerSlope6401]
    rw [smul_eq_C_mul, smul_eq_C_mul]
    have hinv : Polynomial.C ((s - r)⁻¹) * Polynomial.C (s - r) =
        (1 : F[X]) := by
      rw [← Polynomial.C_mul, inv_mul_cancel₀ hden, Polynomial.C_1]
    calc
      P s - (P r - Polynomial.C r *
          (Polynomial.C ((s - r)⁻¹) * (P s - P r)) +
        Polynomial.C s *
          (Polynomial.C ((s - r)⁻¹) * (P s - P r))) =
        P s - P r -
          (Polynomial.C (s - r) * Polynomial.C ((s - r)⁻¹)) *
            (P s - P r) := by
              rw [map_sub]
              ring
      _ = 0 := by
        rw [mul_comm (Polynomial.C (s - r))
          (Polynomial.C ((s - r)⁻¹)), hinv, one_mul, sub_self]

theorem globalAffineResidual_natDegree_le6401
    (P : F → F[X]) (p0 p1 : F[X]) (z : F)
    (hP : (P z).natDegree ≤ residualPolynomialDegreeCap6401)
    (hp0 : p0.natDegree ≤ residualPolynomialDegreeCap6401)
    (hp1 : p1.natDegree ≤ residualPolynomialDegreeCap6401) :
    (globalAffineResidual6401 P p0 p1 z).natDegree ≤
      residualPolynomialDegreeCap6401 := by
  unfold globalAffineResidual6401
  apply (Polynomial.natDegree_sub_le _ _).trans
  apply max_le hP
  apply (Polynomial.natDegree_add_le _ _).trans
  exact max_le hp0 (Polynomial.natDegree_C_mul_le _ _ |>.trans hp1)

/-- The fixed coefficient space generated by all owner residuals in `S`. -/
noncomputable def globalAffineResidualSpan6401
    (S : Finset F) (P : F → F[X]) (p0 p1 : F[X]) :
    Submodule F F[X] :=
  Submodule.span F (Set.range fun z : S =>
    globalAffineResidual6401 P p0 p1 z.1)

private theorem mem_degreeLT_of_natDegree_le
    (Q : F[X]) (K : Nat) (hQ : Q.natDegree ≤ K) :
    Q ∈ Polynomial.degreeLT F (K + 1) := by
  by_cases hzero : Q = 0
  · simp [hzero]
  · rw [Polynomial.mem_degreeLT, Polynomial.degree_eq_natDegree hzero]
    exact WithBot.coe_lt_coe.mpr (Nat.lt_succ_of_le hQ)

/-- The residual span lies in the benchmark message-polynomial space. -/
theorem globalAffineResidualSpan_le_degreeLT6401
    (S : Finset F) (P : F → F[X]) (p0 p1 : F[X])
    (hP : ∀ z ∈ S, (P z).natDegree ≤ residualPolynomialDegreeCap6401)
    (hp0 : p0.natDegree ≤ residualPolynomialDegreeCap6401)
    (hp1 : p1.natDegree ≤ residualPolynomialDegreeCap6401) :
    globalAffineResidualSpan6401 S P p0 p1 ≤
      Polynomial.degreeLT F (residualPolynomialDegreeCap6401 + 1) := by
  rw [globalAffineResidualSpan6401, Submodule.span_le]
  rintro Q ⟨z, rfl⟩
  exact mem_degreeLT_of_natDegree_le _ _
    (globalAffineResidual_natDegree_le6401 P p0 p1 z.1
      (hP z.1 z.2) hp0 hp1)

/-- Explicit finite-dimensional embedding supplied by the degree bound. -/
noncomputable def residualSpanDegreeEmbedding6401
    (W : Submodule F F[X]) (K : Nat)
    (hW : W ≤ Polynomial.degreeLT F (K + 1)) :
    W →ₗ[F] Polynomial.degreeLT F (K + 1) where
  toFun Q := ⟨Q.1, hW Q.2⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

theorem residualSpanDegreeEmbedding_injective6401
    (W : Submodule F F[X]) (K : Nat)
    (hW : W ≤ Polynomial.degreeLT F (K + 1)) :
    Function.Injective (residualSpanDegreeEmbedding6401 W K hW) := by
  intro Q R hQR
  have hv :
      (residualSpanDegreeEmbedding6401 W K hW Q).1 =
        (residualSpanDegreeEmbedding6401 W K hW R).1 :=
    congrArg Subtype.val hQR
  exact Subtype.ext hv

/-- On an agreement coordinate, the residual value is affine in the
challenge, even though the received word is not polynomial in the
coordinate. -/
theorem eval_globalAffineResidual_eq_affine_of_agreement6401
    (P : F → F[X]) (p0 p1 : F[X])
    (z x u0 u1 : F)
    (hagree : (P z).eval x = u0 + z * u1) :
    (globalAffineResidual6401 P p0 p1 z).eval x =
      (u0 - p0.eval x) + z * (u1 - p1.eval x) := by
  simp only [globalAffineResidual6401, Polynomial.eval_sub,
    Polynomial.eval_add, Polynomial.eval_mul, Polynomial.eval_C, hagree]
  ring

end ResidualSpace

section EvaluationNormals

variable {F I : Type*} [Field F] [DecidableEq I]

/-- Evaluation at one coordinate, restricted to a fixed polynomial
submodule. -/
noncomputable def residualEvalNormal6401
    (alpha : I → F) (W : Submodule F F[X]) (i : I) : Module.Dual F W where
  toFun Q := Q.1.eval (alpha i)
  map_add' Q R := by simp
  map_smul' c Q := by simp

/-- Evaluation on an ordered prefix. -/
noncomputable def residualPrefixEvalMap6401
    (alpha : I → F) (W : Submodule F F[X])
    {s : Nat} (f : Fin s → I) : W →ₗ[F] (Fin s → F) :=
  LinearMap.pi fun j => residualEvalNormal6401 alpha W (f j)

private theorem card_le_natDegree_of_eval_zero
    (alpha : I ↪ F) (Q : F[X]) (hQ : Q ≠ 0)
    (B : Finset I) (hroot : ∀ i ∈ B, Q.eval (alpha i) = 0) :
    B.card ≤ Q.natDegree := by
  classical
  let roots : Finset F := B.map alpha
  have hsub : roots ⊆ Q.roots.toFinset := by
    intro x hx
    obtain ⟨i, hi, rfl⟩ := Finset.mem_map.mp hx
    exact Multiset.mem_toFinset.mpr
      ((Polynomial.mem_roots hQ).2 (hroot i hi))
  calc
    B.card = roots.card := by simp [roots]
    _ ≤ Q.roots.toFinset.card := Finset.card_le_card hsub
    _ ≤ Q.roots.card := Multiset.toFinset_card_le _
    _ ≤ Q.natDegree := Polynomial.card_roots' Q

/-- A proper span of evaluation normals has at most `K` coordinates in its
flat.  The proof extracts a nonzero polynomial in the kernel of the prefix
evaluation map, then applies the ordinary root bound. -/
theorem residualEvalNormal_flat_card_le_degree
    (alpha : I ↪ F) (W : Submodule F F[X])
    [FiniteDimensional F W]
    (K : Nat)
    (hW : W ≤ Polynomial.degreeLT F (K + 1))
    (A : Finset I) {s : Nat} (f : Fin s → I)
    (hs : s < Module.finrank F W) :
    (normalSpanFlat (F := F) A
      (residualEvalNormal6401 alpha W) f).card ≤ K := by
  classical
  let T := residualPrefixEvalMap6401 alpha W f
  have hnotinj : ¬ Function.Injective T := by
    intro hinj
    have hle := LinearMap.finrank_le_finrank_of_injective hinj
    have htarget : Module.finrank F (Fin s → F) = s := by
      simp [Module.finrank_fintype_fun_eq_card]
    rw [htarget] at hle
    omega
  have hker : LinearMap.ker T ≠ ⊥ := by
    intro hbot
    exact hnotinj (LinearMap.ker_eq_bot.mp hbot)
  obtain ⟨Q, hQker, hQne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hker
  have hTQ : T Q = 0 := LinearMap.mem_ker.mp hQker
  have hprefix : ∀ j, residualEvalNormal6401 alpha W (f j) Q = 0 := by
    intro j
    exact congrFun hTQ j
  have annihilator : ∀ L : Module.Dual F W,
      L ∈ Submodule.span F
          (Set.range (residualEvalNormal6401 alpha W ∘ f)) →
        L Q = 0 := by
    intro L hL
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hL
    · rintro L ⟨j, rfl⟩
      exact hprefix j
    · exact LinearMap.zero_apply _
    · intro L M _hL _hM hLzero hMzero
      simp [hLzero, hMzero]
    · intro c L _hL hLzero
      simp [hLzero]
  have hQpoly : Q.1 ≠ 0 := by
    intro hzero
    apply hQne
    apply Subtype.ext
    exact hzero
  have hQdegree : Q.1.natDegree ≤ K := by
    have hmem := hW Q.2
    by_cases hzero : Q.1 = 0
    · simp [hzero]
    · rw [Polynomial.mem_degreeLT,
        Polynomial.degree_eq_natDegree hzero] at hmem
      exact Nat.le_of_lt_succ (WithBot.coe_lt_coe.mp hmem)
  let B := normalSpanFlat (F := F) A
    (residualEvalNormal6401 alpha W) f
  have hroot : ∀ i ∈ B, Q.1.eval (alpha i) = 0 := by
    intro i hi
    have hspan : residualEvalNormal6401 alpha W i ∈
        Submodule.span F
          (Set.range (residualEvalNormal6401 alpha W ∘ f)) := by
      exact (Finset.mem_filter.mp hi).2
    exact annihilator _ hspan
  exact (card_le_natDegree_of_eval_zero alpha Q.1 hQpoly B hroot).trans
    hQdegree

/-- Rank-state form of the same flat bound.  Unlike
`residualEvalNormal_flat_card_le_degree`, the tuple may be much longer than
the residual dimension; it is enough that its normal span is still proper.
This is the exact hypothesis needed by multi-pin walks with rank-preserving
steps. -/
theorem residualEvalNormal_flat_card_le_degree_of_span_ne_top
    (alpha : I ↪ F) (W : Submodule F F[X])
    [FiniteDimensional F W]
    (K : Nat)
    (hW : W ≤ Polynomial.degreeLT F (K + 1))
    (A : Finset I) {s : Nat} (f : Fin s → I)
    (hproper : Submodule.span F
      (Set.range (residualEvalNormal6401 alpha W ∘ f)) ≠ ⊤) :
    (normalSpanFlat (F := F) A
      (residualEvalNormal6401 alpha W) f).card ≤ K := by
  classical
  let Phi : Submodule F (Module.Dual F W) := Submodule.span F
    (Set.range (residualEvalNormal6401 alpha W ∘ f))
  have hco : Phi.dualCoannihilator ≠ ⊥ := by
    intro hbot
    have hsum := Subspace.finrank_add_finrank_dualCoannihilator_eq Phi
    rw [hbot, finrank_bot, add_zero] at hsum
    have htop : Phi = ⊤ := Submodule.eq_top_of_finrank_eq <| by
      rw [Subspace.dual_finrank_eq]
      exact hsum
    exact hproper htop
  obtain ⟨Q, hQco, hQne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hco
  have hannihilator : ∀ L : Module.Dual F W, L ∈ Phi → L Q = 0 := by
    exact (Submodule.mem_dualCoannihilator Q).mp hQco
  have hQpoly : Q.1 ≠ 0 := by
    intro hzero
    apply hQne
    apply Subtype.ext
    exact hzero
  have hQdegree : Q.1.natDegree ≤ K := by
    have hmem := hW Q.2
    rw [Polynomial.mem_degreeLT,
      Polynomial.degree_eq_natDegree hQpoly] at hmem
    exact Nat.le_of_lt_succ (WithBot.coe_lt_coe.mp hmem)
  let B := normalSpanFlat (F := F) A
    (residualEvalNormal6401 alpha W) f
  have hroot : ∀ i ∈ B, Q.1.eval (alpha i) = 0 := by
    intro i hi
    have hspan : residualEvalNormal6401 alpha W i ∈ Phi := by
      exact (Finset.mem_filter.mp hi).2
    exact hannihilator _ hspan
  exact (card_le_natDegree_of_eval_zero alpha Q.1 hQpoly B hroot).trans
    hQdegree

/-- Benchmark specialization: every proper evaluation-normal flat of the
global affine-residual span has at most `131071` coordinates. -/
theorem globalAffineResidual_flat_card_le_131071_6401
    (alpha : I ↪ F) (W : Submodule F F[X])
    [FiniteDimensional F W]
    (hW : W ≤ Polynomial.degreeLT F
      (residualPolynomialDegreeCap6401 + 1))
    (A : Finset I) {s : Nat} (f : Fin s → I)
    (hs : s < Module.finrank F W) :
    (normalSpanFlat (F := F) A
      (residualEvalNormal6401 alpha W) f).card ≤ 131071 := by
  simpa [residualPolynomialDegreeCap6401] using
    residualEvalNormal_flat_card_le_degree alpha W
      residualPolynomialDegreeCap6401 hW A f hs

/-! ## Spanning pins force an affine owner curve -/

def ResidualPinsSpan6401
    (alpha : I → F) (W : Submodule F F[X]) (pins : Finset I) : Prop :=
  Submodule.span F
      (Set.range fun i : pins => residualEvalNormal6401 alpha W i.1) = ⊤

/-- Ordered injective pins whose evaluation normals span the whole residual
dual.  This is the owner-independent tuple predicate used by the exact
multi-pin incidence swap. -/
def spanningResidualNormalTuples6401
    (alpha : I → F) (W : Submodule F F[X])
    (t : Nat) (f : Fin t → I) : Prop :=
  Function.Injective f ∧
    Submodule.span F
      (Set.range (residualEvalNormal6401 alpha W ∘ f)) = ⊤

noncomputable instance spanningResidualNormalTuples_decidable6401
    (alpha : I → F) (W : Submodule F F[X]) (t : Nat) :
    DecidablePred (spanningResidualNormalTuples6401 alpha W t) :=
  Classical.decPred _

/-- Passing from an ordered spanning tuple to its underlying pin set does
not lose the spanning property. -/
theorem residualPinsSpan_image_of_tupleSpan6401
    (alpha : I → F) (W : Submodule F F[X])
    {t : Nat} (f : Fin t → I)
    (hspan : Submodule.span F
      (Set.range (residualEvalNormal6401 alpha W ∘ f)) = ⊤) :
    ResidualPinsSpan6401 alpha W (Finset.univ.image f) := by
  classical
  have hrange :
      Set.range (fun i : ↑(Finset.univ.image f) ↦
        residualEvalNormal6401 alpha W i.1) =
        Set.range (residualEvalNormal6401 alpha W ∘ f) := by
    ext L
    constructor
    · rintro ⟨i, rfl⟩
      obtain ⟨j, _hj, hij⟩ := Finset.mem_image.mp i.2
      refine ⟨j, ?_⟩
      simp only [Function.comp_apply]
      rw [hij]
    · rintro ⟨j, rfl⟩
      refine ⟨⟨f j, Finset.mem_image.mpr
        ⟨j, Finset.mem_univ _, rfl⟩⟩, rfl⟩
  rw [ResidualPinsSpan6401, hrange, hspan]

/-- An independent tuple of length equal to the dual dimension spans, hence
gives a valid residual pin set. -/
theorem residualPinsSpan_image_of_independent_finrank6401
    (alpha : I → F) (W : Submodule F F[X]) [FiniteDimensional F W]
    {t : Nat} (f : Fin t → I)
    (hli : LinearIndependent F (residualEvalNormal6401 alpha W ∘ f))
    (ht : t = Module.finrank F W) :
    ResidualPinsSpan6401 alpha W (Finset.univ.image f) := by
  apply residualPinsSpan_image_of_tupleSpan6401 alpha W f
  apply hli.span_eq_top_of_card_eq_finrank'
  simpa [ht] using (dual_finrank_eq (K := F) (V := W)).symm

/-- If one pin set spans the fixed residual dual and at least `1183` owners
agree on every pin, those owners lie on an affine polynomial line.  This is
the deterministic endpoint consumed by multi-pin averaging. -/
theorem curveWitness_of_residualPinsSpan6401
    (alpha : I → F) (u0 u1 : I → F)
    (S T : Finset F) (P : F → F[X]) (p0 p1 : F[X])
    (pins : Finset I)
    (hTsub : T ⊆ S)
    (hTcard : BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 ≤ T.card)
    (hPdegree : ∀ z ∈ S,
      (P z).natDegree ≤ residualPolynomialDegreeCap6401)
    (hp0 : p0.natDegree ≤ residualPolynomialDegreeCap6401)
    (hp1 : p1.natDegree ≤ residualPolynomialDegreeCap6401)
    (hagree : ∀ z ∈ T, ∀ i ∈ pins,
      (P z).eval (alpha i) = u0 i + z * u1 i)
    (hspan : ResidualPinsSpan6401 alpha
      (globalAffineResidualSpan6401 S P p0 p1) pins) :
    BCHKSTwoFrobeniusWeakCurveSeed6401.PolynomialAffineCurveWitness6401 S P := by
  classical
  let W := globalAffineResidualSpan6401 S P p0 p1
  let D : F → F[X] := globalAffineResidual6401 P p0 p1
  have htwo : 1 < T.card := by
    have hout : 2 ≤
        BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 := by
      native_decide
    omega
  obtain ⟨r, hr, s, hs, hrs⟩ := Finset.one_lt_card.mp htwo
  have hrS : r ∈ S := hTsub hr
  have hsS : s ∈ S := hTsub hs
  have hden : s - r ≠ 0 := sub_ne_zero.mpr hrs.symm
  let q1 : F[X] := (s - r)⁻¹ • (D s - D r)
  let q0 : F[X] := D r - r • q1
  let out0 : F[X] := p0 + q0
  let out1 : F[X] := p1 + q1
  have hDmem : ∀ z ∈ S, D z ∈ W := by
    intro z hz
    apply Submodule.subset_span
    exact ⟨⟨z, hz⟩, rfl⟩
  have hq1W : q1 ∈ W := by
    exact W.smul_mem _ (W.sub_mem (hDmem s hsS) (hDmem r hrS))
  have hq0W : q0 ∈ W := W.sub_mem (hDmem r hrS) (W.smul_mem _ hq1W)
  have hDdegree : ∀ z ∈ S,
      (D z).natDegree ≤ residualPolynomialDegreeCap6401 := by
    intro z hz
    exact globalAffineResidual_natDegree_le6401 P p0 p1 z
      (hPdegree z hz) hp0 hp1
  have hq1degree : q1.natDegree ≤ residualPolynomialDegreeCap6401 := by
    apply (Polynomial.natDegree_smul_le _ _).trans
    exact (Polynomial.natDegree_sub_le _ _).trans
      (max_le (hDdegree s hsS) (hDdegree r hrS))
  have hq0degree : q0.natDegree ≤ residualPolynomialDegreeCap6401 := by
    apply (Polynomial.natDegree_sub_le _ _).trans
    exact max_le (hDdegree r hrS)
      ((Polynomial.natDegree_smul_le _ _).trans hq1degree)
  have hout0degree : out0.natDegree ≤ residualPolynomialDegreeCap6401 := by
    exact (Polynomial.natDegree_add_le _ _).trans (max_le hp0 hq0degree)
  have hout1degree : out1.natDegree ≤ residualPolynomialDegreeCap6401 := by
    exact (Polynomial.natDegree_add_le _ _).trans (max_le hp1 hq1degree)
  have hresidualLine : ∀ z ∈ T, D z = q0 + z • q1 := by
    intro z hz
    let H : W := ⟨D z - (q0 + z • q1), by
      exact W.sub_mem (hDmem z (hTsub hz))
        (W.add_mem hq0W (W.smul_mem _ hq1W))⟩
    have hHeval : ∀ i : pins,
        residualEvalNormal6401 alpha W i.1 H = 0 := by
      intro i
      have hir := hagree r hr i.1 i.2
      have his := hagree s hs i.1 i.2
      have hiz := hagree z hz i.1 i.2
      have hDr := eval_globalAffineResidual_eq_affine_of_agreement6401
        P p0 p1 r (alpha i.1) (u0 i.1) (u1 i.1) hir
      have hDs := eval_globalAffineResidual_eq_affine_of_agreement6401
        P p0 p1 s (alpha i.1) (u0 i.1) (u1 i.1) his
      have hDz := eval_globalAffineResidual_eq_affine_of_agreement6401
        P p0 p1 z (alpha i.1) (u0 i.1) (u1 i.1) hiz
      have hq1eval : q1.eval (alpha i.1) = u1 i.1 - p1.eval (alpha i.1) := by
        dsimp [q1, D]
        simp only [Polynomial.eval_smul, Polynomial.eval_sub, hDs, hDr]
        calc
          (s - r)⁻¹ *
              (((u0 i.1 - p0.eval (alpha i.1)) +
                  s * (u1 i.1 - p1.eval (alpha i.1))) -
                ((u0 i.1 - p0.eval (alpha i.1)) +
                  r * (u1 i.1 - p1.eval (alpha i.1)))) =
              (s - r)⁻¹ * (s - r) *
                (u1 i.1 - p1.eval (alpha i.1)) := by ring
          _ = u1 i.1 - p1.eval (alpha i.1) := by
            rw [inv_mul_cancel₀ hden, one_mul]
      have hq0eval : q0.eval (alpha i.1) =
          u0 i.1 - p0.eval (alpha i.1) := by
        dsimp [q0]
        simp only [Polynomial.eval_sub, Polynomial.eval_smul, hq1eval]
        rw [show (D r).eval (alpha i.1) =
          (u0 i.1 - p0.eval (alpha i.1)) +
            r * (u1 i.1 - p1.eval (alpha i.1)) by
              simpa [D] using hDr]
        ring
      change (D z - (q0 + z • q1)).eval (alpha i.1) = 0
      simp only [Polynomial.eval_sub, Polynomial.eval_add,
        Polynomial.eval_smul, hq0eval, hq1eval]
      rw [show (D z).eval (alpha i.1) =
        (u0 i.1 - p0.eval (alpha i.1)) +
          z * (u1 i.1 - p1.eval (alpha i.1)) by
            simpa [D] using hDz]
      ring
    have hall : ∀ L : Module.Dual F W, L H = 0 := by
      intro L
      have hL : L ∈ Submodule.span F
          (Set.range fun i : pins => residualEvalNormal6401 alpha W i.1) := by
        rw [hspan]
        trivial
      refine Submodule.span_induction ?_ ?_ ?_ ?_ hL
      · rintro L ⟨i, rfl⟩
        exact hHeval i
      · exact LinearMap.zero_apply _
      · intro L M _hL _hM hLzero hMzero
        simp [hLzero, hMzero]
      · intro c L _hL hLzero
        simp [hLzero]
    have hHzero : H = 0 :=
      (Module.forall_dual_apply_eq_zero_iff F H).mp hall
    exact sub_eq_zero.mp (congrArg Subtype.val hHzero)
  refine ⟨out0, out1, hout0degree, hout1degree, T, hTsub, hTcard, ?_⟩
  intro z hz
  have hline := hresidualLine z hz
  dsimp [D, globalAffineResidual6401] at hline
  dsimp [out0, out1]
  rw [smul_eq_C_mul] at hline
  calc
    P z = p0 + Polynomial.C z * p1 + q0 + Polynomial.C z * q1 := by
      linear_combination hline
    _ = p0 + q0 + Polynomial.C z * (p1 + q1) := by ring

/-! ## Exact owner-incidence endpoints -/

/-- Conditional `rho=34` endpoint.  Everything after the row-mass premise is
now formal: exact falling-factorial incidence averaging finds `1183` owners
on one spanning pin set, and that pin set forces an affine polynomial curve.

The sole premise not yet derived from the flat caps is `hrow`, namely the
weighted tuple-tree assertion that the executable multi-pin mass is a lower
bound for every owner row. -/
theorem curveWitness_of_multiPinSpanningRowMass6401
    (alpha : I → F) (u0 u1 : I → F)
    (Uset : Finset I) (S : Finset F) (A : F → Finset I)
    (P : F → F[X]) (p0 p1 : F[X])
    (hUcard : Uset.card =
      BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401)
    (hScard : BCHKSMultiPinRankAccumulation6401.multiPinOwnerMass6401 ≤
      S.card)
    (hsub : ∀ z ∈ S, A z ⊆ Uset)
    (hPdegree : ∀ z ∈ S,
      (P z).natDegree ≤ residualPolynomialDegreeCap6401)
    (hp0 : p0.natDegree ≤ residualPolynomialDegreeCap6401)
    (hp1 : p1.natDegree ≤ residualPolynomialDegreeCap6401)
    (hagree : ∀ z ∈ S, ∀ i ∈ A z,
      (P z).eval (alpha i) = u0 i + z * u1 i)
    (hrow : ∀ z ∈ S,
      BCHKSMultiPinRankAccumulation6401.pureEvalMultiPinSpanningMass6401
          34 71 ≤
        (goodTuples (A z)
          (spanningResidualNormalTuples6401 alpha
            (globalAffineResidualSpan6401 S P p0 p1)) 71).card) :
    BCHKSTwoFrobeniusWeakCurveSeed6401.PolynomialAffineCurveWitness6401 S P := by
  classical
  let W := globalAffineResidualSpan6401 S P p0 p1
  let Pred := spanningResidualNormalTuples6401 alpha W
  let mass :=
    BCHKSMultiPinRankAccumulation6401.pureEvalMultiPinSpanningMass6401 34 71
  by_contra hfail
  have hfiber : ∀ f ∈ goodTuples Uset Pred 71,
      (S.filter fun z ↦ f ∈ goodTuples (A z) Pred 71).card ≤ 1182 := by
    intro f hf
    by_contra hcap
    let T := S.filter fun z ↦ f ∈ goodTuples (A z) Pred 71
    let pins : Finset I := Finset.univ.image f
    have hTgt : 1182 < T.card := by
      dsimp [T]
      omega
    have hTcard :
        BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 ≤ T.card := by
      have hout :
          BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 = 1183 := by
        native_decide
      rw [hout]
      exact hTgt
    have hTsub : T ⊆ S := by
      intro z hz
      exact (Finset.mem_filter.mp hz).1
    have hfpred : Pred 71 f := (mem_goodTuples_iff Uset Pred).mp hf |>.2
    have hpinsSpan : ResidualPinsSpan6401 alpha W pins := by
      exact residualPinsSpan_image_of_tupleSpan6401 alpha W f hfpred.2
    have hTpins : ∀ z ∈ T, ∀ i ∈ pins,
        (P z).eval (alpha i) = u0 i + z * u1 i := by
      intro z hz i hi
      have hfrow : f ∈ goodTuples (A z) Pred 71 :=
        (Finset.mem_filter.mp hz).2
      have hcoords := (mem_goodTuples_iff (A z) Pred).mp hfrow |>.1
      obtain ⟨j, _hj, rfl⟩ := Finset.mem_image.mp hi
      exact hagree z (hTsub hz) (f j) (hcoords j)
    apply hfail
    exact curveWitness_of_residualPinsSpan6401 alpha u0 u1 S T P p0 p1 pins
      hTsub hTcard hPdegree hp0 hp1 hTpins hpinsSpan
  have hcount :=
    BCHKSMultiPinRankAccumulation6401.ownerCard_mul_tupleMass_le_descFactorial_mul_fiberCap6401
        Uset S A Pred 71 mass 1182 hsub
        (fun z hz ↦ hrow z hz) hfiber
        (fun f hf ↦ (mem_goodTuples_iff Uset Pred).mp hf |>.2.1)
  rw [hUcard] at hcount
  have hexact :=
    BCHKSMultiPinRankAccumulation6401.pureEval_rho34_t71_retains_1183_exact6401
  have hmass :
      BCHKSMultiPinRankAccumulation6401.multiPinOwnerMass6401 * mass ≤
        S.card * mass := Nat.mul_le_mul_right mass hScard
  have hbad :
      BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 *
          BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial 71 ≤
        BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial 71 *
          1182 :=
    hexact.trans (hmass.trans hcount)
  have hout :
      BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 = 1183 := by
    native_decide
  have hpos : 0 <
      BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial 71 := by
    rw [Nat.descFactorial_pos]
    native_decide
  rw [hout] at hbad
  omega

/-- Fully unconditional fixed-space endpoint from the ordinary greedy basis
count.  For a high-mass owner family, weak affine-curve failure forces the
global affine-residual coefficient span to have dimension at least `22`.

This theorem uses only the actual owner agreement rows, polynomial root
bounds, and finite incidence averaging.  It does not use a Frobenius
certificate or a rational-locator atom. -/
theorem residualSpan_finrank_ge_22_of_noCurve6401
    (alpha : I ↪ F) (u0 u1 : I → F)
    (Uset : Finset I) (S : Finset F) (A : F → Finset I)
    (P : F → F[X]) (p0 p1 : F[X])
    (hUcard : Uset.card =
      BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401)
    (hScard : BCHKSMultiPinRankAccumulation6401.multiPinOwnerMass6401 ≤
      S.card)
    (hsub : ∀ z ∈ S, A z ⊆ Uset)
    (hrow : ∀ z ∈ S,
      BCHKSMultiPinRankAccumulation6401.multiPinRow6401 ≤ (A z).card)
    (hPdegree : ∀ z ∈ S,
      (P z).natDegree ≤ residualPolynomialDegreeCap6401)
    (hp0 : p0.natDegree ≤ residualPolynomialDegreeCap6401)
    (hp1 : p1.natDegree ≤ residualPolynomialDegreeCap6401)
    (hagree : ∀ z ∈ S, ∀ i ∈ A z,
      (P z).eval (alpha i) = u0 i + z * u1 i)
    (hfail : ¬ BCHKSTwoFrobeniusWeakCurveSeed6401.PolynomialAffineCurveWitness6401
      S P) :
    22 ≤ Module.finrank F (globalAffineResidualSpan6401 S P p0 p1) := by
  classical
  let W := globalAffineResidualSpan6401 S P p0 p1
  have hW : W ≤ Polynomial.degreeLT F
      (residualPolynomialDegreeCap6401 + 1) := by
    exact globalAffineResidualSpan_le_degreeLT6401 S P p0 p1
      hPdegree hp0 hp1
  let emb := residualSpanDegreeEmbedding6401 W
    residualPolynomialDegreeCap6401 hW
  letI : FiniteDimensional F W := FiniteDimensional.of_injective emb
    (residualSpanDegreeEmbedding_injective6401 W
      residualPolynomialDegreeCap6401 hW)
  change 22 ≤ Module.finrank F W
  by_contra hdim
  have hdimlt : Module.finrank F W < 22 := Nat.lt_of_not_ge hdim
  let D : Fin 22 := ⟨Module.finrank F W, hdimlt⟩
  let normal : I → Module.Dual F W := residualEvalNormal6401 alpha W
  have hflat : ∀ z ∈ S, ∀ s < D.val,
      ∀ f ∈ goodTuples (A z)
          (independentNormalTuples (F := F) normal) s,
        (normalSpanFlat (F := F) (A z) normal f).card ≤
          residualPolynomialDegreeCap6401 := by
    intro z hz s hs f hf
    exact residualEvalNormal_flat_card_le_degree alpha W
      residualPolynomialDegreeCap6401 hW (A z) f (by
        change s < Module.finrank F W
        exact hs)
  have hfiber : ∀ f ∈ goodTuples Uset
      (independentNormalTuples (F := F) normal) D.val,
      (S.filter fun z ↦ f ∈ goodTuples (A z)
        (independentNormalTuples (F := F) normal) D.val).card ≤ 1182 := by
    intro f hf
    by_contra hcap
    let T := S.filter fun z ↦ f ∈ goodTuples (A z)
      (independentNormalTuples (F := F) normal) D.val
    let pins : Finset I := Finset.univ.image f
    have hTgt : 1182 < T.card := by
      dsimp [T]
      omega
    have hTcard :
        BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 ≤ T.card := by
      have hout :
          BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 = 1183 := by
        native_decide
      rw [hout]
      exact hTgt
    have hTsub : T ⊆ S := by
      intro z hz
      exact (Finset.mem_filter.mp hz).1
    have hli : LinearIndependent F (normal ∘ f) :=
      (mem_goodTuples_iff Uset
        (independentNormalTuples (F := F) normal)).mp hf |>.2
    have hpinsSpan : ResidualPinsSpan6401 alpha W pins := by
      apply residualPinsSpan_image_of_independent_finrank6401 alpha W f
      · exact hli
      · rfl
    have hTpins : ∀ z ∈ T, ∀ i ∈ pins,
        (P z).eval (alpha i) = u0 i + z * u1 i := by
      intro z hz i hi
      have hfrow : f ∈ goodTuples (A z)
          (independentNormalTuples (F := F) normal) D.val :=
        (Finset.mem_filter.mp hz).2
      have hcoords := (mem_goodTuples_iff (A z)
        (independentNormalTuples (F := F) normal)).mp hfrow |>.1
      obtain ⟨j, _hj, rfl⟩ := Finset.mem_image.mp hi
      exact hagree z (hTsub hz) (f j) (hcoords j)
    apply hfail
    exact curveWitness_of_residualPinsSpan6401 alpha u0 u1 S T P p0 p1 pins
      hTsub hTcard hPdegree hp0 hp1 hTpins hpinsSpan
  have hcount :=
    BCHKSMultiPinRankAccumulation6401.ownerCard_mul_linearFlatGaps_le_descFactorial_mul_fiberCap6401
        Uset S A normal (fun _ ↦ residualPolynomialDegreeCap6401)
        BCHKSMultiPinRankAccumulation6401.multiPinRow6401 D.val 1182
        hsub hrow hflat hfiber
  rw [hUcard] at hcount
  have hcount' :
      S.card *
          (BCHKSMultiPinRankAccumulation6401.multiPinRow6401 -
            residualPolynomialDegreeCap6401) ^ D.val ≤
        BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial
            D.val * 1182 := by
    simpa using hcount
  have hexact :=
    BCHKSMultiPinRankAccumulation6401.pureEval_greedyBasis_all_dimensions_lt22_exact6401
      D
  have hmass :
      BCHKSMultiPinRankAccumulation6401.multiPinOwnerMass6401 *
          (BCHKSMultiPinRankAccumulation6401.multiPinRow6401 -
            BCHKSMultiPinRankAccumulation6401.multiPinDegreeCap6401) ^ D.val ≤
        S.card *
          (BCHKSMultiPinRankAccumulation6401.multiPinRow6401 -
            BCHKSMultiPinRankAccumulation6401.multiPinDegreeCap6401) ^ D.val :=
    Nat.mul_le_mul_right _ hScard
  have hcapEq : residualPolynomialDegreeCap6401 =
      BCHKSMultiPinRankAccumulation6401.multiPinDegreeCap6401 := by
    native_decide
  rw [hcapEq] at hcount'
  have hbad :
      BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 *
          BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial
            D.val ≤
        BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial
            D.val * 1182 :=
    hexact.trans (hmass.trans hcount')
  have hout :
      BCHKSTwoFrobeniusWeakCurveSeed6401.weakCurveOutput6401 = 1183 := by
    native_decide
  have hpos : 0 <
      BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401.descFactorial
        D.val := by
    rw [Nat.descFactorial_pos]
    exact (Nat.le_of_lt D.isLt).trans (by native_decide)
  rw [hout] at hbad
  omega

end EvaluationNormals

end BCHKSGlobalAffineResidualNormalSpace6401
end ProximityPrize.SubmissionLower
