import ProximityPrize.SubmissionLower.BCHKSFiveOwnerCorrectionGeometry6401
import ProximityPrize.SubmissionLower.BCHKSGlobalAffineResidualNormalSpace6401
import ProximityPrize.SubmissionLower.BCHKSMixedHermiteRowSpan6400

/-!
# What universal augmented-minor vanishing really implies

For a correction space with columns `v_j`, adjoin one error column `E`.
If every square coordinate minor of `[E | v]` vanishes, the augmented
columns are dependent.  When the correction columns are independent this
says exactly that `E` belongs to their span over the coefficient field.

In the polynomial application, choosing a constant evaluation basis upgrades
the resulting function-field coefficients to one polynomial correction
curve.  At challenge degree four, removing the constant and linear terms
leaves a residual span generated by only three polynomials.  It need not be
one-dimensional: the quadratic/cubic profile recorded below is a genuine
two-direction counterexample to the implication

`all augmented determinants vanish -> scalar correction chart`.

Thus the sound nonproper dichotomy is "evaluation rank-flat or a bounded
global correction curve".  Scalar/clone structure requires an additional
rank-one hypothesis on the nonlinear coefficient polynomials.
-/

namespace ProximityPrize.SubmissionLower
namespace BCHKSNonproperAugmentedResidualAudit6401

open Polynomial
open BCHKSFiveOwnerCorrectionGeometry6401
open BCHKSGlobalAffineResidualNormalSpace6401

set_option maxHeartbeats 2000000
set_option maxRecDepth 1000000

/-! ## Universal minors mean augmented-column dependence -/

/-- The full coordinate-by-augmented-column matrix. -/
def globalCorrectionAugmentedMatrix6401
    {K Coord J : Type*}
    (v : Coord → J → K) (E : Coord → K) :
    Matrix Coord (Option J) K :=
  fun i o => Option.casesOn' o (E i) (fun j => v i j)

/-- If every square row selection of a finite matrix has zero determinant,
its columns cannot be linearly independent.  This is the exact linear-algebra
content of the nonproper augmented-determinant branch. -/
theorem augmentedColumns_dependent_of_all_rowMinors_zero6401
    {K Coord J : Type*} [Field K]
    [Fintype Coord] [DecidableEq Coord]
    [Fintype J] [DecidableEq J]
    (M : Matrix Coord (Option J) K)
    (hall : ∀ x : Option J → Coord,
      (M.submatrix x _root_.id).det = 0) :
    ¬ LinearIndependent K M.transpose.row := by
  intro hli
  obtain ⟨x, hx⟩ :=
    BCHKSMixedHermiteRowSpan6400.exists_columns_det_ne_zero_of_rows_linearIndependent
      M.transpose hli
  have hmatrix :
      M.transpose.submatrix _root_.id x =
        (M.submatrix x _root_.id).transpose := by
    ext i j
    rfl
  rw [hmatrix, Matrix.det_transpose, hall x] at hx
  exact hx rfl

/-- With independent correction columns, universal augmented-minor
vanishing puts the error column in their span.  No scalar/clone conclusion
is present: the span can have any correction-space dimension. -/
theorem errorColumn_mem_span_of_all_rowMinors_zero6401
    {K Coord J : Type*} [Field K]
    [Fintype Coord] [DecidableEq Coord]
    [Fintype J] [DecidableEq J]
    (v : Coord → J → K) (E : Coord → K)
    (hv : LinearIndependent K (fun j : J => fun i => v i j))
    (hall : ∀ x : Option J → Coord,
      ((globalCorrectionAugmentedMatrix6401 v E).submatrix
        x _root_.id).det = 0) :
    E ∈ Submodule.span K
      (Set.range fun j : J => fun i => v i j) := by
  let M : Matrix Coord (Option J) K :=
    globalCorrectionAugmentedMatrix6401 v E
  have hminor : ∀ x : Option J → Coord,
      (M.submatrix x _root_.id).det = 0 := by
    intro x
    simpa [M, correctionAugmentedMatrix6401] using hall x
  have hdep : ¬ LinearIndependent K
      (fun o : Option J => Option.casesOn' o E
        (fun j => fun i => v i j)) := by
    have hdepM :=
      augmentedColumns_dependent_of_all_rowMinors_zero6401 M hminor
    change ¬ LinearIndependent K (fun o => fun i => M i o) at hdepM
    change ¬ LinearIndependent K (fun o => fun i =>
      Option.casesOn' o (E i) (fun j => v i j)) at hdepM
    have hfun :
        (fun o : Option J => Option.casesOn' o E
          (fun j => fun i => v i j)) =
        (fun o : Option J => fun i =>
          Option.casesOn' o (E i) (fun j => v i j)) := by
      funext o i
      cases o <;> rfl
    rw [hfun]
    exact hdepM
  by_contra hnot
  exact hdep (linearIndependent_option'.2 ⟨hv, hnot⟩)

/-- Polynomial correction-matrix specialization of the preceding theorem.
All identically-zero polynomial minors remain zero over `F(Z)`, so the
polynomial error column belongs to the function-field span of the constant
correction columns.  A chosen constant evaluation basis is what subsequently
descends these rational coefficients back to bounded polynomials. -/
theorem polynomialErrorColumn_mem_ratFuncSpan_of_all_dets_zero6401
    {F Coord J : Type*} [Field F]
    [Fintype Coord] [DecidableEq Coord]
    [Fintype J] [DecidableEq J]
    (v : Coord → J → F) (E : Coord → F[X])
    (hv : LinearIndependent (RatFunc F)
      (fun j : J => fun i => algebraMap F (RatFunc F) (v i j)))
    (hall : ∀ x : Option J → Coord,
      (correctionAugmentedMatrix6401 v E x).det = 0) :
    (fun i => algebraMap F[X] (RatFunc F) (E i)) ∈
      Submodule.span (RatFunc F)
        (Set.range fun j : J => fun i =>
          algebraMap F (RatFunc F) (v i j)) := by
  let vR : Coord → J → RatFunc F := fun i j =>
    algebraMap F (RatFunc F) (v i j)
  let ER : Coord → RatFunc F := fun i =>
    algebraMap F[X] (RatFunc F) (E i)
  have hminor : ∀ x : Option J → Coord,
      ((globalCorrectionAugmentedMatrix6401 vR ER).submatrix
        x _root_.id).det = 0 := by
    intro x
    have hmapped := congrArg (algebraMap F[X] (RatFunc F)) (hall x)
    rw [map_zero] at hmapped
    rw [← hmapped]
    rw [RingHom.map_det]
    congr 1
    ext i o
    cases o <;>
      simp [globalCorrectionAugmentedMatrix6401,
        correctionAugmentedMatrix6401, vR, ER]
  exact errorColumn_mem_span_of_all_rowMinors_zero6401
    vR ER hv hminor

/-! ## A degree-four correction curve has residual dimension at most three -/

/-- Once a global correction curve has degree at most four, its residuals
after removing the constant and linear coefficient lie in the span of the
three nonlinear coefficient polynomials.  This is the strongest automatic
dimension drop; it does not say those three generators are proportional. -/
theorem degreeFourCurve_residualSpan_le_threeGenerators6401
    {F : Type*} [Field F]
    (S : Finset F) (P : F → F[X])
    (P0 P1 P2 P3 P4 : F[X])
    (hcurve : ∀ z ∈ S,
      P z = P0 + Polynomial.C z * P1 +
        Polynomial.C (z ^ 2) * P2 +
        Polynomial.C (z ^ 3) * P3 +
        Polynomial.C (z ^ 4) * P4) :
    globalAffineResidualSpan6401 S P P0 P1 ≤
      Submodule.span F ({P2, P3, P4} : Set F[X]) := by
  rw [globalAffineResidualSpan6401, Submodule.span_le]
  rintro Q ⟨z, rfl⟩
  change globalAffineResidual6401 P P0 P1 z.1 ∈
    Submodule.span F ({P2, P3, P4} : Set F[X])
  unfold globalAffineResidual6401
  rw [hcurve z.1 z.2]
  have hP2 : P2 ∈ Submodule.span F ({P2, P3, P4} : Set F[X]) :=
    Submodule.subset_span (by simp)
  have hP3 : P3 ∈ Submodule.span F ({P2, P3, P4} : Set F[X]) :=
    Submodule.subset_span (by simp)
  have hP4 : P4 ∈ Submodule.span F ({P2, P3, P4} : Set F[X]) :=
    Submodule.subset_span (by simp)
  have hsum : Polynomial.C (z.1 ^ 2) * P2 +
        Polynomial.C (z.1 ^ 3) * P3 +
        Polynomial.C (z.1 ^ 4) * P4 ∈
      Submodule.span F ({P2, P3, P4} : Set F[X]) := by
    simpa only [smul_eq_C_mul] using
      (Submodule.add_mem _
        (Submodule.add_mem _
          (Submodule.smul_mem _ (z.1 ^ 2) hP2)
          (Submodule.smul_mem _ (z.1 ^ 3) hP3))
        (Submodule.smul_mem _ (z.1 ^ 4) hP4))
  convert hsum using 1 <;> ring

/-- If one degree-four global correction curve contains the entire retained
high-mass owner family, the existing residual-normal incidence theorem closes
it immediately: no-curve failure would force residual dimension at least
`22`, while the preceding theorem bounds it by `3`.

This statement is deliberately scoped to one *global* curve covering `S`.
Universal determinant vanishing for unrelated local correction components
does not supply that routing premise. -/
theorem curveWitness_of_globalDegreeFourCorrection_highMass6401
    {F I : Type*} [Field F] [DecidableEq F] [DecidableEq I]
    (alpha : I ↪ F) (u0 u1 : I → F)
    (Uset : Finset I) (S : Finset F) (A : F → Finset I)
    (P : F → F[X]) (P0 P1 P2 P3 P4 : F[X])
    (hUcard : Uset.card =
      BCHKSMultiPinRankAccumulation6401.multiPinAmbient6401)
    (hScard : BCHKSMultiPinRankAccumulation6401.multiPinOwnerMass6401 ≤
      S.card)
    (hsub : ∀ z ∈ S, A z ⊆ Uset)
    (hrow : ∀ z ∈ S,
      BCHKSMultiPinRankAccumulation6401.multiPinRow6401 ≤ (A z).card)
    (hPdegree : ∀ z ∈ S,
      (P z).natDegree ≤ residualPolynomialDegreeCap6401)
    (hP0degree : P0.natDegree ≤ residualPolynomialDegreeCap6401)
    (hP1degree : P1.natDegree ≤ residualPolynomialDegreeCap6401)
    (hagree : ∀ z ∈ S, ∀ i ∈ A z,
      (P z).eval (alpha i) = u0 i + z * u1 i)
    (hcurve : ∀ z ∈ S,
      P z = P0 + Polynomial.C z * P1 +
        Polynomial.C (z ^ 2) * P2 +
        Polynomial.C (z ^ 3) * P3 +
        Polynomial.C (z ^ 4) * P4) :
    BCHKSTwoFrobeniusWeakCurveSeed6401.PolynomialAffineCurveWitness6401 S P := by
  classical
  by_contra hfail
  let W := globalAffineResidualSpan6401 S P P0 P1
  have hlarge : 22 ≤ Module.finrank F W := by
    exact residualSpan_finrank_ge_22_of_noCurve6401
      alpha u0 u1 Uset S A P P0 P1 hUcard hScard hsub hrow
      hPdegree hP0degree hP1degree hagree hfail
  let generators : Finset F[X] := {P2, P3, P4}
  have hWle : W ≤ Submodule.span F (generators : Set F[X]) := by
    simpa [W, generators] using
      degreeFourCurve_residualSpan_le_threeGenerators6401
        S P P0 P1 P2 P3 P4 hcurve
  have hmono : Module.finrank F W ≤
      Module.finrank F (Submodule.span F (generators : Set F[X])) :=
    Submodule.finrank_mono hWle
  have hgen : Module.finrank F
      (Submodule.span F (generators : Set F[X])) ≤ generators.card := by
    exact finrank_span_finset_le_card generators
  have hcard : generators.card ≤ 3 := by
    dsimp [generators]
    calc
      ({P2, P3, P4} : Finset F[X]).card ≤
          ({P3, P4} : Finset F[X]).card + 1 :=
        Finset.card_insert_le P2 {P3, P4}
      _ ≤ (({P4} : Finset F[X]).card + 1) + 1 := by
        exact Nat.add_le_add_right (Finset.card_insert_le P3 {P4}) 1
      _ ≤ 3 := by simp
  omega

/-! ## Explicit nonscalar nonlinear correction profile -/

/-- A degree-three correction curve with two independent nonlinear
directions. -/
noncomputable def quadraticCubicCorrection6401 (z : ℚ) : ℚ[X] :=
  Polynomial.C (z ^ 2) + Polynomial.C (z ^ 3) * Polynomial.X

theorem quadraticCubicCorrection_values6401 :
    quadraticCubicCorrection6401 0 = 0 ∧
      quadraticCubicCorrection6401 1 = 1 + Polynomial.X ∧
      quadraticCubicCorrection6401 (-1) = 1 - Polynomial.X := by
  constructor
  · simp [quadraticCubicCorrection6401]
  constructor <;> simp [quadraticCubicCorrection6401] <;> ring

/-- The three displayed points of the quadratic/cubic curve do not lie in
one scalar polynomial chart.  Hence even a globally compatible bounded
correction curve need not be a clone or fixed scalar core. -/
theorem quadraticCubicCorrection_not_scalar6401 :
    ¬ ∃ Pbase G : ℚ[X], ∃ c : ℚ → ℚ,
      G ≠ 0 ∧
      ∀ z ∈ ({0, 1, -1} : Finset ℚ),
        quadraticCubicCorrection6401 z =
          Pbase + Polynomial.C (c z) * G := by
  rintro ⟨Pbase, G, c, _hG, hline⟩
  have h0 := hline 0 (by simp)
  have h1 := hline 1 (by simp)
  have hm := hline (-1) (by simp)
  rw [quadraticCubicCorrection_values6401.1] at h0
  rw [quadraticCubicCorrection_values6401.2.1] at h1
  rw [quadraticCubicCorrection_values6401.2.2] at hm
  have hA : 1 + Polynomial.X = Polynomial.C (c 1 - c 0) * G := by
    calc
      1 + Polynomial.X =
          (Pbase + Polynomial.C (c 1) * G) -
            (Pbase + Polynomial.C (c 0) * G) := by rw [← h1, ← h0]; ring
      _ = Polynomial.C (c 1 - c 0) * G := by
        rw [map_sub]
        ring
  have hB : 1 - Polynomial.X = Polynomial.C (c (-1) - c 0) * G := by
    calc
      1 - Polynomial.X =
          (Pbase + Polynomial.C (c (-1)) * G) -
            (Pbase + Polynomial.C (c 0) * G) := by rw [← hm, ← h0]; ring
      _ = Polynomial.C (c (-1) - c 0) * G := by
        rw [map_sub]
        ring
  have hA0 := congrArg (fun Q : ℚ[X] => Q.coeff 0) hA
  have hA1 := congrArg (fun Q : ℚ[X] => Q.coeff 1) hA
  have hB0 := congrArg (fun Q : ℚ[X] => Q.coeff 0) hB
  have hB1 := congrArg (fun Q : ℚ[X] => Q.coeff 1) hB
  simp only [Polynomial.coeff_add, Polynomial.coeff_sub,
    Polynomial.coeff_one, Polynomial.coeff_X,
    Polynomial.coeff_C_mul] at hA0
  simp only [Polynomial.coeff_add, Polynomial.coeff_sub,
    Polynomial.coeff_one, Polynomial.coeff_X,
    Polynomial.coeff_C_mul] at hA1
  simp only [Polynomial.coeff_add, Polynomial.coeff_sub,
    Polynomial.coeff_one, Polynomial.coeff_X,
    Polynomial.coeff_C_mul] at hB0
  simp only [Polynomial.coeff_add, Polynomial.coeff_sub,
    Polynomial.coeff_one, Polynomial.coeff_X,
    Polynomial.coeff_C_mul] at hB1
  norm_num at hA0 hA1 hB0 hB1
  nlinarith

end BCHKSNonproperAugmentedResidualAudit6401
end ProximityPrize.SubmissionLower
