import ProximityPrize.SubmissionLower.ContactDelayedTailMultiplicityProvider6732Research
import ProximityPrize.SubmissionLower.ContactTwoTailParameters6733Research
import ProximityPrize.SubmissionLower.ContactRobustFixedMeet6656Research
import ProximityPrize.SubmissionLower.ContactMovingAgreementCertificate6719Research
namespace ProximityPrize.SubmissionLower.ContactTwoTailFixedProvider6732Research
open ContactResidualSupportParametersResearch
noncomputable section
def fixedProfile:ContactRobustFixedMeet6656Research.Profile:=
  ⟨262144,131071,182052,7464132,1242,11⟩
def fixedSupport:ResidualSupportParameters:=
  ContactMovingAgreementCertificate6719Research.support 1186 44 9
end
end ProximityPrize.SubmissionLower.ContactTwoTailFixedProvider6732Research
