import ProximityPrize.SubmissionLower.ContactProperStageActiveFixedPowers6733Research
import ProximityPrize.SubmissionLower.ContactTwoTailClosure6733Research
namespace ProximityPrize.SubmissionLower.ContactTwoTailUnconditional6733Research
open ProximityPrize.Benchmark
open ContactTwoTailFixedSelected6733Research
open ContactProperStageActiveProvider6733Research
open ContactProperStageActiveFixedPowers6733Research
noncomputable section
set_option autoImplicit false
set_option maxHeartbeats 1000000
theorem properStageProvider6733:ProperStageProvider6733:=
  properStageProvider6733_of_activeFixedPowers activeStageFixedPowerProvider6733
theorem protocolClaim6733:ProtocolClaim 6733 10251903 33554432:=
  ContactTwoTailClosure6733Research.protocolClaim6733_of_proper properStageProvider6733
end
end ProximityPrize.SubmissionLower.ContactTwoTailUnconditional6733Research
