import ProximityPrize.Benchmark.TargetLower
import ProximityPrize.SubmissionLower.ContactGlobalAdaptiveAlignment6600Research
import ProximityPrize.SubmissionLower.ContactProtocol6600ConditionalResearch

namespace ProximityPrize.SubmissionLower.ContactProtocol6600AdaptiveResearch

open ProximityPrize.Benchmark
open ContactGlobalAdaptiveAlignment6600Research

set_option maxHeartbeats 3000000
set_option maxRecDepth 35000

theorem protocolClaim6600_of_terminal_projection_families
    (hprojection : FrozenTerminalAdaptiveProjectionFamilies6600) :
    ProtocolClaim 6619 315871 1048576 := by
  apply ContactProtocol6600ConditionalResearch.protocolClaim6600_of_global_count_lt_alignment
  exact global_count_lt_alignment6600_of_terminal_projection_families hprojection

end ProximityPrize.SubmissionLower.ContactProtocol6600AdaptiveResearch
