import ProximityPrize.Benchmark.TargetLower
import ProximityPrize.SubmissionLower.LocalMathlib_FieldTheory_RatFunc_Valuation
import ProximityPrize.SubmissionLower.LocalMathlib_RingTheory_Valuation_Discrete_IsDiscreteValuationRing

/-!
# The actual infinity DVR and its normalized adic valuation

Model label: gpt-5.

Construct the valuation ring of RatFunc.inftyValuation itself. This ring
has K(T) as its actual fraction field and is a DVR. Its actual maximal
ideal is generated by 1/T, and its normalized adic valuation is proved
equal to RatFunc.inftyValuation on every element of K(T).

No inverse-coordinate copy of an extension field, or assumed chart
identification, is used. Normalization inside a fixed finite separable
extension and the global norm summation are subsequent steps.
-/

namespace ProximityPrize.SubmissionLower.InfinityValuationRing

open scoped Classical

noncomputable section

variable (K : Type*) [Field K]

local instance : DecidableEq K := Classical.decEq K

/-- The actual unit ball of the valuation at infinity. -/
abbrev InfinityRing := (RatFunc.inftyValuation K).valuationSubring

instance infinity_isRankOneDiscrete :
    Valuation.IsRankOneDiscrete (RatFunc.inftyValuation K) := inferInstance

instance infinityRing_isDiscreteValuationRing :
    IsDiscreteValuationRing (InfinityRing K) := inferInstance

theorem infinityRing_isFractionRing :
    IsFractionRing (InfinityRing K) (RatFunc K) := inferInstance

/-- The actual inverse parameter, proved to belong to the infinity ring. -/
def infinityUniformizer : InfinityRing K := by
  refine ⟨(RatFunc.X : RatFunc K)⁻¹, ?_⟩
  change RatFunc.inftyValuation K (RatFunc.X : RatFunc K)⁻¹ ≤ 1
  rw [show RatFunc.inftyValuation K (RatFunc.X : RatFunc K)⁻¹ =
      WithZero.exp (-1 : ℤ) by
    simpa only [one_div] using RatFunc.inftyValuation.X_inv K]
  rw [← WithZero.exp_zero, WithZero.exp_le_exp]
  norm_num

theorem infinityUniformizer_value :
    RatFunc.inftyValuation K
      (algebraMap (InfinityRing K) (RatFunc K) (infinityUniformizer K)) =
      WithZero.exp (-1 : ℤ) := by
  change RatFunc.inftyValuation K (RatFunc.X : RatFunc K)⁻¹ = _
  simpa only [one_div] using RatFunc.inftyValuation.X_inv K

theorem infinityUniformizer_isUniformizer :
    (RatFunc.inftyValuation K).IsUniformizer
      (algebraMap (InfinityRing K) (RatFunc K) (infinityUniformizer K)) := by
  unfold Valuation.IsUniformizer
  rw [Valuation.IsRankOneDiscrete.generator_eq_exp_neg_one_of_mem_range
    (v := RatFunc.inftyValuation K)
    ⟨algebraMap (InfinityRing K) (RatFunc K) (infinityUniformizer K),
      infinityUniformizer_value K⟩]
  exact infinityUniformizer_value K

theorem infinityUniformizer_ne_zero : infinityUniformizer K ≠ 0 := by
  intro hzero
  have h := (infinityUniformizer_isUniformizer K).ne_zero
  exact h (by rw [hzero, map_zero])

theorem infinity_maximalIdeal_eq_span :
    (IsDiscreteValuationRing.maximalIdeal (InfinityRing K)).asIdeal =
      Ideal.span {infinityUniformizer K} :=
  (infinityUniformizer_isUniformizer K).is_generator

theorem infinityUniformizer_irreducible : Irreducible (infinityUniformizer K) :=
  (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr
    (infinity_maximalIdeal_eq_span K)

/-- The valuation-ring adic valuation agrees with the original infinity
valuation on every integral element, with exact normalization. -/
theorem infinity_intValuation_eq (x : InfinityRing K) :
    (IsDiscreteValuationRing.maximalIdeal (InfinityRing K)).intValuation x =
      RatFunc.inftyValuation K (algebraMap (InfinityRing K) (RatFunc K) x) := by
  by_cases hx : x = 0
  · simp [hx]
  obtain ⟨n, u, rfl⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible
    hx (infinityUniformizer_irreducible K)
  have hunit :
      (IsDiscreteValuationRing.maximalIdeal (InfinityRing K)).intValuation
        (u : InfinityRing K) = 1 := by
    simp [IsDiscreteValuationRing.maximalIdeal]
  have hunit' :
      RatFunc.inftyValuation K
        (algebraMap (InfinityRing K) (RatFunc K) (u : InfinityRing K)) = 1 :=
    Valuation.Integers.one_of_isUnit
      (Valuation.valuationSubring.integers (RatFunc.inftyValuation K)) u.isUnit
  have hparameter :
      (IsDiscreteValuationRing.maximalIdeal (InfinityRing K)).intValuation
        (infinityUniformizer K) = WithZero.exp (-1 : ℤ) :=
    (IsDiscreteValuationRing.maximalIdeal (InfinityRing K)).intValuation_singleton
      (infinityUniformizer_ne_zero K) (infinity_maximalIdeal_eq_span K)
  simp only [map_mul, map_pow, hunit, hunit', hparameter,
    infinityUniformizer_value, one_mul]

/-- Exact equality on the actual common fraction field K(T), not merely
equivalence or an unspecified rescaling of the two valuations. -/
theorem infinity_valuation_eq (x : RatFunc K) :
    (IsDiscreteValuationRing.maximalIdeal (InfinityRing K)).valuation (RatFunc K) x =
      RatFunc.inftyValuation K x := by
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := InfinityRing K) x
  simp only [map_div₀,
    IsDedekindDomain.HeightOneSpectrum.valuation_of_algebraMap,
    infinity_intValuation_eq]

end

end ProximityPrize.SubmissionLower.InfinityValuationRing
