import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR05Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData17
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData18

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR17Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData17.prefixData
    LocatorPhase6800ReceiptRowData18.prefixData 17 110 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR17Checked
