import ProximityPrize.SubmissionLower.LocatorReplacementGridRow14
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_15_band_00_y_00 : RowBandReceipt 15 0 1 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
