import ProximityPrize.SubmissionLower.LocatorReplacementGridRow09Band02T01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_09_band_02_t_02 : RowTileReceipt 9 4 5 6 14 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
