import ProximityPrize.SubmissionLower.LocatorReplacementGridRow04Band00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_04_band_01_y_00 : RowBandReceipt 4 7 10 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
