import ProximityPrize.SubmissionLower.LocatorReplacementGridRow05Band02
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_05_band_03_y_00 : RowBandReceipt 5 9 10 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
