import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR10Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData22
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData23

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR22Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData22.prefixData
    LocatorPhase6800ReceiptRowData23.prefixData 22 105 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR22Checked
