import ProximityPrize.SubmissionLower.LocatorReplacementGridRow10Band02
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_10_band_03_t_00 : RowTileReceipt 10 5 6 0 11 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
