import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR20Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData04
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData05

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR04Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData04.prefixData
    LocatorPhase6800ReceiptRowData05.prefixData 4 123 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR04Checked
