import ProximityPrize.SubmissionLower.LocatorReplacementGridRow14Band00Y01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_14_band_00_y_02 : RowBandReceipt 14 2 3 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
