import ProximityPrize.SubmissionLower.LocatorReplacementGridRow04Band01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_04_band_02_y_00_z_00 : RowBandReceipt 4 14 16 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
