import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR22Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData06
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData07

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR06Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData06.prefixData
    LocatorPhase6800ReceiptRowData07.prefixData 6 121 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR06Checked
