import ProximityPrize.SubmissionLower.LocatorReplacementGridRow05Band04Y00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_05_band_04_y_01 : RowBandReceipt 5 13 14 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
