import ProximityPrize.SubmissionLower.LocatorReplacementGridRow06Band06T00T02
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_06_band_06_t_00_t_03 : RowTileReceipt 6 8 9 3 4 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
