import ProximityPrize.SubmissionLower.LocatorReplacementGridRow07Band05T04
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_07_band_05_t_05_t_00_t_00 : RowTileReceipt 7 7 8 5 6 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
