import ProximityPrize.SubmissionLower.LocatorReplacementGridRow14Band00Y00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_14_band_00_y_01 : RowBandReceipt 14 1 2 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
