import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR03Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData15
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData16

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR15Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData15.prefixData
    LocatorPhase6800ReceiptRowData16.prefixData 15 112 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR15Checked
