import ProximityPrize.SubmissionLower.LocatorReplacementGridRow14Band01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_14_band_02_t_00 : RowTileReceipt 14 4 5 0 11 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
