import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR17Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData01
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData02

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR01Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData01.prefixData
    LocatorPhase6800ReceiptRowData02.prefixData 1 126 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR01Checked
