import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR27Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData11
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData12

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR11Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData11.prefixData
    LocatorPhase6800ReceiptRowData12.prefixData 11 116 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR11Checked
