import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR11Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData23
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData24

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR23Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData23.prefixData
    LocatorPhase6800ReceiptRowData24.prefixData 23 104 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR23Checked
