import ProximityPrize.SubmissionLower.LocatorReplacementGridRow16Band00Y01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_16_band_00_y_02 : RowBandReceipt 16 2 3 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
