import ProximityPrize.SubmissionLower.LocatorReplacementGridRow10Band05T00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_10_band_05_t_01 : RowTileReceipt 10 7 8 11 22 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
