import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR14Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData26
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData27

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR26Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData26.prefixData
    LocatorPhase6800ReceiptRowData27.prefixData 26 101 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR26Checked
