import ProximityPrize.SubmissionLower.LocatorReplacementGridRow03Band01

namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_03_band_02 : RowBandReceipt 3 14 21 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
