import ProximityPrize.SubmissionLower.LocatorReplacementGridRow13Band00Y00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_13_band_00_y_01 : RowBandReceipt 13 1 2 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
