import ProximityPrize.SubmissionLower.LocatorReplacementGridRow12Band00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_12_band_01_t_00 : RowTileReceipt 12 3 4 0 11 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
