import ProximityPrize.SubmissionLower.LocatorReplacementGridRow04Band01Y01Z00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_04_band_01_y_01_z_01 : RowBandReceipt 4 11 12 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
