import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR07Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData19
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData20

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR19Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData19.prefixData
    LocatorPhase6800ReceiptRowData20.prefixData 19 108 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR19Checked
