import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR21Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData05
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData06

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR05Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData05.prefixData
    LocatorPhase6800ReceiptRowData06.prefixData 5 122 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR05Checked
