import ProximityPrize.SubmissionLower.LocatorReplacementGridBarrierP2
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_13_band_00_y_00 : RowBandReceipt 13 0 1 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
