import ProximityPrize.SubmissionLower.LocatorReplacementGridRow08Band04
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_08_band_05_t_00 : RowTileReceipt 8 7 8 0 11 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
