import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR28Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData12
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData13

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR12Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData12.prefixData
    LocatorPhase6800ReceiptRowData13.prefixData 12 115 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR12Checked
