import ProximityPrize.SubmissionLower.LocatorReplacementGridRow05Hot00Single03

namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData

set_option maxRecDepth 100000
set_option maxHeartbeats 30000000

end ProximityPrize.SubmissionLower.LocatorReplacementGridData
