import ProximityPrize.SubmissionLower.LocatorReplacementGridRow09Band01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_09_band_02_t_00 : RowTileReceipt 9 4 5 0 1 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
