import ProximityPrize.SubmissionLower.LocatorReplacementGridRow09Band02T02
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_09_band_02_t_03 : RowTileReceipt 9 4 5 14 22 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
