import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR04Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData16
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData17

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR16Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData16.prefixData
    LocatorPhase6800ReceiptRowData17.prefixData 16 111 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR16Checked
