import ProximityPrize.SubmissionLower.LocatorReplacementGridRow13Band00Y01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_13_band_00_y_02_t_00 : RowTileReceipt 13 2 3 0 11 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
