import ProximityPrize.SubmissionLower.LocatorReplacementGridRow05Band03Y01
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_05_band_03_y_02 : RowBandReceipt 5 11 12 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
