import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR18Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData02
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData03

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR02Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData02.prefixData
    LocatorPhase6800ReceiptRowData03.prefixData 2 125 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR02Checked
