import ProximityPrize.SubmissionLower.LocatorPhase6800ThresholdR24Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData08
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData09

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR08Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData08.prefixData
    LocatorPhase6800ReceiptRowData09.prefixData 8 119 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR08Checked
