import ProximityPrize.SubmissionLower.LocatorReplacementGridRow06Hot00Part02

namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData

set_option maxRecDepth 100000
set_option maxHeartbeats 30000000

end ProximityPrize.SubmissionLower.LocatorReplacementGridData
