import ProximityPrize.SubmissionLower.LocatorReplacementGridRow06Band05
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_06_band_06_t_00_t_00 : RowTileReceipt 6 8 9 0 1 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
