import ProximityPrize.SubmissionLower.LocatorTwoFactorAvoidance
import ProximityPrize.SubmissionLower.BI
import ProximityPrize.SubmissionLower.LocatorHybridCost

/-!
# Collision-free extraction from a batch of regular factors

Let `A` be a finite set of distinct regular factors and let `P` be their
product.  Suppose a shared power route has reached a quotient family `q` at
depth `j`, so an original row has the form `P^j * q v`.  At the first stage
where not every factor divides every value of `q`, the nonuniversal
divisibility conditions are proper submodules.  A finite-union argument
chooses one `v` avoiding all of them simultaneously.

For `F ∈ A` put `G_F = ∏ (A.erase F)` and retain the cofactor in the
helper:

`Q_F = G_F^j * q v`.

Then `P^j * q v = F^j * Q_F`.  Consequently the order-`j` derivative
extraction makes `Q_F` vanish on every `F`-regular seed, including seeds at
which another factor vanishes.  There is no internal-collision error term or
collision charge.  Pairwise coprimality also gives `IsRelPrime F Q_F`, and
the cofactor exactly restores all residual weight lost to the other factors.
-/

namespace ProximityPrize.SubmissionLower.LocatorBatchProductRoute

open scoped BigOperators
open UniqueFactorizationMonoid
open RCN081 RCN100 RCN119 RCN130 RCN140 RCN156 RCN180 RCN234 RCN260
open LocatorLowQuotient LocatorCoprimeQuotient
  LocatorArbitraryPowerAvoidance LocatorArbitraryPowerContact
  LocatorTwoFactorAvoidance

noncomputable section

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 5000000

variable {K V : Type} [Field K]
local instance : DecidableEq K := Classical.decEq K
local instance : StrongNormalizationMonoid (MvPolynomial (Fin 4) K) :=
  UniqueFactorizationMonoid.strongNormalizationMonoid

abbrev P4 (K : Type) [Field K] := MvPolynomial (Fin 4) K

/-! ## Divisibility subspaces and simultaneous avoidance -/

/-- The preimage under a linear polynomial family of the principal ideal
generated by `F`. -/
def dvdSubmodule [AddCommGroup V] [Module K V]
    (q : V →ₗ[K] P4 K) (F : P4 K) : Submodule K V where
  carrier := {v | F ∣ q v}
  zero_mem' := by simp
  add_mem' := by
    intro x y hx hy
    change F ∣ q x at hx
    change F ∣ q y at hy
    change F ∣ q (x + y)
    rw [map_add]
    exact dvd_add hx hy
  smul_mem' := by
    intro a x hx
    change F ∣ q x at hx
    change F ∣ q (a • x)
    rw [map_smul, MvPolynomial.smul_eq_C_mul]
    exact dvd_mul_of_dvd_right hx _

@[simp] theorem mem_dvdSubmodule [AddCommGroup V] [Module K V]
    (q : V →ₗ[K] P4 K) (F : P4 K) (v : V) :
    v ∈ dvdSubmodule q F ↔ F ∣ q v := Iff.rfl

theorem dvdSubmodule_ne_top_of_not_universal
    [AddCommGroup V] [Module K V]
    (q : V →ₗ[K] P4 K) (F : P4 K)
    (h : ¬ ∀ v, F ∣ q v) :
    dvdSubmodule q F ≠ ⊤ := by
  intro htop
  apply h
  intro v
  have hv : v ∈ dvdSubmodule q F := by rw [htop]; trivial
  exact hv

/-- A field with more elements than the number of nonuniversal factors
contains one vector avoiding every corresponding divisibility subspace.
The vector is automatically nonzero when the factor set is nonempty. -/
theorem exists_avoiding_nonuniversal_factors
    [AddCommGroup V] [Module K V]
    {A : Type} [DecidableEq A] (s : Finset A) (hs : s.Nonempty)
    (q : V →ₗ[K] P4 K) (factor : A → P4 K)
    (hnonuniversal : ∀ a ∈ s, ¬ ∀ v, factor a ∣ q v)
    (hcard : s.card < ENat.card K) :
    ∃ v, v ≠ 0 ∧ ∀ a ∈ s, ¬ factor a ∣ q v := by
  classical
  let bad : s → Submodule K V := fun a => dvdSubmodule q (factor a.1)
  have hproper : ∀ a : s, bad a ≠ ⊤ := by
    intro a
    exact dvdSubmodule_ne_top_of_not_universal q (factor a.1)
      (hnonuniversal a.1 a.2)
  have hsmall : (Finset.univ : Finset s).card < ENat.card K := by
    simpa using hcard
  have hss := RCN133.finite_iUnion_ssubset
    (Finset.univ : Finset s) bad hproper hsmall
  obtain ⟨v, hv⟩ := Set.ssubset_univ_iff_nonempty_compl.mp hss
  have havoid : ∀ a : s, v ∉ bad a := by
    intro a hmem
    apply hv
    simp only [Set.mem_iUnion, Finset.mem_univ, true_and]
    exact ⟨a, trivial, hmem⟩
  have hv0 : v ≠ 0 := by
    intro hz
    obtain ⟨a, ha⟩ := hs
    have hnot := havoid ⟨a, ha⟩
    apply hnot
    subst v
    change factor a ∣ q 0
    simp
  refine ⟨v, hv0, ?_⟩
  intro a ha
  simpa only [bad, mem_dvdSubmodule] using havoid ⟨a, ha⟩

/-! ## Products of distinct regular factors -/

/-- The squarefree product represented by a finite set of regular indices. -/
def regularProduct (H : P4 K) (A : Finset (RCN266.RegularIndex H)) : P4 K :=
  ∏ F ∈ A, F.1

/-- The complementary product after removing one regular index. -/
def regularCofactor (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) : P4 K :=
  ∏ G ∈ A.erase F, G.1

theorem regularFactor_ne_zero (H : P4 K) (F : RCN266.RegularIndex H) :
    F.1 ≠ 0 :=
  (RCN167.positiveRFactors_spec H F.1 F.2).1.ne_zero

theorem regularProduct_ne_zero (H : P4 K)
    (A : Finset (RCN266.RegularIndex H)) : regularProduct H A ≠ 0 := by
  classical
  unfold regularProduct
  apply Finset.prod_ne_zero_iff.mpr
  intro F hF
  exact regularFactor_ne_zero H F

theorem regularCofactor_ne_zero (H : P4 K)
    (A : Finset (RCN266.RegularIndex H)) (F : RCN266.RegularIndex H) :
    regularCofactor H A F ≠ 0 := by
  classical
  unfold regularCofactor
  apply Finset.prod_ne_zero_iff.mpr
  intro G hG
  exact regularFactor_ne_zero H G

/-- Exact factor/cofactor decomposition of the batch product. -/
theorem regularFactor_mul_cofactor
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A) :
    F.1 * regularCofactor H A F = regularProduct H A := by
  classical
  simpa only [regularProduct, regularCofactor] using
    Finset.mul_prod_erase A (fun G => G.1) hFA

/-- A regular factor is coprime to the product of all the other regular
factors in the same finite set. -/
theorem regularFactor_isRelPrime_cofactor
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A) :
    IsRelPrime F.1 (regularCofactor H A F) := by
  classical
  unfold regularCofactor
  apply IsRelPrime.prod_right
  intro G hG
  have hGe := Finset.mem_erase.mp hG
  apply regularIndex_isRelPrime_of_ne H F G
  intro heq
  apply hGe.1
  exact Subtype.ext heq.symm

/-- Splitting a batch power around one selected factor. -/
theorem regularProduct_power_split
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A)
    (j : ℕ) (J : P4 K) :
    regularProduct H A ^ j * J =
      F.1 ^ j * (regularCofactor H A F ^ j * J) := by
  rw [← regularFactor_mul_cofactor H A F hFA, mul_pow]
  ring

/-- Avoiding `F` in the common residual witness makes the cofactor-retaining
helper coprime to `F`. -/
theorem regularFactor_isRelPrime_liftedHelper
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A)
    (j : ℕ) (J : P4 K) (hnot : ¬ F.1 ∣ J) :
    IsRelPrime F.1 (regularCofactor H A F ^ j * J) := by
  have hFirred := (RCN167.positiveRFactors_spec H F.1 F.2).1
  apply hFirred.isRelPrime_iff_not_dvd.mpr
  intro hd
  apply hnot
  exact ((regularFactor_isRelPrime_cofactor H A F hFA).pow_right)
    |>.dvd_of_dvd_mul_left hd

/-! ## Exact restoration of residual weights -/

/-- Multiplying the common residual witness by the complementary product
restores precisely the weight spent on all factors other than `F`. -/
theorem cofactor_power_mul_weight_le_sub
    (weights : Fin 4 → ℕ) (B j : ℕ) (F C J : P4 K)
    (hF : F ≠ 0) (hC : C ≠ 0) (hJ : J ≠ 0)
    (hfeasible : j * wt weights (F * C) ≤ B)
    (hbound : wt weights J ≤ B - j * wt weights (F * C)) :
    wt weights (C ^ j * J) ≤ B - j * wt weights F := by
  have hFC := weightedTotalDegree_mul weights F C hF hC
  have hCJ := weightedTotalDegree_mul weights (C ^ j) J
    (pow_ne_zero j hC) hJ
  have hCp := wt_pow_eq weights C hC j
  unfold wt at hfeasible hbound hFC hCJ hCp ⊢
  rw [hFC, Nat.mul_add] at hfeasible hbound
  rw [hCp] at hCJ
  rw [hCJ]
  let f := MvPolynomial.weightedTotalDegree weights F
  let c := MvPolynomial.weightedTotalDegree weights C
  let x := MvPolynomial.weightedTotalDegree weights J
  change j * f + j * c ≤ B at hfeasible
  change x ≤ B - (j * f + j * c) at hbound
  change j * c + x ≤ B - j * f
  have htotal : j * f + (j * c + x) ≤ B := by
    calc
      j * f + (j * c + x) = (j * f + j * c) + x := by omega
      _ ≤ (j * f + j * c) + (B - (j * f + j * c)) :=
        Nat.add_le_add_left hbound _
      _ = B := Nat.add_sub_of_le hfeasible
  have htotal' : (j * c + x) + j * f ≤ B := by
    simpa only [Nat.add_comm] using htotal
  exact Nat.le_sub_of_add_le htotal'

/-- The three residual bounds for every lifted helper. -/
theorem liftedHelper_residual_bounds
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A)
    (T YS S j : ℕ) (J : P4 K) (hJ : J ≠ 0)
    (hT : wt residualTotalWeights J ≤
      T - j * wt residualTotalWeights (regularProduct H A))
    (hY : wt residualYSWeights J ≤
      YS - j * wt residualYSWeights (regularProduct H A))
    (hS : wt residualSWeights J ≤
      S - j * wt residualSWeights (regularProduct H A))
    (hTfeasible : j * wt residualTotalWeights (regularProduct H A) ≤ T)
    (hYfeasible : j * wt residualYSWeights (regularProduct H A) ≤ YS)
    (hSfeasible : j * wt residualSWeights (regularProduct H A) ≤ S) :
    wt residualTotalWeights (regularCofactor H A F ^ j * J) ≤
        T - j * wt residualTotalWeights F.1 ∧
      wt residualYSWeights (regularCofactor H A F ^ j * J) ≤
        YS - j * wt residualYSWeights F.1 ∧
      wt residualSWeights (regularCofactor H A F ^ j * J) ≤
        S - j * wt residualSWeights F.1 := by
  have hfactor := regularFactor_mul_cofactor H A F hFA
  have hF0 := regularFactor_ne_zero H F
  have hC0 := regularCofactor_ne_zero H A F
  rw [← hfactor] at hT hY hS hTfeasible hYfeasible hSfeasible
  exact ⟨
    cofactor_power_mul_weight_le_sub residualTotalWeights T j F.1
      (regularCofactor H A F) J hF0 hC0 hJ hTfeasible hT,
    cofactor_power_mul_weight_le_sub residualYSWeights YS j F.1
      (regularCofactor H A F) J hF0 hC0 hJ hYfeasible hY,
    cofactor_power_mul_weight_le_sub residualSWeights S j F.1
      (regularCofactor H A F) J hF0 hC0 hJ hSfeasible hS⟩

/-! ## One common witness and all collision-free helpers -/

/-- At a nonuniversal batch stage, one vector gives coprime helpers for every
nonuniversal factor, with the sharp per-factor residual caps.

Crucially, `hnonuniversal` concerns the displayed current family `q`.  It must
be established again after every high-band projection; nonuniversality on an
earlier ambient family does not survive restriction to a kernel. -/
theorem exists_collisionFree_batch_helpers
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A N : Finset (RCN266.RegularIndex H))
    (hNA : N ⊆ A) (hN : N.Nonempty)
    (q : V →ₗ[K] P4 K) (hq : Function.Injective q)
    (j Dq w T YS S : ℕ)
    (hbox : ∀ v, q v ∈ nestedCoefficientBox K Dq w
      (T - j * wt residualTotalWeights (regularProduct H A))
      (YS - j * wt residualYSWeights (regularProduct H A))
      (S - j * wt residualSWeights (regularProduct H A)))
    (hfeasible :
      j * wt residualTotalWeights (regularProduct H A) ≤ T ∧
      j * wt residualYSWeights (regularProduct H A) ≤ YS ∧
      j * wt residualSWeights (regularProduct H A) ≤ S)
    (hnonuniversal : ∀ F ∈ N, ¬ ∀ v, F.1 ∣ q v)
    (hcard : N.card < ENat.card K) :
    ∃ (v : V) (J : P4 K),
      v ≠ 0 ∧ J = q v ∧ J ≠ 0 ∧
      ∀ F ∈ N,
        let QF := regularCofactor H A F ^ j * J
        QF ≠ 0 ∧ IsRelPrime F.1 QF ∧
          regularProduct H A ^ j * J = F.1 ^ j * QF ∧
          wt residualTotalWeights QF ≤
            T - j * wt residualTotalWeights F.1 ∧
          wt residualYSWeights QF ≤
            YS - j * wt residualYSWeights F.1 ∧
          wt residualSWeights QF ≤
            S - j * wt residualSWeights F.1 := by
  classical
  obtain ⟨v, hv, havoid⟩ := exists_avoiding_nonuniversal_factors
    N hN q (fun F => F.1) hnonuniversal hcard
  let J := q v
  have hJ : J ≠ 0 := by
    intro hz
    apply hv
    apply hq
    simpa only [J, map_zero] using hz
  have hweights := nested_mem_weights (hbox v) hJ
  refine ⟨v, J, hv, rfl, hJ, ?_⟩
  intro F hFN
  have hFA := hNA hFN
  let QF := regularCofactor H A F ^ j * J
  have hQF : QF ≠ 0 :=
    mul_ne_zero (pow_ne_zero j (regularCofactor_ne_zero H A F)) hJ
  have hrel : IsRelPrime F.1 QF := by
    exact regularFactor_isRelPrime_liftedHelper H A F hFA j J
      (havoid F hFN)
  have heq := regularProduct_power_split H A F hFA j J
  have hb := liftedHelper_residual_bounds H A F hFA T YS S j J hJ
    hweights.1 hweights.2.1 hweights.2.2.1
    hfeasible.1 hfeasible.2.1 hfeasible.2.2
  exact ⟨hQF, hrel, heq, hb⟩

/-! ## The current post-projection split -/

/-- Factors whose divisibility subspace is the whole *current* domain. -/
noncomputable def universalFactors
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) : Finset (RCN266.RegularIndex H) := by
  classical
  exact A.filter fun F => ∀ v, F.1 ∣ q v

@[simp] theorem mem_universalFactors
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) (F : RCN266.RegularIndex H) :
    F ∈ universalFactors H A q ↔ F ∈ A ∧ ∀ v, F.1 ∣ q v := by
  classical
  simp only [universalFactors, Finset.mem_filter]

theorem universalFactors_subset
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) : universalFactors H A q ⊆ A := by
  intro F hF
  exact (mem_universalFactors H A q F).mp hF |>.1

/-- Individual universal divisibility combines to divisibility by the entire
squarefree regular product. -/
theorem regularProduct_dvd_of_each
    (H : P4 K) (A : Finset (RCN266.RegularIndex H)) (Q : P4 K)
    (hdiv : ∀ F ∈ A, F.1 ∣ Q) : regularProduct H A ∣ Q := by
  classical
  induction A using Finset.induction_on with
  | empty => simp only [regularProduct, Finset.notMem_empty,
      Finset.prod_empty, one_dvd]
  | @insert F A hFA ih =>
      have hFdiv : F.1 ∣ Q := hdiv F (Finset.mem_insert_self F A)
      have hAdiv : regularProduct H A ∣ Q := by
        apply ih
        intro G hGA
        exact hdiv G (Finset.mem_insert_of_mem hGA)
      have hrel : IsRelPrime F.1 (regularProduct H A) := by
        unfold regularProduct
        apply IsRelPrime.prod_right
        intro G hGA
        apply regularIndex_isRelPrime_of_ne H F G
        intro heq
        apply hFA
        have hFG : F = G := Subtype.ext heq
        rwa [hFG]
      have hprod : regularProduct H (insert F A) =
          F.1 * regularProduct H A := by
        simp only [regularProduct, Finset.prod_insert hFA]
      rw [hprod]
      exact hrel.mul_dvd hFdiv hAdiv

/-- The squarefree product of any set of regular indices divides the
ambient carrier polynomial.  This is the bridge used after a universal
source split: the source controls the product's narrow coordinates, while
the selected carrier still controls its total coordinate. -/
theorem regularProduct_dvd_carrier
    (H : P4 K) (A : Finset (RCN266.RegularIndex H)) :
    regularProduct H A ∣ H := by
  apply regularProduct_dvd_of_each
  intro F _hFA
  exact (RCN167.positiveRFactors_spec H F.1 F.2).2.1

/-- The product of the current universal subset divides every value of the
current family. -/
theorem universalProduct_dvd
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) :
    ∀ v, regularProduct H (universalFactors H A q) ∣ q v := by
  intro v
  apply regularProduct_dvd_of_each
  intro F hF
  exact (mem_universalFactors H A q F).mp hF |>.2 v

/-- Packaged conclusion of `exists_collisionFree_batch_helpers`. -/
def HasCollisionFreeBatchHelpers
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A N : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) (j T YS S : ℕ) : Prop :=
  ∃ (v : V) (J : P4 K),
    v ≠ 0 ∧ J = q v ∧ J ≠ 0 ∧
    ∀ F ∈ N,
      let QF := regularCofactor H A F ^ j * J
      QF ≠ 0 ∧ IsRelPrime F.1 QF ∧
        regularProduct H A ^ j * J = F.1 ^ j * QF ∧
        wt residualTotalWeights QF ≤
          T - j * wt residualTotalWeights F.1 ∧
        wt residualYSWeights QF ≤
          YS - j * wt residualYSWeights F.1 ∧
        wt residualSWeights QF ≤
          S - j * wt residualSWeights F.1

/-- One explicit adapter from a current post-projection family to the U/N
case split used by the abstract phase recursion.

If every factor is universal, the first component supplies divisibility by
the whole product for the next shared quotient round.  Otherwise `U` is a
strict subset and one common witness supplies all helpers for `N = A \ U`.
The recursive child on `U` should normally be built from a fresh source; this
theorem intentionally does not claim that restricting or quotienting the
current family preserves nonuniversality. -/
theorem currentPostProjection_split
    [AddCommGroup V] [Module K V]
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) (hq : Function.Injective q)
    (j Dq w T YS S : ℕ)
    (hbox : ∀ v, q v ∈ nestedCoefficientBox K Dq w
      (T - j * wt residualTotalWeights (regularProduct H A))
      (YS - j * wt residualYSWeights (regularProduct H A))
      (S - j * wt residualSWeights (regularProduct H A)))
    (hfeasible :
      j * wt residualTotalWeights (regularProduct H A) ≤ T ∧
      j * wt residualYSWeights (regularProduct H A) ≤ YS ∧
      j * wt residualSWeights (regularProduct H A) ≤ S)
    (hfield : ∀ B : Finset (RCN266.RegularIndex H), B ⊆ A →
      B.card < ENat.card K) :
    let U := universalFactors H A q
    (∀ v, regularProduct H U ∣ q v) ∧
      (U = A ∨
        U ⊂ A ∧ HasCollisionFreeBatchHelpers H A (A \ U) q j T YS S) := by
  classical
  let U := universalFactors H A q
  have hUsub : U ⊆ A := universalFactors_subset H A q
  have hprod : ∀ v, regularProduct H U ∣ q v :=
    universalProduct_dvd H A q
  refine ⟨hprod, ?_⟩
  by_cases hall : U = A
  · exact Or.inl hall
  · right
    have hproper : U ⊂ A :=
      (_root_.ssubset_iff_subset_ne).mpr ⟨hUsub, hall⟩
    have hN : (A \ U).Nonempty := by
      apply Finset.sdiff_nonempty.mpr
      intro hAU
      exact hall (Finset.Subset.antisymm hUsub hAU)
    have hnonuniversal : ∀ F ∈ A \ U, ¬ ∀ v, F.1 ∣ q v := by
      intro F hFN hdiv
      have hparts := Finset.mem_sdiff.mp hFN
      apply hparts.2
      exact (mem_universalFactors H A q F).mpr ⟨hparts.1, hdiv⟩
    refine ⟨hproper, ?_⟩
    exact exists_collisionFree_batch_helpers H A (A \ U)
      Finset.sdiff_subset hN q hq j Dq w T YS S hbox hfeasible
      hnonuniversal (hfield (A \ U) Finset.sdiff_subset)

/-! ## Quotienting a fully universal batch -/

private theorem sub_mul_then_one (a b j:ℕ):
    a-j*b-b=a-(j+1)*b:=by
  rw [Nat.sub_sub,Nat.add_mul,one_mul]

/-- A raw constraint-kernel reconstruction lies in the nested source box as
soon as the usual contact/slope shape inequality supplies its YS cap. -/
theorem kernelReconstruct_mem_nested
    {I:Type} [Fintype I]
    (D w L S m YS:ℕ) (nodes u0 u1:I → K)
    (hw:1 ≤ w) (hshape:D+S ≤ w*(YS+1)):
    ∀ v:ConstraintKernel (K:=K) D w L S m nodes u0 u1,
      kernelReconstructLinear (K:=K) D w L S m nodes u0 u1 v ∈
        nestedCoefficientBox K D w L YS S:=by
  intro v d hd
  have hglobal:=reconstruct_mem_globalCoefficientBox K D w L S v.1
  have hb:=hglobal hd
  have hYS:=flag_box_ys_bound D w L S YS hw hshape
    (reconstruct K D w L S v.1) hglobal
  have hy:=(MvPolynomial.le_weightedTotalDegree residualYSWeights hd).trans hYS
  rw [weight_fin4] at hy
  simp only [residualYSWeights] at hy
  refine ⟨hb.1,?_,hb.2.1,hb.2.2⟩
  simpa [residualYSWeights] using hy

/-- Source-entry adapter for a universally divisible squarefree regular
product.  This is the batch analogue of the single-factor private
`quotient_nested` construction: it builds the injective quotient family and
subtracts the product's four weights exactly once. -/
theorem kernelQuotient_regularProduct_nested
    {I:Type} [Fintype I]
    (D w L S m YS:ℕ) (nodes u0 u1:I → K)
    (hw:1 ≤ w) (hshape:D+S ≤ w*(YS+1))
    (H:P4 K) (A:Finset (RCN266.RegularIndex H))
    (hdiv:∀ v:ConstraintKernel (K:=K) D w L S m nodes u0 u1,
      regularProduct H A ∣ reconstruct K D w L S v.1):
    ∃ q:ConstraintKernel (K:=K) D w L S m nodes u0 u1 →ₗ[K] P4 K,
      Function.Injective q ∧
      (∀ v,reconstruct K D w L S v.1=regularProduct H A*q v) ∧
      ∀ v,q v ∈ nestedCoefficientBox K
        (D-wt (contactWeights w) (regularProduct H A)) w
        (L-wt residualTotalWeights (regularProduct H A))
        (YS-wt residualYSWeights (regularProduct H A))
        (S-wt residualSWeights (regularProduct H A)):=by
  let recon:=kernelReconstructLinear (K:=K) D w L S m nodes u0 u1
  have hdiv':∀ v,regularProduct H A ∣ recon v:=by
    intro v
    simpa only [recon,kernelReconstructLinear_apply] using hdiv v
  obtain ⟨hq,hprod,hbox⟩:=quotientLinear_nested_data D w L YS S recon
    (kernelReconstructLinear_injective (K:=K) D w L S m nodes u0 u1)
    (kernelReconstruct_mem_nested D w L S m YS nodes u0 u1 hw hshape)
    (regularProduct H A) (regularProduct_ne_zero H A) hdiv'
  let q:=quotientLinear recon (regularProduct H A)
    (regularProduct_ne_zero H A) hdiv'
  refine ⟨q,hq,?_,?_⟩
  · intro v
    simpa only [recon,kernelReconstructLinear_apply,q] using hprod v
  · exact hbox

/-- If the entire current batch product divides an injective family, divide
by that product in one operation.  The family remains injective, the product
power advances from `j` to `j+1`, and all four residual coordinates are
normalized to the new exponent. -/
theorem quotient_by_universal_regularProduct
    [AddCommGroup V] [Module K V]
    (H:P4 K) (A:Finset (RCN266.RegularIndex H))
    (q:V →ₗ[K] P4 K) (hq:Function.Injective q)
    (j Dq w T YS S:ℕ)
    (hmem:∀ v,q v ∈ nestedCoefficientBox K Dq w
      (T-j*wt residualTotalWeights (regularProduct H A))
      (YS-j*wt residualYSWeights (regularProduct H A))
      (S-j*wt residualSWeights (regularProduct H A)))
    (hdiv:∀ v,regularProduct H A ∣ q v):
    ∃ qNext:V →ₗ[K] P4 K,
      Function.Injective qNext ∧
      (∀ v,regularProduct H A^j*q v=
        regularProduct H A^(j+1)*qNext v) ∧
      ∀ v,qNext v ∈ nestedCoefficientBox K
        (Dq-wt (contactWeights w) (regularProduct H A)) w
        (T-(j+1)*wt residualTotalWeights (regularProduct H A))
        (YS-(j+1)*wt residualYSWeights (regularProduct H A))
        (S-(j+1)*wt residualSWeights (regularProduct H A)):=by
  classical
  let P:=regularProduct H A
  let qNext:=quotientLinear q P (regularProduct_ne_zero H A) hdiv
  obtain ⟨hqNext,hprod,hnext⟩:=quotientLinear_nested_data
    Dq w
      (T-j*wt residualTotalWeights P)
      (YS-j*wt residualYSWeights P)
      (S-j*wt residualSWeights P)
      q hq hmem P (regularProduct_ne_zero H A) hdiv
  refine ⟨qNext,hqNext,?_,?_⟩
  · intro v
    change P^j*q v=P^(j+1)*qNext v
    rw [hprod v,pow_succ]
    ring
  · intro v
    have hv:=hnext v
    simpa only [P,sub_mul_then_one] using hv

/-- Complete current-stage adapter.  It first partitions factors using the
displayed post-projection family.  A proper universal child emits simultaneous
helpers for its complement.  If every factor is universal, it additionally
constructs the next injective quotient family and advances the common product
power.  Thus a consumer never has to infer post-projection properness from an
earlier source stage. -/
theorem currentPostProjection_split_or_advance
    [AddCommGroup V] [Module K V]
    (H:P4 K) (A:Finset (RCN266.RegularIndex H))
    (q:V →ₗ[K] P4 K) (hq:Function.Injective q)
    (j Dq w T YS S:ℕ)
    (hbox:∀ v,q v ∈ nestedCoefficientBox K Dq w
      (T-j*wt residualTotalWeights (regularProduct H A))
      (YS-j*wt residualYSWeights (regularProduct H A))
      (S-j*wt residualSWeights (regularProduct H A)))
    (hfeasible:
      j*wt residualTotalWeights (regularProduct H A) ≤ T ∧
      j*wt residualYSWeights (regularProduct H A) ≤ YS ∧
      j*wt residualSWeights (regularProduct H A) ≤ S)
    (hfield:∀ B:Finset (RCN266.RegularIndex H),B ⊆ A →
      B.card < ENat.card K):
    let U:=universalFactors H A q
    (∀ v,regularProduct H U ∣ q v) ∧
      ((U ⊂ A ∧ HasCollisionFreeBatchHelpers H A (A\U) q j T YS S) ∨
        (U=A ∧ ∃ qNext:V →ₗ[K] P4 K,
          Function.Injective qNext ∧
          (∀ v,regularProduct H A^j*q v=
            regularProduct H A^(j+1)*qNext v) ∧
          ∀ v,qNext v ∈ nestedCoefficientBox K
            (Dq-wt (contactWeights w) (regularProduct H A)) w
            (T-(j+1)*wt residualTotalWeights (regularProduct H A))
            (YS-(j+1)*wt residualYSWeights (regularProduct H A))
            (S-(j+1)*wt residualSWeights (regularProduct H A)))):=by
  classical
  let U:=universalFactors H A q
  obtain ⟨hprod,hcase⟩:=currentPostProjection_split H A q hq
    j Dq w T YS S hbox hfeasible hfield
  refine ⟨hprod,?_⟩
  rcases hcase with hall | hproper
  · right
    refine ⟨hall,?_⟩
    have hdivA:∀ v,regularProduct H A ∣ q v:=by
      intro v
      rw [← hall]
      exact hprod v
    exact quotient_by_universal_regularProduct H A q hq
      j Dq w T YS S hbox hdivA
  · exact Or.inl hproper

/-! ## First strict exit in a shared product-power chain -/

/-- A shared band chain exits when the post-projection universal factors form
a strict subset `U` of the current batch.  The index `j` counts additional
whole-product quotients after the displayed input family `q`; thus a source
which was quotiented once before calling this interface has original power
`j+1` at the exit. -/
def HasBatchExitStage
    [AddCommGroup V] [Module K V]
    (fuel Dlow w delta T YS S : ℕ)
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (q : V →ₗ[K] P4 K) : Prop :=
  ∃ (j : Fin fuel) (U : Finset (RCN266.RegularIndex H)) (v : V) (J : P4 K),
    U ⊂ A ∧ v ≠ 0 ∧ J ≠ 0 ∧
      regularProduct H A ^ j.val * J = q v ∧
      J ∈ nestedCoefficientBox K
        (Dlow - j.val * delta -
          j.val * wt (contactWeights w) (regularProduct H A)) w
        (T - j.val * wt residualTotalWeights (regularProduct H A))
        (YS - j.val * wt residualYSWeights (regularProduct H A))
        (S - j.val * wt residualSWeights (regularProduct H A)) ∧
      ∀ F ∈ A \ U, ¬ F.1 ∣ J

/-- The batch analogue of `exists_power_stage_of_bandBudget_succ`.  At each
band the universal subset is recomputed on the projected family.  A proper
subset exits immediately; an all-universal stage quotients the entire
squarefree product and continues.  The terminal residual inequality rules
out an all-universal final stage.

This theorem is deliberately only the linear-algebraic stage selector.  Its
consumer multiplies the retained cofactor back into `J`, performs derivative
extraction, and applies the desired helper-count cap. -/
theorem exists_batchExitStage_of_bandBudget_succ
    [AddCommGroup V] [Module K V] [FiniteDimensional K V]
    (steps Dhigh Dlow w delta T YS S : ℕ)
    (hwidth : Dhigh ≤ Dlow + delta)
    (q : V →ₗ[K] P4 K) (hq : Function.Injective q)
    (hmem : ∀ v, q v ∈ nestedCoefficientBox K Dhigh w T YS S)
    (H : P4 K) (A : Finset (RCN266.RegularIndex H)) (hA : A.Nonempty)
    (hsource :
      powerBandBudget delta
          (wt residualTotalWeights (regularProduct H A))
          (wt residualYSWeights (regularProduct H A))
          (wt residualSWeights (regularProduct H A))
          T YS S (steps + 1) < Module.finrank K V)
    (hterminal :
      T - steps * wt residualTotalWeights (regularProduct H A) <
          wt residualTotalWeights (regularProduct H A) ∨
      YS - steps * wt residualYSWeights (regularProduct H A) <
          wt residualYSWeights (regularProduct H A) ∨
      S - steps * wt residualSWeights (regularProduct H A) <
          wt residualSWeights (regularProduct H A))
    (hfield : A.card < ENat.card K) :
    HasBatchExitStage (steps + 1) Dlow w delta T YS S H A q := by
  classical
  let P := regularProduct H A
  have hP : P ≠ 0 := by
    simpa only [P] using regularProduct_ne_zero H A
  change powerBandBudget delta
      (wt residualTotalWeights P) (wt residualYSWeights P)
      (wt residualSWeights P) T YS S (steps + 1) <
    Module.finrank K V at hsource
  change
    T - steps * wt residualTotalWeights P < wt residualTotalWeights P ∨
    YS - steps * wt residualYSWeights P < wt residualYSWeights P ∨
    S - steps * wt residualSWeights P < wt residualSWeights P at hterminal
  induction steps generalizing V Dhigh Dlow T YS S with
  | zero =>
      let bandOne := (highBandMap (K := K) w Dlow delta T YS S).comp q
      let lowOne := LinearMap.ker bandOne
      have hrangeOne : Module.finrank K bandOne.range ≤
          delta * channelCount T YS S := by
        calc
          Module.finrank K bandOne.range ≤
              Module.finrank K (HighBandIndex delta T YS S → K) :=
            bandOne.range.finrank_le
          _ = delta * channelCount T YS S := by
            rw [Module.finrank_fintype_fun_eq_card, highBandIndex_card]
      have hlowOneRank : 0 < Module.finrank K lowOne := by
        have hsum := bandOne.finrank_range_add_finrank_ker
        change Module.finrank K bandOne.range + Module.finrank K lowOne =
          Module.finrank K V at hsum
        have hfirst : delta * channelCount T YS S < Module.finrank K V := by
          simpa only [powerBandBudget, Nat.add_zero] using hsource
        omega
      let qOne : lowOne →ₗ[K] P4 K := q.comp lowOne.subtype
      have hqOne : Function.Injective qOne := by
        intro a b hab
        apply Subtype.ext
        apply hq
        simpa only [qOne, LinearMap.comp_apply, Submodule.coe_subtype] using hab
      have hqOneBox : ∀ v : lowOne,
          qOne v ∈ nestedCoefficientBox K Dlow w T YS S := by
        intro v
        have hzero : highBandMap w Dlow delta T YS S (q v.1) = 0 := by
          have hv := v.2
          change bandOne v.1 = 0 at hv
          simpa only [bandOne, qOne, LinearMap.comp_apply,
            Submodule.coe_subtype] using hv
        simpa only [qOne, LinearMap.comp_apply, Submodule.coe_subtype] using
          mem_low_of_highBandMap_eq_zero Dhigh Dlow w delta T YS S hwidth
            (q v.1) (hmem v.1) hzero
      let U := universalFactors H A qOne
      have hUsub : U ⊆ A := universalFactors_subset H A qOne
      by_cases hall : U = A
      · have hdivP : ∀ v : lowOne, P ∣ qOne v := by
          intro v
          have hv := universalProduct_dvd H A qOne v
          change regularProduct H U ∣ qOne v at hv
          rw [hall] at hv
          simpa only [P] using hv
        exfalso
        obtain ⟨v, hv⟩ :=
          Module.finrank_pos_iff_exists_ne_zero.mp hlowOneRank
        have hqv : qOne v ≠ 0 := by
          intro hz
          apply hv
          apply hqOne
          simpa only [map_zero] using hz
        have hb := nested_mem_weights (hqOneBox v) hqv
        have hdivT : wt residualTotalWeights P ≤
            wt residualTotalWeights (qOne v) := by
          simpa only [wt] using
            weightedTotalDegree_le_of_dvd residualTotalWeights P
              (qOne v) (hdivP v) hqv
        have hdivY : wt residualYSWeights P ≤
            wt residualYSWeights (qOne v) := by
          simpa only [wt] using
            weightedTotalDegree_le_of_dvd residualYSWeights P
              (qOne v) (hdivP v) hqv
        have hdivS : wt residualSWeights P ≤
            wt residualSWeights (qOne v) := by
          simpa only [wt] using
            weightedTotalDegree_le_of_dvd residualSWeights P
              (qOne v) (hdivP v) hqv
        rcases hterminal with ht | hy | hs
        · apply (not_lt_of_ge (hdivT.trans hb.1))
          simpa only [Nat.zero_mul, Nat.sub_zero] using ht
        · apply (not_lt_of_ge (hdivY.trans hb.2.1))
          simpa only [Nat.zero_mul, Nat.sub_zero] using hy
        · apply (not_lt_of_ge (hdivS.trans hb.2.2.1))
          simpa only [Nat.zero_mul, Nat.sub_zero] using hs
      · have hproper : U ⊂ A :=
          (_root_.ssubset_iff_subset_ne).mpr ⟨hUsub, hall⟩
        have hN : (A \ U).Nonempty := by
          apply Finset.sdiff_nonempty.mpr
          intro hAU
          exact hall (Finset.Subset.antisymm hUsub hAU)
        have hnon : ∀ F ∈ A \ U, ¬ ∀ v, F.1 ∣ qOne v := by
          intro F hFN hdiv
          have hp := Finset.mem_sdiff.mp hFN
          apply hp.2
          exact (mem_universalFactors H A qOne F).mpr ⟨hp.1, hdiv⟩
        have hNcard : (A \ U).card < ENat.card K := by
          calc
            ((A \ U).card : ENat) ≤ (A.card : ENat) := by
              exact_mod_cast (Finset.card_le_card Finset.sdiff_subset)
            _ < ENat.card K := hfield
        obtain ⟨v, hv, havoid⟩ := exists_avoiding_nonuniversal_factors
          (A \ U) hN qOne (fun F => F.1) hnon hNcard
        have hqv : qOne v ≠ 0 := by
          intro hz
          apply hv
          apply hqOne
          simpa only [map_zero] using hz
        refine ⟨⟨0, by omega⟩, U, v.1, qOne v, hproper, ?_, hqv, ?_, ?_, ?_⟩
        · intro hz
          apply hv
          exact Subtype.ext hz
        · simp only [Fin.val_zero, pow_zero, one_mul, qOne,
            LinearMap.comp_apply, Submodule.coe_subtype]
        · simpa only [Fin.val_zero, zero_mul, Nat.sub_zero] using hqOneBox v
        · exact havoid
  | succ steps ih =>
      let bandOne := (highBandMap (K := K) w Dlow delta T YS S).comp q
      let lowOne := LinearMap.ker bandOne
      have hrangeOne : Module.finrank K bandOne.range ≤
          delta * channelCount T YS S := by
        calc
          Module.finrank K bandOne.range ≤
              Module.finrank K (HighBandIndex delta T YS S → K) :=
            bandOne.range.finrank_le
          _ = delta * channelCount T YS S := by
            rw [Module.finrank_fintype_fun_eq_card, highBandIndex_card]
      have hlowOneRank :
          powerBandBudget delta
              (wt residualTotalWeights P) (wt residualYSWeights P)
              (wt residualSWeights P)
              (T - wt residualTotalWeights P)
              (YS - wt residualYSWeights P)
              (S - wt residualSWeights P) (steps + 1) <
            Module.finrank K lowOne := by
        have hsum := bandOne.finrank_range_add_finrank_ker
        change Module.finrank K bandOne.range + Module.finrank K lowOne =
          Module.finrank K V at hsum
        have hbudget :
            delta * channelCount T YS S +
                powerBandBudget delta
                  (wt residualTotalWeights P) (wt residualYSWeights P)
                  (wt residualSWeights P)
                  (T - wt residualTotalWeights P)
                  (YS - wt residualYSWeights P)
                  (S - wt residualSWeights P) (steps + 1) <
              Module.finrank K V := by
          simpa only [powerBandBudget, Nat.succ_eq_add_one,
            Nat.add_assoc] using hsource
        omega
      let qOne : lowOne →ₗ[K] P4 K := q.comp lowOne.subtype
      have hqOne : Function.Injective qOne := by
        intro a b hab
        apply Subtype.ext
        apply hq
        simpa only [qOne, LinearMap.comp_apply, Submodule.coe_subtype] using hab
      have hqOneBox : ∀ v : lowOne,
          qOne v ∈ nestedCoefficientBox K Dlow w T YS S := by
        intro v
        have hzero : highBandMap w Dlow delta T YS S (q v.1) = 0 := by
          have hv := v.2
          change bandOne v.1 = 0 at hv
          simpa only [bandOne, qOne, LinearMap.comp_apply,
            Submodule.coe_subtype] using hv
        simpa only [qOne, LinearMap.comp_apply, Submodule.coe_subtype] using
          mem_low_of_highBandMap_eq_zero Dhigh Dlow w delta T YS S hwidth
            (q v.1) (hmem v.1) hzero
      let U := universalFactors H A qOne
      have hUsub : U ⊆ A := universalFactors_subset H A qOne
      by_cases hall : U = A
      · have hdivP : ∀ v : lowOne, P ∣ qOne v := by
          intro v
          have hv := universalProduct_dvd H A qOne v
          change regularProduct H U ∣ qOne v at hv
          rw [hall] at hv
          simpa only [P] using hv
        let qTwo := quotientLinear qOne P hP hdivP
        obtain ⟨hqTwo, _hprodTwo, hqTwoBox⟩ :=
          quotientLinear_nested_data Dlow w T YS S qOne hqOne hqOneBox
            P hP hdivP
        let DOneHigh := Dlow - wt (contactWeights w) P
        let DOneLow := Dlow - delta - wt (contactWeights w) P
        let TOne := T - wt residualTotalWeights P
        let YOne := YS - wt residualYSWeights P
        let SOne := S - wt residualSWeights P
        have hwidthRest : DOneHigh ≤ DOneLow + delta := by
          simp only [DOneHigh, DOneLow]
          omega
        have hterminalRest :
            TOne - steps * wt residualTotalWeights P <
                wt residualTotalWeights P ∨
            YOne - steps * wt residualYSWeights P <
                wt residualYSWeights P ∨
            SOne - steps * wt residualSWeights P <
                wt residualSWeights P := by
          rcases hterminal with ht | hy | hs
          · left
            simpa only [TOne, Nat.sub_sub, Nat.add_mul, one_mul,
              Nat.succ_eq_add_one, Nat.add_comm] using ht
          · right; left
            simpa only [YOne, Nat.sub_sub, Nat.add_mul, one_mul,
              Nat.succ_eq_add_one, Nat.add_comm] using hy
          · right; right
            simpa only [SOne, Nat.sub_sub, Nat.add_mul, one_mul,
              Nat.succ_eq_add_one, Nat.add_comm] using hs
        obtain ⟨j, child, v, J, hchild, hv, hJ, heq, hbox, havoid⟩ :=
          ih DOneHigh DOneLow TOne YOne SOne hwidthRest qTwo hqTwo
            (by simpa only [qTwo, DOneHigh, TOne, YOne, SOne] using hqTwoBox)
            (by simpa only [TOne, YOne, SOne] using hlowOneRank)
            hterminalRest
        let jUp : Fin (Nat.succ steps + 1) := ⟨j.val + 1, by omega⟩
        refine ⟨jUp, child, v.1, J, hchild, ?_, hJ, ?_, ?_, havoid⟩
        · intro hz
          apply hv
          exact Subtype.ext hz
        · change P ^ (j.val + 1) * J = q v.1
          calc
            P ^ (j.val + 1) * J = P * (P ^ j.val * J) := by
              rw [pow_succ']
              ring
            _ = P * qTwo v := by rw [heq]
            _ = qOne v :=
              (recon_eq_mul_quotientPolynomial qOne P hdivP v).symm
            _ = q v.1 := rfl
        · have hD :
              DOneLow - j.val * delta -
                  j.val * wt (contactWeights w) P =
                Dlow - (j.val + 1) * delta -
                  (j.val + 1) * wt (contactWeights w) P := by
              simp only [DOneLow, Nat.sub_sub, Nat.add_mul, one_mul]
              congr 1
              omega
          have hT : TOne - j.val * wt residualTotalWeights P =
              T - (j.val + 1) * wt residualTotalWeights P := by
            simp only [TOne, Nat.sub_sub, Nat.add_mul, one_mul]
            congr 1
            omega
          have hY : YOne - j.val * wt residualYSWeights P =
              YS - (j.val + 1) * wt residualYSWeights P := by
            simp only [YOne, Nat.sub_sub, Nat.add_mul, one_mul]
            congr 1
            omega
          have hS : SOne - j.val * wt residualSWeights P =
              S - (j.val + 1) * wt residualSWeights P := by
            simp only [SOne, Nat.sub_sub, Nat.add_mul, one_mul]
            congr 1
            omega
          change J ∈ nestedCoefficientBox K
            (DOneLow - j.val * delta -
              j.val * wt (contactWeights w) P) w
            (TOne - j.val * wt residualTotalWeights P)
            (YOne - j.val * wt residualYSWeights P)
            (SOne - j.val * wt residualSWeights P) at hbox
          change J ∈ nestedCoefficientBox K
            (Dlow - (j.val + 1) * delta -
              (j.val + 1) * wt (contactWeights w) P) w
            (T - (j.val + 1) * wt residualTotalWeights P)
            (YS - (j.val + 1) * wt residualYSWeights P)
            (S - (j.val + 1) * wt residualSWeights P)
          rw [hD, hT, hY, hS] at hbox
          exact hbox
      · have hproper : U ⊂ A :=
          (_root_.ssubset_iff_subset_ne).mpr ⟨hUsub, hall⟩
        have hN : (A \ U).Nonempty := by
          apply Finset.sdiff_nonempty.mpr
          intro hAU
          exact hall (Finset.Subset.antisymm hUsub hAU)
        have hnon : ∀ F ∈ A \ U, ¬ ∀ v, F.1 ∣ qOne v := by
          intro F hFN hdiv
          have hp := Finset.mem_sdiff.mp hFN
          apply hp.2
          exact (mem_universalFactors H A qOne F).mpr ⟨hp.1, hdiv⟩
        have hNcard : (A \ U).card < ENat.card K := by
          calc
            ((A \ U).card : ENat) ≤ (A.card : ENat) := by
              exact_mod_cast (Finset.card_le_card Finset.sdiff_subset)
            _ < ENat.card K := hfield
        obtain ⟨v, hv, havoid⟩ := exists_avoiding_nonuniversal_factors
          (A \ U) hN qOne (fun F => F.1) hnon hNcard
        have hqv : qOne v ≠ 0 := by
          intro hz
          apply hv
          apply hqOne
          simpa only [map_zero] using hz
        refine ⟨⟨0, by omega⟩, U, v.1, qOne v, hproper, ?_, hqv, ?_, ?_, ?_⟩
        · intro hz
          apply hv
          exact Subtype.ext hz
        · simp only [Fin.val_zero, pow_zero, one_mul, qOne,
            LinearMap.comp_apply, Submodule.coe_subtype]
        · simpa only [Fin.val_zero, zero_mul, Nat.sub_zero] using hqOneBox v
        · exact havoid

/-! ## Derivative extraction has no internal-collision locus -/

/-- The retained complementary product is part of the helper passed to the
power-extraction lemma.  Hence this conclusion holds on every regular seed,
without assuming that the complementary product specializes nonzero. -/
theorem specialization_eq_zero_of_batch_power
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A)
    (j : ℕ) (P : Polynomial K) (gamma : K) (J : P4 K)
    (hfactorial : (j.factorial : K) ≠ 0)
    (hFzero : RCN319.specialization K P gamma F.1 = 0)
    (hregular : RCN319.specialization K P gamma
      (MvPolynomial.pderiv (2 : Fin 4) F.1) ≠ 0)
    (hpower : RCN319.specialization K P gamma
      (iteratePderivR j (regularProduct H A ^ j * J)) = 0) :
    RCN319.specialization K P gamma
      (regularCofactor H A F ^ j * J) = 0 := by
  rw [regularProduct_power_split H A F hFA j J] at hpower
  exact specialization_eq_zero_of_iteratePderivR_power_product
    j P gamma F.1 (regularCofactor H A F ^ j * J)
    hfactorial hFzero hregular hpower

/-- Kernel/contact wrapper for the collision-free batch extraction.  The
only capacity cost is the derivative order `j`; no specialization condition
on any other regular factor appears. -/
theorem batch_helper_zero_on_regularSeeds
    {I : Type} [Fintype I] [DecidableEq I]
    (j D Dlow w L S m agreements p : ℕ)
    [CharP K p] (hp : p.Prime)
    (nodes : I ↪ K) (u0 u1 : I → K)
    (H : P4 K) (A : Finset (RCN266.RegularIndex H))
    (F : RCN266.RegularIndex H) (hFA : F ∈ A)
    (selected : K → Polynomial K) (Gamma : Finset K)
    (v : ConstraintKernel (K := K) D w L S m nodes u0 u1)
    (J : P4 K)
    (hj : 1 ≤ j) (hjchar : j < p) (hw : 1 ≤ w)
    (hdegree : ∀ gamma ∈ Gamma, (selected gamma).natDegree ≤ w)
    (hagreement : ∀ gamma ∈ Gamma, agreements ≤
      ((Finset.univ : Finset I).filter (fun i ↦
        (selected gamma).eval (nodes i) = u0 i + gamma * u1 i)).card)
    (hcapacity : Dlow ≤ (m - j) * agreements + j * (w - 1))
    (hlow : reconstruct K D w L S v.1 ∈
      globalCoefficientBox K Dlow w L S)
    (heq : regularProduct H A ^ j * J = reconstruct K D w L S v.1) :
    ∀ gamma ∈ regularSeeds H selected Gamma F,
      RCN319.specialization K (selected gamma) gamma
        (regularCofactor H A F ^ j * J) = 0 := by
  classical
  intro gamma hgamma
  have hgammaG := regularSeeds_subset H selected Gamma F hgamma
  let support := (Finset.univ : Finset I).filter (fun i ↦
    (selected gamma).eval (nodes i) = u0 i + gamma * u1 i)
  have hcard : agreements ≤ support.card := hagreement gamma hgammaG
  have hcap : Dlow ≤ (m - j) * support.card + j * (w - 1) :=
    hcapacity.trans (Nat.add_le_add_right
      (Nat.mul_le_mul_left (m - j) hcard) _)
  have hvalues : ∀ i ∈ support,
      (selected gamma).eval (nodes i) = u0 i + gamma * u1 i := by
    intro i hi
    exact (Finset.mem_filter.mp hi).2
  have hder := specialization_iteratePderivR_eq_zero_of_kernel_low_box
    j D Dlow w L S m nodes u0 u1 v hlow
    (selected gamma) gamma support hj hw (hdegree gamma hgammaG)
    hcap hvalues
  rw [← heq] at hder
  obtain ⟨hFzero, hregular⟩ := (Finset.mem_filter.mp hgamma).2
  exact specialization_eq_zero_of_batch_power H A F hFA j
    (selected gamma) gamma J
    (factorial_ne_zero_of_lt_char p j hp hjchar)
    hFzero hregular hder

/-! ## Numerical one-split interface -/

/-- A one-split counting lemma.  Factors in `U` are the universal branch and
are charged by an ordinary cap; every other factor is charged by the helper
obtained from the common batch witness.  All numerical work is isolated in
the final branch inequality. -/
theorem regularSeeds_sum_le_of_one_split
    (H : P4 K) (A U : Finset (RCN266.RegularIndex H)) (hUA : U ⊆ A)
    (selected : K → Polynomial K) (Gamma : Finset K)
    (ordinaryCap helperCap : RCN266.RegularIndex H → ℕ) (B : ℕ)
    (hordinary : ∀ F ∈ U,
      (regularSeeds H selected Gamma F).card ≤ ordinaryCap F)
    (hhelper : ∀ F ∈ A \ U,
      (regularSeeds H selected Gamma F).card ≤ helperCap F)
    (hbranch : (∑ F ∈ U, ordinaryCap F) +
      (∑ F ∈ A \ U, helperCap F) ≤ B) :
    (∑ F ∈ A, (regularSeeds H selected Gamma F).card) ≤ B := by
  classical
  have hsplit : A = U ∪ (A \ U) := by
    ext F
    simp only [Finset.mem_union, Finset.mem_sdiff]
    constructor
    · intro hFA
      by_cases hFU : F ∈ U
      · exact Or.inl hFU
      · exact Or.inr ⟨hFA, hFU⟩
    · intro h
      exact h.elim (fun h => hUA h) (fun h => h.1)
  have hdisjoint : Disjoint U (A \ U) := by
    apply Finset.disjoint_left.mpr
    intro F hFU hFd
    exact (Finset.mem_sdiff.mp hFd).2 hFU
  rw [hsplit, Finset.sum_union hdisjoint]
  exact (Nat.add_le_add
    (Finset.sum_le_sum fun F hF => hordinary F hF)
    (Finset.sum_le_sum fun F hF => hhelper F hF)).trans hbranch

/-! ## Abstract recursion by a phase potential

The state type below is deliberately indexed by an arbitrary well-founded
phase rank.  A state may therefore carry the current quotient space, its
post-projection linear family, the product identity, and all box receipts;
none of those data has to be compressed into a flag.  Its `factors` are
exactly the factors universal immediately after the preceding projection.

At a successor state a consumer has two choices.

* Stop, by showing that the sum of ordinary per-factor caps fits the current
  potential.
* Produce a child state on the universal subset `U`.  All factors in `A \ U`
  must receive helper bounds from the *current* post-projection family.  The
  child potential plus those helper caps must fit the parent potential.

The child may have `U = A`; the phase rank then records one fewer band of the
same source.  When `U ⊂ A`, the child may instead reset to a fresh source and
the phase rank can encode a lexicographic measure such as aggregate positive
R-weight followed by that source's remaining bands.  At rank zero `hbase` is the
terminal receipt (usually the fact that no nonempty universal subset fits the
residual box, followed by one last simultaneous-avoidance split).
-/

/-- Soundness of a recursive post-projection partition certificate.  This is
pure finite-sum bookkeeping: all algebraic obligations are localized in
`hstep`, and all numerical obligations are localized in `hbase`, the stop
alternative, and the displayed potential inequality. -/
theorem sum_count_le_of_phasePotential
    {A : Type} [DecidableEq A]
    (count ordinaryCap : A → ℕ)
    (State : ℕ → Type)
    (factors : (n : ℕ) → State n → Finset A)
    (potential : (n : ℕ) → State n → ℕ)
    (hordinary : ∀ a, count a ≤ ordinaryCap a)
    (hbase : ∀ s : State 0,
      (∑ a ∈ factors 0 s, ordinaryCap a) ≤ potential 0 s)
    (hstep : ∀ n (s : State (n + 1)),
      ((∑ a ∈ factors (n + 1) s, ordinaryCap a) ≤
          potential (n + 1) s) ∨
        ∃ (t : State n) (helperCap : A → ℕ),
          factors n t ⊆ factors (n + 1) s ∧
          (∀ a ∈ factors (n + 1) s \ factors n t,
            count a ≤ helperCap a) ∧
          potential n t +
              (∑ a ∈ factors (n + 1) s \ factors n t, helperCap a) ≤
            potential (n + 1) s)
    (n : ℕ) (s : State n) :
    (∑ a ∈ factors n s, count a) ≤ potential n s := by
  induction n with
  | zero =>
      exact (Finset.sum_le_sum fun a _ha => hordinary a).trans (hbase s)
  | succ n ih =>
      rcases hstep n s with hstop | ⟨t, helperCap, hsub, hhelper, hpot⟩
      · exact (Finset.sum_le_sum fun a _ha => hordinary a).trans hstop
      · let current := factors (n + 1) s
        let universal := factors n t
        have hsplit : current = universal ∪ (current \ universal) := by
          ext a
          simp only [Finset.mem_union, Finset.mem_sdiff]
          constructor
          · intro ha
            by_cases hau : a ∈ universal
            · exact Or.inl hau
            · exact Or.inr ⟨ha, hau⟩
          · intro ha
            exact ha.elim (fun hau => hsub hau) (fun hd => hd.1)
        have hdisjoint : Disjoint universal (current \ universal) := by
          apply Finset.disjoint_left.mpr
          intro a hau had
          exact (Finset.mem_sdiff.mp had).2 hau
        change (∑ a ∈ current, count a) ≤ potential (n + 1) s
        rw [hsplit, Finset.sum_union hdisjoint]
        exact (Nat.add_le_add (ih t)
          (Finset.sum_le_sum fun a ha => hhelper a ha)).trans hpot

/-- Specialization of the abstract phase-potential recursion to regular-seed
counts.  `OwnBound` is precisely the ordinary stopping interface already
produced by `LocatorFixedOwnBound`; batch helper consumers need only populate
the second branch of `hstep`. -/
theorem regularSeeds_sum_le_of_phasePotential
    (H : P4 K) (selected : K → Polynomial K) (Gamma : Finset K)
    (State : ℕ → Type)
    (factors : (n : ℕ) → State n →
      Finset (RCN266.RegularIndex H))
    (potential : (n : ℕ) → State n → ℕ)
    (hown : ∀ F, LocatorHybridCost.OwnBound
      (regularSeeds H selected Gamma F).card
      (regularCumulativeFlag H F))
    (hbase : ∀ s : State 0,
      (∑ F ∈ factors 0 s,
        LocatorHybridCost.ordinaryCostOf (regularCumulativeFlag H F)) ≤
          potential 0 s)
    (hstep : ∀ n (s : State (n + 1)),
      ((∑ F ∈ factors (n + 1) s,
          LocatorHybridCost.ordinaryCostOf (regularCumulativeFlag H F)) ≤
            potential (n + 1) s) ∨
        ∃ (t : State n) (helperCap : RCN266.RegularIndex H → ℕ),
          factors n t ⊆ factors (n + 1) s ∧
          (∀ F ∈ factors (n + 1) s \ factors n t,
            (regularSeeds H selected Gamma F).card ≤ helperCap F) ∧
          potential n t +
              (∑ F ∈ factors (n + 1) s \ factors n t, helperCap F) ≤
            potential (n + 1) s)
    (n : ℕ) (s : State n) :
    (∑ F ∈ factors n s,
      (regularSeeds H selected Gamma F).card) ≤ potential n s := by
  classical
  apply sum_count_le_of_phasePotential
    (fun F : RCN266.RegularIndex H =>
      (regularSeeds H selected Gamma F).card)
    (fun F : RCN266.RegularIndex H =>
      LocatorHybridCost.ordinaryCostOf (regularCumulativeFlag H F))
    State factors potential
  · intro F
    exact LocatorHybridCost.ownBound_le_ordinaryCostOf (hown F)
  · exact hbase
  · exact hstep

/-! ## Complete descent through one source phase

The rank-indexed interface above is convenient while constructing one
particular algebraic route.  Numerical prefix certificates use a different
view: keep applying the same source while it routes the current aggregate,
and stop at the first nonrouteable strict subaggregate.  The next two lemmas
are the finite-set induction engine for that view.

Crucially, a routed step must return a *strict* child.  Thus its algebraic
implementation may restart from a fresh source on that child; no claim about
mixed powers in the preceding source family is hidden in this bookkeeping.
-/

/-- Repeatedly remove a helper-charged complement while `routeable` holds.
At the terminal subaggregate the single shared `defect` bounds what remains
above the additive charge. -/
theorem sum_count_le_charge_add_defect_of_strict_routes
    {A : Type} [DecidableEq A]
    (count charge : A → ℕ)
    (routeable : Finset A → Prop)
    (ambient : Finset A) (defect : ℕ)
    (hterminal : ∀ B, B ⊆ ambient → ¬ routeable B →
      (∑ a ∈ B, count a) ≤ (∑ a ∈ B, charge a) + defect)
    (hroute : ∀ B, B ⊆ ambient → routeable B →
      ∃ U, U ⊂ B ∧
        (∑ a ∈ B \ U, count a) ≤ (∑ a ∈ B \ U, charge a)) :
    (∑ a ∈ ambient, count a) ≤
      (∑ a ∈ ambient, charge a) + defect := by
  classical
  have aux : ∀ B : Finset A, B ⊆ ambient →
      (∑ a ∈ B, count a) ≤ (∑ a ∈ B, charge a) + defect := by
    intro B
    induction B using Finset.strongInduction with
    | H B ih =>
        intro hB
        by_cases hr : routeable B
        · obtain ⟨U, hUB, hexit⟩ := hroute B hB hr
          have hUsub : U ⊆ B := hUB.subset
          have hUambient : U ⊆ ambient := hUsub.trans hB
          have hUbound := ih U hUB hUambient
          let exited := B \ U
          have hexit' : (∑ a ∈ exited, count a) ≤
              (∑ a ∈ exited, charge a) := by
            simpa only [exited] using hexit
          have hsplit : B = U ∪ exited := by
            dsimp only [exited]
            exact (Finset.union_sdiff_of_subset hUsub).symm
          have hdisjoint : Disjoint U exited := by
            apply Finset.disjoint_left.mpr
            intro a hau had
            change a ∈ B \ U at had
            exact (Finset.mem_sdiff.mp had).2 hau
          calc
            (∑ a ∈ B, count a) =
                (∑ a ∈ U, count a) + (∑ a ∈ exited, count a) := by
              rw [hsplit, Finset.sum_union hdisjoint]
            _ ≤ ((∑ a ∈ U, charge a) + defect) +
                (∑ a ∈ exited, charge a) :=
              Nat.add_le_add hUbound hexit'
            _ = (∑ a ∈ B, charge a) + defect := by
              rw [hsplit, Finset.sum_union hdisjoint]
              omega
        · exact hterminal B hB hr
  exact aux ambient (fun _ ha => ha)

/-- One numerical phase transition.  `previous` is the already certified
bound before adding this source.  A nonrouteable terminal row bounds the
previous excess over the new additive charge, while a routeable row supplies
a strict child and helper-charged complement.  The resulting bound is the
minimum of retaining the previous certificate and using the new phase. -/
theorem sum_count_le_min_previous_onePhase
    {A : Type} [DecidableEq A]
    (count charge : A → ℕ)
    (routeable : Finset A → Prop)
    (previous : Finset A → ℕ)
    (ambient : Finset A) (defect : ℕ)
    (hprevious : ∀ B, B ⊆ ambient →
      (∑ a ∈ B, count a) ≤ previous B)
    (hterminal : ∀ B, B ⊆ ambient → ¬ routeable B →
      previous B ≤ (∑ a ∈ B, charge a) + defect)
    (hroute : ∀ B, B ⊆ ambient → routeable B →
      ∃ U, U ⊂ B ∧
        (∑ a ∈ B \ U, count a) ≤ (∑ a ∈ B \ U, charge a)) :
    (∑ a ∈ ambient, count a) ≤
      min (previous ambient) ((∑ a ∈ ambient, charge a) + defect) := by
  classical
  apply le_min
  · exact hprevious ambient (fun _ ha => ha)
  · apply sum_count_le_charge_add_defect_of_strict_routes
      count charge routeable ambient defect
    · intro B hB hnroute
      exact (hprevious B hB).trans (hterminal B hB hnroute)
    · exact hroute

end

end ProximityPrize.SubmissionLower.LocatorBatchProductRoute
