import ProximityPrize.SubmissionLower.LocatorReplacementGridRow14Band01T00
namespace ProximityPrize.SubmissionLower.LocatorReplacementGridData
set_option maxRecDepth 100000
set_option maxHeartbeats 30000000
theorem receipt_row_14_band_01_t_01 : RowTileReceipt 14 3 4 11 22 := by decide +kernel
end ProximityPrize.SubmissionLower.LocatorReplacementGridData
