import ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR06Checked
import ProximityPrize.SubmissionLower.LocatorPhase6800FastChannelCount
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData18
import ProximityPrize.SubmissionLower.LocatorPhase6800ReceiptRowData19

namespace ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR18Checked

open LocatorPhase6800Oracle LocatorPhase6800ReceiptCellCore ThresholdFastProof

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

theorem checked : PrefixCoreRIndexedOf LocatorPhase6800ReceiptRowData18.prefixData
    LocatorPhase6800ReceiptRowData19.prefixData 18 109 := by
  decide +kernel

#print axioms checked

end ProximityPrize.SubmissionLower.LocatorPhase6800PrefixCoreR18Checked
