import ProximityPrize.Benchmark.TargetLower
import ProximityPrize.SubmissionLower.MatrixRootMultiplicity

/-!
# Polynomial-matrix corank at an irreducible specialization

This is the characteristic-free analogue of scalar root-multiplicity.
Reduction modulo an arbitrary irreducible polynomial `mu` may merge all of
its geometric roots in positive characteristic.  The residue-field corank
still contributes one full power of `mu` per missing matrix rank.
-/

namespace ProximityPrize.SubmissionLower.MatrixIrreducibleMultiplicity

open scoped BigOperators

noncomputable section

variable {K : Type*} [Field K] [DecidableEq K]
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- If selected columns vanish after reduction modulo `mu`, each determinant
term contains one copy of `mu` for every selected column. -/
theorem pow_card_dvd_det_of_adjoinRoot_columns_eq_zero
    (mu : Polynomial K) (M : Matrix ι ι (Polynomial K)) (columns : Finset ι)
    (hzero : ∀ j ∈ columns, ∀ i, AdjoinRoot.mk mu (M i j) = 0) :
    mu ^ columns.card ∣ M.det := by
  classical
  rw [Matrix.det_apply']
  apply Finset.dvd_sum
  intro permutation _
  have hpart :
      (∏ _j ∈ columns, mu) ∣ ∏ j ∈ columns, M (permutation j) j := by
    apply Finset.prod_dvd_prod_of_dvd
    intro j hj
    exact AdjoinRoot.mk_eq_zero.mp (hzero j hj (permutation j))
  have hfull :
      (∏ j ∈ columns, M (permutation j) j) ∣
        ∏ j : ι, M (permutation j) j :=
    Finset.prod_dvd_prod_of_subset columns Finset.univ
      (fun j => M (permutation j) j) (Finset.subset_univ columns)
  have hproduct : mu ^ columns.card ∣ ∏ j : ι, M (permutation j) j := by
    simpa using hpart.trans hfull
  exact dvd_mul_of_dvd_right hproduct _

/-- Rank-loss divisibility for any surjective specialization to a field whose
kernel is generated by the irreducible polynomial `mu`.  This is the form
used by actual minpoly evaluation maps. -/
theorem pow_corank_dvd_det_of_surjective_specialization
    {A : Type*} [Field A]
    (mu : Polynomial K) (hmu : Irreducible mu)
    (f : Polynomial K →+* A) (hsurj : Function.Surjective f)
    (hker : ∀ g, f g = 0 ↔ mu ∣ g)
    (M : Matrix ι ι (Polynomial K)) :
    mu ^ (Fintype.card ι - (f.mapMatrix M).rank) ∣ M.det := by
  classical
  let lifted : Matrix ι ι A → Matrix ι ι (Polynomial K) := fun B i j =>
    Function.surjInv hsurj (B i j)
  have reduce_lifted (B : Matrix ι ι A) : f.mapMatrix (lifted B) = B := by
    ext i j
    exact Function.rightInverse_surjInv hsurj (B i j)
  let evaluated : Matrix ι ι A := f.mapMatrix M
  obtain ⟨V, U, e, hV, hU, hnormal⟩ := Matrix.exists_rank_normal_form evaluated
  let transformed : Matrix ι ι (Polynomial K) := lifted V * M * lifted U
  have heval : f.mapMatrix transformed =
      (Matrix.fromBlocks 1 0 0 0).submatrix e e := by
    change f.mapMatrix (lifted V * M * lifted U) = _
    rw [map_mul, map_mul, reduce_lifted, reduce_lifted]
    exact hnormal
  let zeroEmbedding : Fin (Fintype.card ι - evaluated.rank) ↪ ι := {
    toFun := fun j => e.symm (Sum.inr j)
    inj' := by
      intro i j hij
      exact Sum.inr.inj (e.symm.injective hij)
  }
  let zeroColumns : Finset ι := Finset.univ.map zeroEmbedding
  have hcard : zeroColumns.card = Fintype.card ι - evaluated.rank := by
    simp [zeroColumns]
  have hzero : ∀ j ∈ zeroColumns, ∀ i, mu ∣ transformed i j := by
    intro j hj i
    obtain ⟨j0, _, rfl⟩ := Finset.mem_map.mp hj
    apply (hker _).mp
    change f.mapMatrix transformed i (e.symm (Sum.inr j0)) = 0
    rw [heval]
    simp only [Matrix.submatrix_apply, Equiv.apply_symm_apply]
    cases e i <;> rfl
  have hdiv : mu ^ zeroColumns.card ∣ transformed.det := by
    classical
    rw [Matrix.det_apply']
    apply Finset.dvd_sum
    intro permutation _
    have hpart :
        (∏ _j ∈ zeroColumns, mu) ∣
          ∏ j ∈ zeroColumns, transformed (permutation j) j := by
      apply Finset.prod_dvd_prod_of_dvd
      intro j hj
      exact hzero j hj (permutation j)
    have hfull :
        (∏ j ∈ zeroColumns, transformed (permutation j) j) ∣
          ∏ j : ι, transformed (permutation j) j :=
      Finset.prod_dvd_prod_of_subset zeroColumns Finset.univ
        (fun j => transformed (permutation j) j) (Finset.subset_univ zeroColumns)
    have hproduct : mu ^ zeroColumns.card ∣
        ∏ j : ι, transformed (permutation j) j := by
      simpa using hpart.trans hfull
    exact dvd_mul_of_dvd_right hproduct _
  rw [hcard] at hdiv
  change mu ^ (Fintype.card ι - evaluated.rank) ∣
      (lifted V * M * lifted U).det at hdiv
  rw [Matrix.det_mul, Matrix.det_mul] at hdiv
  have hVdetMap : f (lifted V).det = V.det := by
    rw [RingHom.map_det]
    rw [reduce_lifted]
  have hUdetMap : f (lifted U).det = U.det := by
    rw [RingHom.map_det]
    rw [reduce_lifted]
  have hVdetNe : V.det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det V).mp hV).ne_zero
  have hUdetNe : U.det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det U).mp hU).ne_zero
  have hVnot : ¬mu ∣ (lifted V).det := by
    intro hdvd
    have hz : f (lifted V).det = 0 := (hker _).mpr hdvd
    rw [hVdetMap] at hz
    exact hVdetNe hz
  have hUnot : ¬mu ∣ (lifted U).det := by
    intro hdvd
    have hz : f (lifted U).det = 0 := (hker _).mpr hdvd
    rw [hUdetMap] at hz
    exact hUdetNe hz
  have hmiddle : mu ^ (Fintype.card ι - evaluated.rank) ∣ M.det * (lifted U).det :=
    hmu.prime.pow_dvd_of_dvd_mul_left _ hVnot (by simpa only [mul_assoc] using hdiv)
  exact hmu.prime.pow_dvd_of_dvd_mul_right _ hUnot hmiddle

theorem natDegree_mul_corank_le_of_surjective_specialization
    {A : Type*} [Field A]
    (mu : Polynomial K) (hmu : Irreducible mu)
    (f : Polynomial K →+* A) (hsurj : Function.Surjective f)
    (hker : ∀ g, f g = 0 ↔ mu ∣ g)
    (M : Matrix ι ι (Polynomial K)) (hdet : M.det ≠ 0) :
    mu.natDegree * (Fintype.card ι - (f.mapMatrix M).rank) ≤ M.det.natDegree := by
  have hdvd := pow_corank_dvd_det_of_surjective_specialization
    mu hmu f hsurj hker M
  have hdegree := Polynomial.natDegree_le_of_dvd hdvd hdet
  rw [Polynomial.natDegree_pow] at hdegree
  simpa [Nat.mul_comm] using hdegree

section Family

variable {J : Type*} [Fintype J] [DecidableEq J]
variable (A : J → Type*) [∀ j, Field (A j)]

/-- Pairwise-coprime irreducible specializations consume one common
determinant-degree budget, with their residue coranks weighted by full
irreducible degrees. -/
theorem sum_irreducible_coranks_le_natDegree_det
    (mu : J → Polynomial K) (hmu : ∀ j, Irreducible (mu j))
    (hmonic : ∀ j, (mu j).Monic)
    (hcoprime : Pairwise (fun i j => IsCoprime (mu i) (mu j)))
    (f : ∀ j, Polynomial K →+* A j)
    (hsurj : ∀ j, Function.Surjective (f j))
    (hker : ∀ j g, f j g = 0 ↔ mu j ∣ g)
    (M : Matrix ι ι (Polynomial K)) (hdet : M.det ≠ 0) :
    (∑ j, (mu j).natDegree *
      (Fintype.card ι - ((f j).mapMatrix M).rank)) ≤ M.det.natDegree := by
  classical
  let factor : J → Polynomial K := fun j =>
    mu j ^ (Fintype.card ι - ((f j).mapMatrix M).rank)
  have hfactorMonic (j : J) : (factor j).Monic :=
    (hmonic j).pow _
  have hfactorCoprime : Pairwise (fun i j => IsCoprime (factor i) (factor j)) := by
    intro i j hij
    exact (hcoprime hij).pow
  have hfactorDvd (j : J) : factor j ∣ M.det :=
    pow_corank_dvd_det_of_surjective_specialization
      (mu j) (hmu j) (f j) (hsurj j) (hker j) M
  have hprod : (∏ j, factor j) ∣ M.det :=
    Fintype.prod_dvd_of_coprime hfactorCoprime hfactorDvd
  have hdegree := Polynomial.natDegree_le_of_dvd hprod hdet
  rw [Polynomial.natDegree_prod_of_monic
    (s := Finset.univ) (f := factor) (fun j _ => hfactorMonic j)] at hdegree
  simpa [factor, Polynomial.natDegree_pow, Nat.mul_comm] using hdegree

end Family

/-- General rank-loss divisibility at an irreducible residue field.  The
rank-normal-form matrices are lifted entrywise.  Their determinants need not
be units upstairs, but they are nonzero modulo `mu`, so primality cancels
them without losing multiplicity. -/
theorem pow_corank_dvd_det_of_irreducible
    (mu : Polynomial K) (hmu : Irreducible mu)
    (M : Matrix ι ι (Polynomial K)) :
    mu ^ (Fintype.card ι - ((AdjoinRoot.mk mu).mapMatrix M).rank) ∣ M.det := by
  classical
  letI : Fact (Irreducible mu) := ⟨hmu⟩
  let A := AdjoinRoot mu
  let reduceMatrix : Matrix ι ι (Polynomial K) →+* Matrix ι ι A :=
    (AdjoinRoot.mk mu).mapMatrix
  let lifted : Matrix ι ι A → Matrix ι ι (Polynomial K) := fun B i j =>
    Function.surjInv AdjoinRoot.mk_surjective (B i j)
  have reduce_lifted (B : Matrix ι ι A) : reduceMatrix (lifted B) = B := by
    ext i j
    exact Function.rightInverse_surjInv AdjoinRoot.mk_surjective (B i j)
  let evaluated : Matrix ι ι A := reduceMatrix M
  obtain ⟨V, U, e, hV, hU, hnormal⟩ := Matrix.exists_rank_normal_form evaluated
  let transformed : Matrix ι ι (Polynomial K) := lifted V * M * lifted U
  have heval : reduceMatrix transformed =
      (Matrix.fromBlocks 1 0 0 0).submatrix e e := by
    change reduceMatrix (lifted V * M * lifted U) = _
    rw [map_mul, map_mul, reduce_lifted, reduce_lifted]
    exact hnormal
  let zeroEmbedding : Fin (Fintype.card ι - evaluated.rank) ↪ ι := {
    toFun := fun j => e.symm (Sum.inr j)
    inj' := by
      intro i j hij
      exact Sum.inr.inj (e.symm.injective hij)
  }
  let zeroColumns : Finset ι := Finset.univ.map zeroEmbedding
  have hcard : zeroColumns.card = Fintype.card ι - evaluated.rank := by
    simp [zeroColumns]
  have hzero : ∀ j ∈ zeroColumns, ∀ i,
      AdjoinRoot.mk mu (transformed i j) = 0 := by
    intro j hj i
    obtain ⟨j0, _, rfl⟩ := Finset.mem_map.mp hj
    change reduceMatrix transformed i (e.symm (Sum.inr j0)) = 0
    rw [heval]
    simp only [Matrix.submatrix_apply, Equiv.apply_symm_apply]
    cases e i <;> rfl
  have hdiv := pow_card_dvd_det_of_adjoinRoot_columns_eq_zero
    mu transformed zeroColumns hzero
  rw [hcard] at hdiv
  change mu ^ (Fintype.card ι - evaluated.rank) ∣
      (lifted V * M * lifted U).det at hdiv
  rw [Matrix.det_mul, Matrix.det_mul] at hdiv
  have hVdetMap : AdjoinRoot.mk mu (lifted V).det = V.det := by
    rw [RingHom.map_det]
    change (reduceMatrix (lifted V)).det = V.det
    rw [reduce_lifted]
  have hUdetMap : AdjoinRoot.mk mu (lifted U).det = U.det := by
    rw [RingHom.map_det]
    change (reduceMatrix (lifted U)).det = U.det
    rw [reduce_lifted]
  have hVdetNe : V.det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det V).mp hV).ne_zero
  have hUdetNe : U.det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det U).mp hU).ne_zero
  have hVnot : ¬mu ∣ (lifted V).det := by
    intro hdvd
    have hz : AdjoinRoot.mk mu (lifted V).det = 0 := AdjoinRoot.mk_eq_zero.mpr hdvd
    rw [hVdetMap] at hz
    exact hVdetNe hz
  have hUnot : ¬mu ∣ (lifted U).det := by
    intro hdvd
    have hz : AdjoinRoot.mk mu (lifted U).det = 0 := AdjoinRoot.mk_eq_zero.mpr hdvd
    rw [hUdetMap] at hz
    exact hUdetNe hz
  have hmiddle : mu ^ (Fintype.card ι - evaluated.rank) ∣ M.det * (lifted U).det :=
    hmu.prime.pow_dvd_of_dvd_mul_left _ hVnot (by simpa only [mul_assoc] using hdiv)
  exact hmu.prime.pow_dvd_of_dvd_mul_right _ hUnot hmiddle

/-- Degree form of irreducible-specialization multiplicity.  Unlike a sum
over distinct geometric roots, this charges the full inseparable degree of
`mu`. -/
theorem natDegree_mul_corank_le_natDegree_det
    (mu : Polynomial K) (hmu : Irreducible mu)
    (M : Matrix ι ι (Polynomial K)) (hdet : M.det ≠ 0) :
    mu.natDegree *
        (Fintype.card ι - ((AdjoinRoot.mk mu).mapMatrix M).rank) ≤
      M.det.natDegree := by
  have hdvd := pow_corank_dvd_det_of_irreducible mu hmu M
  have hpow : mu ^ (Fintype.card ι - ((AdjoinRoot.mk mu).mapMatrix M).rank) ≠ 0 :=
    pow_ne_zero _ hmu.ne_zero
  have hdegree := Polynomial.natDegree_le_of_dvd hdvd hdet
  rw [Polynomial.natDegree_pow] at hdegree
  simpa [Nat.mul_comm] using hdegree

end

end ProximityPrize.SubmissionLower.MatrixIrreducibleMultiplicity

#print axioms ProximityPrize.SubmissionLower.MatrixIrreducibleMultiplicity.pow_corank_dvd_det_of_irreducible
#print axioms ProximityPrize.SubmissionLower.MatrixIrreducibleMultiplicity.natDegree_mul_corank_le_natDegree_det
