import ProximityPrize.SubmissionLower.MovingFiberPackingProof6811S0C5
import ProximityPrize.SubmissionLower.MovingFiberPackingFast6811

namespace ProximityPrize.SubmissionLower.MovingFiberPackingProof6811.S0
open MovingFiberPackingCheck6811 MovingFiberPackingData6811.S0
set_option autoImplicit false
set_option Elab.async false
set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

theorem row31_1 : convolution own1.toList packed30.toList packed31.toList=true := by decide +kernel
theorem row31_2 : convolution own2.toList packed29.toList packed31.toList=true := by decide +kernel
theorem row31_3 : convolution own3.toList packed28.toList packed31.toList=true := by decide +kernel
theorem row31_4 : convolution own4.toList packed27.toList packed31.toList=true := by decide +kernel
theorem row31_5 : convolution own5.toList packed26.toList packed31.toList=true := by decide +kernel
theorem row31_6 : convolution own6.toList packed25.toList packed31.toList=true := by decide +kernel
theorem row31_7 : convolution own7.toList packed24.toList packed31.toList=true := by decide +kernel
theorem row31_8 : convolution own8.toList packed23.toList packed31.toList=true := by decide +kernel
theorem row31_9 : convolution own9.toList packed22.toList packed31.toList=true := by decide +kernel
theorem row31_10 : convolution own10.toList packed21.toList packed31.toList=true := by decide +kernel
theorem row31_11 : convolution own11.toList packed20.toList packed31.toList=true := by decide +kernel
theorem row31_12 : convolution own12.toList packed19.toList packed31.toList=true := by decide +kernel
theorem row31_13 : convolution own13.toList packed18.toList packed31.toList=true := by decide +kernel
theorem row31_14 : convolution own14.toList packed17.toList packed31.toList=true := by decide +kernel
theorem row31_15 : convolution own15.toList packed16.toList packed31.toList=true := by decide +kernel
theorem row31_16 : convolution own16.toList packed15.toList packed31.toList=true := by decide +kernel
theorem row31_17 : convolution own17.toList packed14.toList packed31.toList=true := by decide +kernel
theorem row31_18 : convolution own18.toList packed13.toList packed31.toList=true := by decide +kernel
theorem row31_19 : convolution own19.toList packed12.toList packed31.toList=true := by decide +kernel
theorem row31_20 : convolution own20.toList packed11.toList packed31.toList=true := by decide +kernel
theorem row31_21 : convolution own21.toList packed10.toList packed31.toList=true := by decide +kernel
theorem row31_22 : convolution own22.toList packed9.toList packed31.toList=true := by decide +kernel
theorem row31_23 : convolution own23.toList packed8.toList packed31.toList=true := by decide +kernel
theorem row31_24 : convolution own24.toList packed7.toList packed31.toList=true := by decide +kernel
theorem row31_25 : convolution own25.toList packed6.toList packed31.toList=true := by decide +kernel
theorem row31_26 : convolution own26.toList packed5.toList packed31.toList=true := by decide +kernel
theorem row31_27 : convolution own27.toList packed4.toList packed31.toList=true := by decide +kernel
theorem row31_28 : convolution own28.toList packed3.toList packed31.toList=true := by decide +kernel
theorem row31_29 : convolution own29.toList packed2.toList packed31.toList=true := by decide +kernel
theorem row31_30 : convolution own30.toList packed1.toList packed31.toList=true := by decide +kernel
theorem row31_31 : convolution own31.toList packed0.toList packed31.toList=true := by
  exact convolution_zero_right 164 _ _ (by decide +kernel) (by decide +kernel)
theorem row32_1 : convolution own1.toList packed31.toList packed32.toList=true := by decide +kernel
theorem row32_2 : convolution own2.toList packed30.toList packed32.toList=true := by decide +kernel
theorem row32_3 : convolution own3.toList packed29.toList packed32.toList=true := by decide +kernel
theorem row32_4 : convolution own4.toList packed28.toList packed32.toList=true := by decide +kernel
theorem row32_5 : convolution own5.toList packed27.toList packed32.toList=true := by decide +kernel
theorem row32_6 : convolution own6.toList packed26.toList packed32.toList=true := by decide +kernel
theorem row32_7 : convolution own7.toList packed25.toList packed32.toList=true := by decide +kernel
theorem row32_8 : convolution own8.toList packed24.toList packed32.toList=true := by decide +kernel
theorem row32_9 : convolution own9.toList packed23.toList packed32.toList=true := by decide +kernel
theorem row32_10 : convolution own10.toList packed22.toList packed32.toList=true := by decide +kernel
theorem row32_11 : convolution own11.toList packed21.toList packed32.toList=true := by decide +kernel
theorem row32_12 : convolution own12.toList packed20.toList packed32.toList=true := by decide +kernel
theorem row32_13 : convolution own13.toList packed19.toList packed32.toList=true := by decide +kernel
theorem row32_14 : convolution own14.toList packed18.toList packed32.toList=true := by decide +kernel
theorem row32_15 : convolution own15.toList packed17.toList packed32.toList=true := by decide +kernel
theorem row32_16 : convolution own16.toList packed16.toList packed32.toList=true := by decide +kernel
theorem row32_17 : convolution own17.toList packed15.toList packed32.toList=true := by decide +kernel
theorem row32_18 : convolution own18.toList packed14.toList packed32.toList=true := by decide +kernel
theorem row32_19 : convolution own19.toList packed13.toList packed32.toList=true := by decide +kernel
theorem row32_20 : convolution own20.toList packed12.toList packed32.toList=true := by decide +kernel
theorem row32_21 : convolution own21.toList packed11.toList packed32.toList=true := by decide +kernel
theorem row32_22 : convolution own22.toList packed10.toList packed32.toList=true := by decide +kernel
theorem row32_23 : convolution own23.toList packed9.toList packed32.toList=true := by decide +kernel
theorem row32_24 : convolution own24.toList packed8.toList packed32.toList=true := by decide +kernel
theorem row32_25 : convolution own25.toList packed7.toList packed32.toList=true := by decide +kernel
theorem row32_26 : convolution own26.toList packed6.toList packed32.toList=true := by decide +kernel
theorem row32_27 : convolution own27.toList packed5.toList packed32.toList=true := by decide +kernel
theorem row32_28 : convolution own28.toList packed4.toList packed32.toList=true := by decide +kernel
theorem row32_29 : convolution own29.toList packed3.toList packed32.toList=true := by decide +kernel
theorem row32_30 : convolution own30.toList packed2.toList packed32.toList=true := by decide +kernel
theorem row32_31 : convolution own31.toList packed1.toList packed32.toList=true := by decide +kernel
theorem row32_32 : convolution own32.toList packed0.toList packed32.toList=true := by
  exact convolution_zero_right 164 _ _ (by decide +kernel) (by decide +kernel)
theorem row33_1 : convolution own1.toList packed32.toList packed33.toList=true := by decide +kernel
theorem row33_2 : convolution own2.toList packed31.toList packed33.toList=true := by decide +kernel
theorem row33_3 : convolution own3.toList packed30.toList packed33.toList=true := by decide +kernel
theorem row33_4 : convolution own4.toList packed29.toList packed33.toList=true := by decide +kernel
theorem row33_5 : convolution own5.toList packed28.toList packed33.toList=true := by decide +kernel
theorem row33_6 : convolution own6.toList packed27.toList packed33.toList=true := by decide +kernel
theorem row33_7 : convolution own7.toList packed26.toList packed33.toList=true := by decide +kernel
theorem row33_8 : convolution own8.toList packed25.toList packed33.toList=true := by decide +kernel
theorem row33_9 : convolution own9.toList packed24.toList packed33.toList=true := by decide +kernel
theorem row33_10 : convolution own10.toList packed23.toList packed33.toList=true := by decide +kernel
theorem row33_11 : convolution own11.toList packed22.toList packed33.toList=true := by decide +kernel
theorem row33_12 : convolution own12.toList packed21.toList packed33.toList=true := by decide +kernel
theorem row33_13 : convolution own13.toList packed20.toList packed33.toList=true := by decide +kernel
theorem row33_14 : convolution own14.toList packed19.toList packed33.toList=true := by decide +kernel
theorem row33_15 : convolution own15.toList packed18.toList packed33.toList=true := by decide +kernel
theorem row33_16 : convolution own16.toList packed17.toList packed33.toList=true := by decide +kernel
theorem row33_17 : convolution own17.toList packed16.toList packed33.toList=true := by decide +kernel
theorem row33_18 : convolution own18.toList packed15.toList packed33.toList=true := by decide +kernel
theorem row33_19 : convolution own19.toList packed14.toList packed33.toList=true := by decide +kernel
theorem row33_20 : convolution own20.toList packed13.toList packed33.toList=true := by decide +kernel
theorem row33_21 : convolution own21.toList packed12.toList packed33.toList=true := by decide +kernel
theorem row33_22 : convolution own22.toList packed11.toList packed33.toList=true := by decide +kernel
theorem row33_23 : convolution own23.toList packed10.toList packed33.toList=true := by decide +kernel
theorem row33_24 : convolution own24.toList packed9.toList packed33.toList=true := by decide +kernel
theorem row33_25 : convolution own25.toList packed8.toList packed33.toList=true := by decide +kernel
theorem row33_26 : convolution own26.toList packed7.toList packed33.toList=true := by decide +kernel
theorem row33_27 : convolution own27.toList packed6.toList packed33.toList=true := by decide +kernel
theorem row33_28 : convolution own28.toList packed5.toList packed33.toList=true := by decide +kernel
theorem row33_29 : convolution own29.toList packed4.toList packed33.toList=true := by decide +kernel
theorem row33_30 : convolution own30.toList packed3.toList packed33.toList=true := by decide +kernel
theorem row33_31 : convolution own31.toList packed2.toList packed33.toList=true := by decide +kernel
theorem row33_32 : convolution own32.toList packed1.toList packed33.toList=true := by decide +kernel
theorem row33_33 : convolution own33.toList packed0.toList packed33.toList=true := by
  exact convolution_zero_right 164 _ _ (by decide +kernel) (by decide +kernel)
theorem row34_1 : convolution own1.toList packed33.toList packed34.toList=true := by decide +kernel
theorem row34_2 : convolution own2.toList packed32.toList packed34.toList=true := by decide +kernel
theorem row34_3 : convolution own3.toList packed31.toList packed34.toList=true := by decide +kernel
theorem row34_4 : convolution own4.toList packed30.toList packed34.toList=true := by decide +kernel
theorem row34_5 : convolution own5.toList packed29.toList packed34.toList=true := by decide +kernel
theorem row34_6 : convolution own6.toList packed28.toList packed34.toList=true := by decide +kernel
theorem row34_7 : convolution own7.toList packed27.toList packed34.toList=true := by decide +kernel
theorem row34_8 : convolution own8.toList packed26.toList packed34.toList=true := by decide +kernel
theorem row34_9 : convolution own9.toList packed25.toList packed34.toList=true := by decide +kernel
theorem row34_10 : convolution own10.toList packed24.toList packed34.toList=true := by decide +kernel
theorem row34_11 : convolution own11.toList packed23.toList packed34.toList=true := by decide +kernel
theorem row34_12 : convolution own12.toList packed22.toList packed34.toList=true := by decide +kernel
theorem row34_13 : convolution own13.toList packed21.toList packed34.toList=true := by decide +kernel
theorem row34_14 : convolution own14.toList packed20.toList packed34.toList=true := by decide +kernel
theorem row34_15 : convolution own15.toList packed19.toList packed34.toList=true := by decide +kernel
theorem row34_16 : convolution own16.toList packed18.toList packed34.toList=true := by decide +kernel
theorem row34_17 : convolution own17.toList packed17.toList packed34.toList=true := by decide +kernel
theorem row34_18 : convolution own18.toList packed16.toList packed34.toList=true := by decide +kernel
theorem row34_19 : convolution own19.toList packed15.toList packed34.toList=true := by decide +kernel
theorem row34_20 : convolution own20.toList packed14.toList packed34.toList=true := by decide +kernel
theorem row34_21 : convolution own21.toList packed13.toList packed34.toList=true := by decide +kernel
theorem row34_22 : convolution own22.toList packed12.toList packed34.toList=true := by decide +kernel
theorem row34_23 : convolution own23.toList packed11.toList packed34.toList=true := by decide +kernel
theorem row34_24 : convolution own24.toList packed10.toList packed34.toList=true := by decide +kernel
theorem row34_25 : convolution own25.toList packed9.toList packed34.toList=true := by decide +kernel
theorem row34_26 : convolution own26.toList packed8.toList packed34.toList=true := by decide +kernel
theorem row34_27 : convolution own27.toList packed7.toList packed34.toList=true := by decide +kernel
theorem row34_28 : convolution own28.toList packed6.toList packed34.toList=true := by decide +kernel
theorem row34_29 : convolution own29.toList packed5.toList packed34.toList=true := by decide +kernel
theorem row34_30 : convolution own30.toList packed4.toList packed34.toList=true := by decide +kernel
theorem row34_31 : convolution own31.toList packed3.toList packed34.toList=true := by decide +kernel
theorem row34_32 : convolution own32.toList packed2.toList packed34.toList=true := by decide +kernel
theorem row34_33 : convolution own33.toList packed1.toList packed34.toList=true := by decide +kernel
theorem row34_34 : convolution own34.toList packed0.toList packed34.toList=true := by
  exact convolution_zero_right 164 _ _ (by decide +kernel) (by decide +kernel)
theorem row35_1 : convolution own1.toList packed34.toList packed35.toList=true := by decide +kernel
theorem row35_2 : convolution own2.toList packed33.toList packed35.toList=true := by decide +kernel
theorem row35_3 : convolution own3.toList packed32.toList packed35.toList=true := by decide +kernel
theorem row35_4 : convolution own4.toList packed31.toList packed35.toList=true := by decide +kernel
theorem row35_5 : convolution own5.toList packed30.toList packed35.toList=true := by decide +kernel
theorem row35_6 : convolution own6.toList packed29.toList packed35.toList=true := by decide +kernel
theorem row35_7 : convolution own7.toList packed28.toList packed35.toList=true := by decide +kernel
theorem row35_8 : convolution own8.toList packed27.toList packed35.toList=true := by decide +kernel
theorem row35_9 : convolution own9.toList packed26.toList packed35.toList=true := by decide +kernel
theorem row35_10 : convolution own10.toList packed25.toList packed35.toList=true := by decide +kernel
theorem row35_11 : convolution own11.toList packed24.toList packed35.toList=true := by decide +kernel
theorem row35_12 : convolution own12.toList packed23.toList packed35.toList=true := by decide +kernel
theorem row35_13 : convolution own13.toList packed22.toList packed35.toList=true := by decide +kernel
theorem row35_14 : convolution own14.toList packed21.toList packed35.toList=true := by decide +kernel
theorem row35_15 : convolution own15.toList packed20.toList packed35.toList=true := by decide +kernel
theorem row35_16 : convolution own16.toList packed19.toList packed35.toList=true := by decide +kernel
theorem row35_17 : convolution own17.toList packed18.toList packed35.toList=true := by decide +kernel
theorem row35_18 : convolution own18.toList packed17.toList packed35.toList=true := by decide +kernel
theorem row35_19 : convolution own19.toList packed16.toList packed35.toList=true := by decide +kernel
theorem row35_20 : convolution own20.toList packed15.toList packed35.toList=true := by decide +kernel
theorem row35_21 : convolution own21.toList packed14.toList packed35.toList=true := by decide +kernel
theorem row35_22 : convolution own22.toList packed13.toList packed35.toList=true := by decide +kernel
theorem row35_23 : convolution own23.toList packed12.toList packed35.toList=true := by decide +kernel
theorem row35_24 : convolution own24.toList packed11.toList packed35.toList=true := by decide +kernel
theorem row35_25 : convolution own25.toList packed10.toList packed35.toList=true := by decide +kernel
theorem row35_26 : convolution own26.toList packed9.toList packed35.toList=true := by decide +kernel
theorem row35_27 : convolution own27.toList packed8.toList packed35.toList=true := by decide +kernel
theorem row35_28 : convolution own28.toList packed7.toList packed35.toList=true := by decide +kernel
theorem row35_29 : convolution own29.toList packed6.toList packed35.toList=true := by decide +kernel
theorem row35_30 : convolution own30.toList packed5.toList packed35.toList=true := by decide +kernel
theorem row35_31 : convolution own31.toList packed4.toList packed35.toList=true := by decide +kernel
theorem row35_32 : convolution own32.toList packed3.toList packed35.toList=true := by decide +kernel
theorem row35_33 : convolution own33.toList packed2.toList packed35.toList=true := by decide +kernel
theorem row35_34 : convolution own34.toList packed1.toList packed35.toList=true := by decide +kernel
theorem row35_35 : convolution own35.toList packed0.toList packed35.toList=true := by
  exact convolution_zero_right 164 _ _ (by decide +kernel) (by decide +kernel)
end ProximityPrize.SubmissionLower.MovingFiberPackingProof6811.S0
