import ProximityPrize.SubmissionLower.MovingFiberPackingProof6811S0C6
import ProximityPrize.SubmissionLower.MovingFiberPackingSemantics6811

namespace ProximityPrize.SubmissionLower.MovingFiberPackingSound6811.S0
open MovingFiberPackingCheck6811 MovingFiberPackingData6811.S0
open MovingFiberPackingProof6811.S0 MovingFiberPackingSemantics6811
set_option autoImplicit false
set_option Elab.async false
set_option maxRecDepth 100000
set_option maxHeartbeats 5000000

theorem own_size (r : Nat) (hr : 1≤r) (hR : r≤35) : (ownRow r).size=164-r := by
  interval_cases r <;> decide +kernel
theorem packed_size (r : Nat) (hR : r≤35) : (packedRow r).size=164-r := by
  interval_cases r <;> decide +kernel
theorem all_checks (R r : Nat) (hr : 1≤r) (hrr : r≤R) (hR : R≤35) :
    convolution (ownRow r).toList (packedRow (R-r)).toList (packedRow R).toList=true := by
  have hpos : 1≤R := hr.trans hrr
  interval_cases R
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row1_1
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row2_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row2_2
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row3_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row3_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row3_3
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row4_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row4_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row4_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row4_4
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row5_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row5_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row5_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row5_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row5_5
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row6_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row6_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row6_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row6_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row6_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row6_6
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row7_7
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row8_8
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row9_9
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row10_10
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row11_11
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row12_12
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row13_13
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row14_14
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row15_15
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row16_16
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row17_17
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row18_18
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row19_19
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row20_20
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row21_21
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row22_22
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row23_23
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row24_24
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row25_25
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row26_26
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row27_27
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row28_28
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row29_29
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_29
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row30_30
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_29
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_30
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row31_31
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_29
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_30
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_31
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row32_32
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_29
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_30
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_31
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_32
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row33_33
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_29
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_30
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_31
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_32
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_33
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row34_34
  · interval_cases r
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_1
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_2
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_3
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_4
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_5
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_6
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_7
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_8
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_9
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_10
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_11
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_12
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_13
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_14
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_15
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_16
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_17
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_18
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_19
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_20
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_21
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_22
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_23
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_24
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_25
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_26
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_27
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_28
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_29
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_30
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_31
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_32
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_33
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_34
    · simpa only [ownRow,packedRow,Nat.reduceSub] using row35_35
theorem bellman : AffineFactorAggregate6808.BellmanRows 35 163 own packed :=
  direct_bellman ownRow packedRow own_size packed_size all_checks
#print axioms bellman
end ProximityPrize.SubmissionLower.MovingFiberPackingSound6811.S0
