import ProximityPrize.SubmissionLower.MovingFiberPackingProof6811S0C4

namespace ProximityPrize.SubmissionLower.MovingFiberPackingProof6811.S0
open MovingFiberPackingCheck6811 MovingFiberPackingData6811.S0
set_option autoImplicit false
set_option Elab.async false
set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

theorem row26_1 : convolution own1.toList packed25.toList packed26.toList=true := by decide +kernel
theorem row26_2 : convolution own2.toList packed24.toList packed26.toList=true := by decide +kernel
theorem row26_3 : convolution own3.toList packed23.toList packed26.toList=true := by decide +kernel
theorem row26_4 : convolution own4.toList packed22.toList packed26.toList=true := by decide +kernel
theorem row26_5 : convolution own5.toList packed21.toList packed26.toList=true := by decide +kernel
theorem row26_6 : convolution own6.toList packed20.toList packed26.toList=true := by decide +kernel
theorem row26_7 : convolution own7.toList packed19.toList packed26.toList=true := by decide +kernel
theorem row26_8 : convolution own8.toList packed18.toList packed26.toList=true := by decide +kernel
theorem row26_9 : convolution own9.toList packed17.toList packed26.toList=true := by decide +kernel
theorem row26_10 : convolution own10.toList packed16.toList packed26.toList=true := by decide +kernel
theorem row26_11 : convolution own11.toList packed15.toList packed26.toList=true := by decide +kernel
theorem row26_12 : convolution own12.toList packed14.toList packed26.toList=true := by decide +kernel
theorem row26_13 : convolution own13.toList packed13.toList packed26.toList=true := by decide +kernel
theorem row26_14 : convolution own14.toList packed12.toList packed26.toList=true := by decide +kernel
theorem row26_15 : convolution own15.toList packed11.toList packed26.toList=true := by decide +kernel
theorem row26_16 : convolution own16.toList packed10.toList packed26.toList=true := by decide +kernel
theorem row26_17 : convolution own17.toList packed9.toList packed26.toList=true := by decide +kernel
theorem row26_18 : convolution own18.toList packed8.toList packed26.toList=true := by decide +kernel
theorem row26_19 : convolution own19.toList packed7.toList packed26.toList=true := by decide +kernel
theorem row26_20 : convolution own20.toList packed6.toList packed26.toList=true := by decide +kernel
theorem row26_21 : convolution own21.toList packed5.toList packed26.toList=true := by decide +kernel
theorem row26_22 : convolution own22.toList packed4.toList packed26.toList=true := by decide +kernel
theorem row26_23 : convolution own23.toList packed3.toList packed26.toList=true := by decide +kernel
theorem row26_24 : convolution own24.toList packed2.toList packed26.toList=true := by decide +kernel
theorem row26_25 : convolution own25.toList packed1.toList packed26.toList=true := by decide +kernel
theorem row26_26 : convolution own26.toList packed0.toList packed26.toList=true := by decide +kernel
theorem row27_1 : convolution own1.toList packed26.toList packed27.toList=true := by decide +kernel
theorem row27_2 : convolution own2.toList packed25.toList packed27.toList=true := by decide +kernel
theorem row27_3 : convolution own3.toList packed24.toList packed27.toList=true := by decide +kernel
theorem row27_4 : convolution own4.toList packed23.toList packed27.toList=true := by decide +kernel
theorem row27_5 : convolution own5.toList packed22.toList packed27.toList=true := by decide +kernel
theorem row27_6 : convolution own6.toList packed21.toList packed27.toList=true := by decide +kernel
theorem row27_7 : convolution own7.toList packed20.toList packed27.toList=true := by decide +kernel
theorem row27_8 : convolution own8.toList packed19.toList packed27.toList=true := by decide +kernel
theorem row27_9 : convolution own9.toList packed18.toList packed27.toList=true := by decide +kernel
theorem row27_10 : convolution own10.toList packed17.toList packed27.toList=true := by decide +kernel
theorem row27_11 : convolution own11.toList packed16.toList packed27.toList=true := by decide +kernel
theorem row27_12 : convolution own12.toList packed15.toList packed27.toList=true := by decide +kernel
theorem row27_13 : convolution own13.toList packed14.toList packed27.toList=true := by decide +kernel
theorem row27_14 : convolution own14.toList packed13.toList packed27.toList=true := by decide +kernel
theorem row27_15 : convolution own15.toList packed12.toList packed27.toList=true := by decide +kernel
theorem row27_16 : convolution own16.toList packed11.toList packed27.toList=true := by decide +kernel
theorem row27_17 : convolution own17.toList packed10.toList packed27.toList=true := by decide +kernel
theorem row27_18 : convolution own18.toList packed9.toList packed27.toList=true := by decide +kernel
theorem row27_19 : convolution own19.toList packed8.toList packed27.toList=true := by decide +kernel
theorem row27_20 : convolution own20.toList packed7.toList packed27.toList=true := by decide +kernel
theorem row27_21 : convolution own21.toList packed6.toList packed27.toList=true := by decide +kernel
theorem row27_22 : convolution own22.toList packed5.toList packed27.toList=true := by decide +kernel
theorem row27_23 : convolution own23.toList packed4.toList packed27.toList=true := by decide +kernel
theorem row27_24 : convolution own24.toList packed3.toList packed27.toList=true := by decide +kernel
theorem row27_25 : convolution own25.toList packed2.toList packed27.toList=true := by decide +kernel
theorem row27_26 : convolution own26.toList packed1.toList packed27.toList=true := by decide +kernel
theorem row27_27 : convolution own27.toList packed0.toList packed27.toList=true := by decide +kernel
theorem row28_1 : convolution own1.toList packed27.toList packed28.toList=true := by decide +kernel
theorem row28_2 : convolution own2.toList packed26.toList packed28.toList=true := by decide +kernel
theorem row28_3 : convolution own3.toList packed25.toList packed28.toList=true := by decide +kernel
theorem row28_4 : convolution own4.toList packed24.toList packed28.toList=true := by decide +kernel
theorem row28_5 : convolution own5.toList packed23.toList packed28.toList=true := by decide +kernel
theorem row28_6 : convolution own6.toList packed22.toList packed28.toList=true := by decide +kernel
theorem row28_7 : convolution own7.toList packed21.toList packed28.toList=true := by decide +kernel
theorem row28_8 : convolution own8.toList packed20.toList packed28.toList=true := by decide +kernel
theorem row28_9 : convolution own9.toList packed19.toList packed28.toList=true := by decide +kernel
theorem row28_10 : convolution own10.toList packed18.toList packed28.toList=true := by decide +kernel
theorem row28_11 : convolution own11.toList packed17.toList packed28.toList=true := by decide +kernel
theorem row28_12 : convolution own12.toList packed16.toList packed28.toList=true := by decide +kernel
theorem row28_13 : convolution own13.toList packed15.toList packed28.toList=true := by decide +kernel
theorem row28_14 : convolution own14.toList packed14.toList packed28.toList=true := by decide +kernel
theorem row28_15 : convolution own15.toList packed13.toList packed28.toList=true := by decide +kernel
theorem row28_16 : convolution own16.toList packed12.toList packed28.toList=true := by decide +kernel
theorem row28_17 : convolution own17.toList packed11.toList packed28.toList=true := by decide +kernel
theorem row28_18 : convolution own18.toList packed10.toList packed28.toList=true := by decide +kernel
theorem row28_19 : convolution own19.toList packed9.toList packed28.toList=true := by decide +kernel
theorem row28_20 : convolution own20.toList packed8.toList packed28.toList=true := by decide +kernel
theorem row28_21 : convolution own21.toList packed7.toList packed28.toList=true := by decide +kernel
theorem row28_22 : convolution own22.toList packed6.toList packed28.toList=true := by decide +kernel
theorem row28_23 : convolution own23.toList packed5.toList packed28.toList=true := by decide +kernel
theorem row28_24 : convolution own24.toList packed4.toList packed28.toList=true := by decide +kernel
theorem row28_25 : convolution own25.toList packed3.toList packed28.toList=true := by decide +kernel
theorem row28_26 : convolution own26.toList packed2.toList packed28.toList=true := by decide +kernel
theorem row28_27 : convolution own27.toList packed1.toList packed28.toList=true := by decide +kernel
theorem row28_28 : convolution own28.toList packed0.toList packed28.toList=true := by decide +kernel
theorem row29_1 : convolution own1.toList packed28.toList packed29.toList=true := by decide +kernel
theorem row29_2 : convolution own2.toList packed27.toList packed29.toList=true := by decide +kernel
theorem row29_3 : convolution own3.toList packed26.toList packed29.toList=true := by decide +kernel
theorem row29_4 : convolution own4.toList packed25.toList packed29.toList=true := by decide +kernel
theorem row29_5 : convolution own5.toList packed24.toList packed29.toList=true := by decide +kernel
theorem row29_6 : convolution own6.toList packed23.toList packed29.toList=true := by decide +kernel
theorem row29_7 : convolution own7.toList packed22.toList packed29.toList=true := by decide +kernel
theorem row29_8 : convolution own8.toList packed21.toList packed29.toList=true := by decide +kernel
theorem row29_9 : convolution own9.toList packed20.toList packed29.toList=true := by decide +kernel
theorem row29_10 : convolution own10.toList packed19.toList packed29.toList=true := by decide +kernel
theorem row29_11 : convolution own11.toList packed18.toList packed29.toList=true := by decide +kernel
theorem row29_12 : convolution own12.toList packed17.toList packed29.toList=true := by decide +kernel
theorem row29_13 : convolution own13.toList packed16.toList packed29.toList=true := by decide +kernel
theorem row29_14 : convolution own14.toList packed15.toList packed29.toList=true := by decide +kernel
theorem row29_15 : convolution own15.toList packed14.toList packed29.toList=true := by decide +kernel
theorem row29_16 : convolution own16.toList packed13.toList packed29.toList=true := by decide +kernel
theorem row29_17 : convolution own17.toList packed12.toList packed29.toList=true := by decide +kernel
theorem row29_18 : convolution own18.toList packed11.toList packed29.toList=true := by decide +kernel
theorem row29_19 : convolution own19.toList packed10.toList packed29.toList=true := by decide +kernel
theorem row29_20 : convolution own20.toList packed9.toList packed29.toList=true := by decide +kernel
theorem row29_21 : convolution own21.toList packed8.toList packed29.toList=true := by decide +kernel
theorem row29_22 : convolution own22.toList packed7.toList packed29.toList=true := by decide +kernel
theorem row29_23 : convolution own23.toList packed6.toList packed29.toList=true := by decide +kernel
theorem row29_24 : convolution own24.toList packed5.toList packed29.toList=true := by decide +kernel
theorem row29_25 : convolution own25.toList packed4.toList packed29.toList=true := by decide +kernel
theorem row29_26 : convolution own26.toList packed3.toList packed29.toList=true := by decide +kernel
theorem row29_27 : convolution own27.toList packed2.toList packed29.toList=true := by decide +kernel
theorem row29_28 : convolution own28.toList packed1.toList packed29.toList=true := by decide +kernel
theorem row29_29 : convolution own29.toList packed0.toList packed29.toList=true := by decide +kernel
theorem row30_1 : convolution own1.toList packed29.toList packed30.toList=true := by decide +kernel
theorem row30_2 : convolution own2.toList packed28.toList packed30.toList=true := by decide +kernel
theorem row30_3 : convolution own3.toList packed27.toList packed30.toList=true := by decide +kernel
theorem row30_4 : convolution own4.toList packed26.toList packed30.toList=true := by decide +kernel
theorem row30_5 : convolution own5.toList packed25.toList packed30.toList=true := by decide +kernel
theorem row30_6 : convolution own6.toList packed24.toList packed30.toList=true := by decide +kernel
theorem row30_7 : convolution own7.toList packed23.toList packed30.toList=true := by decide +kernel
theorem row30_8 : convolution own8.toList packed22.toList packed30.toList=true := by decide +kernel
theorem row30_9 : convolution own9.toList packed21.toList packed30.toList=true := by decide +kernel
theorem row30_10 : convolution own10.toList packed20.toList packed30.toList=true := by decide +kernel
theorem row30_11 : convolution own11.toList packed19.toList packed30.toList=true := by decide +kernel
theorem row30_12 : convolution own12.toList packed18.toList packed30.toList=true := by decide +kernel
theorem row30_13 : convolution own13.toList packed17.toList packed30.toList=true := by decide +kernel
theorem row30_14 : convolution own14.toList packed16.toList packed30.toList=true := by decide +kernel
theorem row30_15 : convolution own15.toList packed15.toList packed30.toList=true := by decide +kernel
theorem row30_16 : convolution own16.toList packed14.toList packed30.toList=true := by decide +kernel
theorem row30_17 : convolution own17.toList packed13.toList packed30.toList=true := by decide +kernel
theorem row30_18 : convolution own18.toList packed12.toList packed30.toList=true := by decide +kernel
theorem row30_19 : convolution own19.toList packed11.toList packed30.toList=true := by decide +kernel
theorem row30_20 : convolution own20.toList packed10.toList packed30.toList=true := by decide +kernel
theorem row30_21 : convolution own21.toList packed9.toList packed30.toList=true := by decide +kernel
theorem row30_22 : convolution own22.toList packed8.toList packed30.toList=true := by decide +kernel
theorem row30_23 : convolution own23.toList packed7.toList packed30.toList=true := by decide +kernel
theorem row30_24 : convolution own24.toList packed6.toList packed30.toList=true := by decide +kernel
theorem row30_25 : convolution own25.toList packed5.toList packed30.toList=true := by decide +kernel
theorem row30_26 : convolution own26.toList packed4.toList packed30.toList=true := by decide +kernel
theorem row30_27 : convolution own27.toList packed3.toList packed30.toList=true := by decide +kernel
theorem row30_28 : convolution own28.toList packed2.toList packed30.toList=true := by decide +kernel
theorem row30_29 : convolution own29.toList packed1.toList packed30.toList=true := by decide +kernel
theorem row30_30 : convolution own30.toList packed0.toList packed30.toList=true := by decide +kernel
end ProximityPrize.SubmissionLower.MovingFiberPackingProof6811.S0
