import ProximityPrize.SubmissionLower.MovingFiberPackingProof6811S0C3

namespace ProximityPrize.SubmissionLower.MovingFiberPackingProof6811.S0
open MovingFiberPackingCheck6811 MovingFiberPackingData6811.S0
set_option autoImplicit false
set_option Elab.async false
set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

theorem row21_1 : convolution own1.toList packed20.toList packed21.toList=true := by decide +kernel
theorem row21_2 : convolution own2.toList packed19.toList packed21.toList=true := by decide +kernel
theorem row21_3 : convolution own3.toList packed18.toList packed21.toList=true := by decide +kernel
theorem row21_4 : convolution own4.toList packed17.toList packed21.toList=true := by decide +kernel
theorem row21_5 : convolution own5.toList packed16.toList packed21.toList=true := by decide +kernel
theorem row21_6 : convolution own6.toList packed15.toList packed21.toList=true := by decide +kernel
theorem row21_7 : convolution own7.toList packed14.toList packed21.toList=true := by decide +kernel
theorem row21_8 : convolution own8.toList packed13.toList packed21.toList=true := by decide +kernel
theorem row21_9 : convolution own9.toList packed12.toList packed21.toList=true := by decide +kernel
theorem row21_10 : convolution own10.toList packed11.toList packed21.toList=true := by decide +kernel
theorem row21_11 : convolution own11.toList packed10.toList packed21.toList=true := by decide +kernel
theorem row21_12 : convolution own12.toList packed9.toList packed21.toList=true := by decide +kernel
theorem row21_13 : convolution own13.toList packed8.toList packed21.toList=true := by decide +kernel
theorem row21_14 : convolution own14.toList packed7.toList packed21.toList=true := by decide +kernel
theorem row21_15 : convolution own15.toList packed6.toList packed21.toList=true := by decide +kernel
theorem row21_16 : convolution own16.toList packed5.toList packed21.toList=true := by decide +kernel
theorem row21_17 : convolution own17.toList packed4.toList packed21.toList=true := by decide +kernel
theorem row21_18 : convolution own18.toList packed3.toList packed21.toList=true := by decide +kernel
theorem row21_19 : convolution own19.toList packed2.toList packed21.toList=true := by decide +kernel
theorem row21_20 : convolution own20.toList packed1.toList packed21.toList=true := by decide +kernel
theorem row21_21 : convolution own21.toList packed0.toList packed21.toList=true := by decide +kernel
theorem row22_1 : convolution own1.toList packed21.toList packed22.toList=true := by decide +kernel
theorem row22_2 : convolution own2.toList packed20.toList packed22.toList=true := by decide +kernel
theorem row22_3 : convolution own3.toList packed19.toList packed22.toList=true := by decide +kernel
theorem row22_4 : convolution own4.toList packed18.toList packed22.toList=true := by decide +kernel
theorem row22_5 : convolution own5.toList packed17.toList packed22.toList=true := by decide +kernel
theorem row22_6 : convolution own6.toList packed16.toList packed22.toList=true := by decide +kernel
theorem row22_7 : convolution own7.toList packed15.toList packed22.toList=true := by decide +kernel
theorem row22_8 : convolution own8.toList packed14.toList packed22.toList=true := by decide +kernel
theorem row22_9 : convolution own9.toList packed13.toList packed22.toList=true := by decide +kernel
theorem row22_10 : convolution own10.toList packed12.toList packed22.toList=true := by decide +kernel
theorem row22_11 : convolution own11.toList packed11.toList packed22.toList=true := by decide +kernel
theorem row22_12 : convolution own12.toList packed10.toList packed22.toList=true := by decide +kernel
theorem row22_13 : convolution own13.toList packed9.toList packed22.toList=true := by decide +kernel
theorem row22_14 : convolution own14.toList packed8.toList packed22.toList=true := by decide +kernel
theorem row22_15 : convolution own15.toList packed7.toList packed22.toList=true := by decide +kernel
theorem row22_16 : convolution own16.toList packed6.toList packed22.toList=true := by decide +kernel
theorem row22_17 : convolution own17.toList packed5.toList packed22.toList=true := by decide +kernel
theorem row22_18 : convolution own18.toList packed4.toList packed22.toList=true := by decide +kernel
theorem row22_19 : convolution own19.toList packed3.toList packed22.toList=true := by decide +kernel
theorem row22_20 : convolution own20.toList packed2.toList packed22.toList=true := by decide +kernel
theorem row22_21 : convolution own21.toList packed1.toList packed22.toList=true := by decide +kernel
theorem row22_22 : convolution own22.toList packed0.toList packed22.toList=true := by decide +kernel
theorem row23_1 : convolution own1.toList packed22.toList packed23.toList=true := by decide +kernel
theorem row23_2 : convolution own2.toList packed21.toList packed23.toList=true := by decide +kernel
theorem row23_3 : convolution own3.toList packed20.toList packed23.toList=true := by decide +kernel
theorem row23_4 : convolution own4.toList packed19.toList packed23.toList=true := by decide +kernel
theorem row23_5 : convolution own5.toList packed18.toList packed23.toList=true := by decide +kernel
theorem row23_6 : convolution own6.toList packed17.toList packed23.toList=true := by decide +kernel
theorem row23_7 : convolution own7.toList packed16.toList packed23.toList=true := by decide +kernel
theorem row23_8 : convolution own8.toList packed15.toList packed23.toList=true := by decide +kernel
theorem row23_9 : convolution own9.toList packed14.toList packed23.toList=true := by decide +kernel
theorem row23_10 : convolution own10.toList packed13.toList packed23.toList=true := by decide +kernel
theorem row23_11 : convolution own11.toList packed12.toList packed23.toList=true := by decide +kernel
theorem row23_12 : convolution own12.toList packed11.toList packed23.toList=true := by decide +kernel
theorem row23_13 : convolution own13.toList packed10.toList packed23.toList=true := by decide +kernel
theorem row23_14 : convolution own14.toList packed9.toList packed23.toList=true := by decide +kernel
theorem row23_15 : convolution own15.toList packed8.toList packed23.toList=true := by decide +kernel
theorem row23_16 : convolution own16.toList packed7.toList packed23.toList=true := by decide +kernel
theorem row23_17 : convolution own17.toList packed6.toList packed23.toList=true := by decide +kernel
theorem row23_18 : convolution own18.toList packed5.toList packed23.toList=true := by decide +kernel
theorem row23_19 : convolution own19.toList packed4.toList packed23.toList=true := by decide +kernel
theorem row23_20 : convolution own20.toList packed3.toList packed23.toList=true := by decide +kernel
theorem row23_21 : convolution own21.toList packed2.toList packed23.toList=true := by decide +kernel
theorem row23_22 : convolution own22.toList packed1.toList packed23.toList=true := by decide +kernel
theorem row23_23 : convolution own23.toList packed0.toList packed23.toList=true := by decide +kernel
theorem row24_1 : convolution own1.toList packed23.toList packed24.toList=true := by decide +kernel
theorem row24_2 : convolution own2.toList packed22.toList packed24.toList=true := by decide +kernel
theorem row24_3 : convolution own3.toList packed21.toList packed24.toList=true := by decide +kernel
theorem row24_4 : convolution own4.toList packed20.toList packed24.toList=true := by decide +kernel
theorem row24_5 : convolution own5.toList packed19.toList packed24.toList=true := by decide +kernel
theorem row24_6 : convolution own6.toList packed18.toList packed24.toList=true := by decide +kernel
theorem row24_7 : convolution own7.toList packed17.toList packed24.toList=true := by decide +kernel
theorem row24_8 : convolution own8.toList packed16.toList packed24.toList=true := by decide +kernel
theorem row24_9 : convolution own9.toList packed15.toList packed24.toList=true := by decide +kernel
theorem row24_10 : convolution own10.toList packed14.toList packed24.toList=true := by decide +kernel
theorem row24_11 : convolution own11.toList packed13.toList packed24.toList=true := by decide +kernel
theorem row24_12 : convolution own12.toList packed12.toList packed24.toList=true := by decide +kernel
theorem row24_13 : convolution own13.toList packed11.toList packed24.toList=true := by decide +kernel
theorem row24_14 : convolution own14.toList packed10.toList packed24.toList=true := by decide +kernel
theorem row24_15 : convolution own15.toList packed9.toList packed24.toList=true := by decide +kernel
theorem row24_16 : convolution own16.toList packed8.toList packed24.toList=true := by decide +kernel
theorem row24_17 : convolution own17.toList packed7.toList packed24.toList=true := by decide +kernel
theorem row24_18 : convolution own18.toList packed6.toList packed24.toList=true := by decide +kernel
theorem row24_19 : convolution own19.toList packed5.toList packed24.toList=true := by decide +kernel
theorem row24_20 : convolution own20.toList packed4.toList packed24.toList=true := by decide +kernel
theorem row24_21 : convolution own21.toList packed3.toList packed24.toList=true := by decide +kernel
theorem row24_22 : convolution own22.toList packed2.toList packed24.toList=true := by decide +kernel
theorem row24_23 : convolution own23.toList packed1.toList packed24.toList=true := by decide +kernel
theorem row24_24 : convolution own24.toList packed0.toList packed24.toList=true := by decide +kernel
theorem row25_1 : convolution own1.toList packed24.toList packed25.toList=true := by decide +kernel
theorem row25_2 : convolution own2.toList packed23.toList packed25.toList=true := by decide +kernel
theorem row25_3 : convolution own3.toList packed22.toList packed25.toList=true := by decide +kernel
theorem row25_4 : convolution own4.toList packed21.toList packed25.toList=true := by decide +kernel
theorem row25_5 : convolution own5.toList packed20.toList packed25.toList=true := by decide +kernel
theorem row25_6 : convolution own6.toList packed19.toList packed25.toList=true := by decide +kernel
theorem row25_7 : convolution own7.toList packed18.toList packed25.toList=true := by decide +kernel
theorem row25_8 : convolution own8.toList packed17.toList packed25.toList=true := by decide +kernel
theorem row25_9 : convolution own9.toList packed16.toList packed25.toList=true := by decide +kernel
theorem row25_10 : convolution own10.toList packed15.toList packed25.toList=true := by decide +kernel
theorem row25_11 : convolution own11.toList packed14.toList packed25.toList=true := by decide +kernel
theorem row25_12 : convolution own12.toList packed13.toList packed25.toList=true := by decide +kernel
theorem row25_13 : convolution own13.toList packed12.toList packed25.toList=true := by decide +kernel
theorem row25_14 : convolution own14.toList packed11.toList packed25.toList=true := by decide +kernel
theorem row25_15 : convolution own15.toList packed10.toList packed25.toList=true := by decide +kernel
theorem row25_16 : convolution own16.toList packed9.toList packed25.toList=true := by decide +kernel
theorem row25_17 : convolution own17.toList packed8.toList packed25.toList=true := by decide +kernel
theorem row25_18 : convolution own18.toList packed7.toList packed25.toList=true := by decide +kernel
theorem row25_19 : convolution own19.toList packed6.toList packed25.toList=true := by decide +kernel
theorem row25_20 : convolution own20.toList packed5.toList packed25.toList=true := by decide +kernel
theorem row25_21 : convolution own21.toList packed4.toList packed25.toList=true := by decide +kernel
theorem row25_22 : convolution own22.toList packed3.toList packed25.toList=true := by decide +kernel
theorem row25_23 : convolution own23.toList packed2.toList packed25.toList=true := by decide +kernel
theorem row25_24 : convolution own24.toList packed1.toList packed25.toList=true := by decide +kernel
theorem row25_25 : convolution own25.toList packed0.toList packed25.toList=true := by decide +kernel
end ProximityPrize.SubmissionLower.MovingFiberPackingProof6811.S0
