import ProximityPrize.Benchmark.TargetLower
import ProximityPrize.SubmissionLower.PlaneResultantPointCount

/-!
# Full field degree from a specialized Sylvester corank

This replaces the distinct-root/embedding argument by one actual power-basis
evaluation.  It therefore bounds the full relative degree, including the
purely inseparable part.
-/

namespace ProximityPrize.SubmissionLower.PlaneSylvesterFieldDegree

open PlaneResultantPointCount

noncomputable section

variable {K E : Type*} [Field K] [Field E] [Algebra K E]

theorem finrank_degreeLT_poly (N : ℕ) :
    Module.finrank K (Polynomial.degreeLT K N) = N := by
  simpa using Module.finrank_eq_card_basis (Polynomial.degreeLT.basis K N)

theorem sylvester_rank_eq_finrank_range_poly
    (p q : Polynomial K) (m n : ℕ)
    (hp : p.natDegree ≤ m) (hq : q.natDegree ≤ n) :
    (Polynomial.sylvester p q m n).rank =
      Module.finrank K (LinearMap.range (Polynomial.sylvesterMap p q hp hq)) := by
  have hmatrix : LinearMap.toMatrix
      (Polynomial.degreeLT.basisProd K m n)
      (Polynomial.degreeLT.basis K (m + n))
      (Polynomial.sylvesterMap p q hp hq) = Polynomial.sylvester p q m n :=
    Polynomial.toMatrix_sylvesterMap' p q hp hq
  rw [Matrix.rank_eq_finrank_range_toLin _
    (Polynomial.degreeLT.basis K (m + n)) (Polynomial.degreeLT.basisProd K m n)]
  rw [← hmatrix, Matrix.toLin_toMatrix]

/-- Evaluation on a bounded polynomial space into a field extension. -/
def evaluationToExtension (N : ℕ) (y : E) :
    Polynomial.degreeLT K N →ₗ[K] E where
  toFun P := Polynomial.eval₂ (algebraMap K E) y (P : Polynomial K)
  map_add' P Q := by simp
  map_smul' c P := by simp [Algebra.smul_def]

/-- A power basis generated by `y`, whose dimension fits in `N`, makes the
bounded evaluation map surjective. -/
theorem evaluationToExtension_surjective
    (N : ℕ) (y : E) (pb : PowerBasis K E) (hgen : pb.gen = y)
    (hdim : pb.dim ≤ N) :
    Function.Surjective (evaluationToExtension (K := K) (E := E) N y) := by
  intro z
  obtain ⟨f, hfdeg, hz⟩ := pb.exists_eq_aeval z
  have hfsmall : f.degree < (N : WithBot ℕ) := by
    by_cases hf : f = 0
    · simp [hf]
    · rw [Polynomial.degree_eq_natDegree hf]
      exact_mod_cast hfdeg.trans_le hdim
  refine ⟨⟨f, Polynomial.mem_degreeLT.mpr hfsmall⟩, ?_⟩
  change Polynomial.eval₂ (algebraMap K E) y f = z
  rw [← hgen]
  exact hz.symm

/-- If two bounded polynomials vanish at a power-basis generator, the full
extension degree is at most the specialized Sylvester corank. -/
theorem finrank_le_sylvester_corank
    [FiniteDimensional K E]
    (p q : Polynomial K) (m n : ℕ) (y : E) (pb : PowerBasis K E)
    (hgen : pb.gen = y)
    (hp : p.natDegree ≤ m) (hq : q.natDegree ≤ n)
    (hdim : pb.dim ≤ m + n)
    (hpy : Polynomial.eval₂ (algebraMap K E) y p = 0)
    (hqy : Polynomial.eval₂ (algebraMap K E) y q = 0) :
    Module.finrank K E ≤
      m + n - (Polynomial.sylvester p q m n).rank := by
  let Eval := evaluationToExtension (K := K) (E := E) (m + n) y
  let Syl := Polynomial.sylvesterMap p q hp hq
  have hsurj : Function.Surjective Eval :=
    evaluationToExtension_surjective (K := K) (E := E) (m + n) y pb hgen hdim
  have hcontain : LinearMap.range Syl ≤ LinearMap.ker Eval := by
    rintro P ⟨input, rfl⟩
    rw [LinearMap.mem_ker]
    change Polynomial.eval₂ (algebraMap K E) y
      (p * (input.2 : Polynomial K) + q * (input.1 : Polynomial K)) = 0
    simp only [Polynomial.eval₂_add, Polynomial.eval₂_mul, hpy, hqy,
      zero_mul, zero_add]
  have hevalrank : Module.finrank K (LinearMap.range Eval) = Module.finrank K E := by
    rw [LinearMap.range_eq_top.mpr hsurj, finrank_top]
  have hnull := LinearMap.finrank_range_add_finrank_ker Eval
  have hfin : Module.finrank K (Polynomial.degreeLT K (m + n)) = m + n :=
    finrank_degreeLT_poly (K := K) (m + n)
  rw [hevalrank, hfin] at hnull
  have hmono := Submodule.finrank_mono hcontain
  have hmatrix := sylvester_rank_eq_finrank_range_poly p q m n hp hq
  change (Polynomial.sylvester p q m n).rank =
    Module.finrank K (LinearMap.range Syl) at hmatrix
  omega

section Family

variable {I : Type*} [Fintype I]
variable (E : I → Type*) [∀ i, Field (E i)] [∀ i, Algebra K (E i)]

def evaluationToFamily (N : ℕ) (y : ∀ i, E i) :
    Polynomial.degreeLT K N →ₗ[K] (∀ i, E i) :=
  LinearMap.pi fun i => evaluationToExtension (K := K) (E := E i) N (y i)

/-- Polynomial CRT makes simultaneous bounded evaluation onto distinct
power-basis components surjective. -/
theorem evaluationToFamily_surjective_of_powerBases
    [DecidableEq I]
    (N : ℕ) (y : ∀ i, E i) (pb : ∀ i, PowerBasis K (E i))
    (hgen : ∀ i, (pb i).gen = y i)
    (hkernels : Function.Injective (fun i => RingHom.ker
      (Polynomial.eval₂RingHom (algebraMap K (E i)) (y i))))
    (hsum : (∑ i, (pb i).dim) ≤ N) :
    Function.Surjective (evaluationToFamily (K := K) E N y) := by
  classical
  let f : ∀ i, Polynomial K →+* E i := fun i =>
    Polynomial.eval₂RingHom (algebraMap K (E i)) (y i)
  have hfsurj (i : I) : Function.Surjective (f i) := by
    intro z
    obtain ⟨g, _, hg⟩ := (pb i).exists_eq_aeval z
    refine ⟨g, ?_⟩
    change (Polynomial.aeval (y i)) g = z
    rw [← hgen i]
    exact hg.symm
  have hcoprime : Pairwise (fun i j => IsCoprime (RingHom.ker (f i))
      (RingHom.ker (f j))) := by
    intro i j hij
    letI : (RingHom.ker (f i)).IsMaximal :=
      RingHom.ker_isMaximal_of_surjective (f i) (hfsurj i)
    letI : (RingHom.ker (f j)).IsMaximal :=
      RingHom.ker_isMaximal_of_surjective (f j) (hfsurj j)
    apply Ideal.isCoprime_of_isMaximal
    intro heq
    exact hij (hkernels heq)
  intro values
  let residues : ∀ i, Polynomial K ⧸ RingHom.ker (f i) := fun i =>
    (RingHom.quotientKerEquivOfSurjective (hfsurj i)).symm (values i)
  obtain ⟨r, hr⟩ := Ideal.pi_quotient_surjective hcoprime residues
  have hreval (i : I) : f i r = values i := by
    calc
      f i r = RingHom.quotientKerEquivOfSurjective (hfsurj i)
          (Ideal.Quotient.mk (RingHom.ker (f i)) r) := by
        rw [RingHom.quotientKerEquivOfSurjective_apply_mk]
      _ = RingHom.quotientKerEquivOfSurjective (hfsurj i) (residues i) := by
        rw [hr i]
      _ = values i := (RingHom.quotientKerEquivOfSurjective (hfsurj i)).apply_symm_apply _
  by_cases hI : Nonempty I
  · let modulus : Polynomial K := ∏ i, minpoly K (y i)
    have hyint (i : I) : IsIntegral K (y i) := by
      rw [← hgen i]
      exact (pb i).isIntegral_gen
    have hmonic : modulus.Monic := by
      apply Polynomial.monic_prod_of_monic
      intro i _
      exact minpoly.monic (hyint i)
    have hmodulus_ne_one : modulus ≠ 1 := by
      haveI := hI
      have hdeg : modulus.natDegree = ∑ i, (pb i).dim := by
        rw [Polynomial.natDegree_prod_of_monic
          (s := Finset.univ) (f := fun i => minpoly K (y i))
          (fun i _ => minpoly.monic (hyint i))]
        apply Finset.sum_congr rfl
        intro i _
        simpa [hgen i] using (pb i).natDegree_minpoly
      intro hone
      have hz : modulus.natDegree = 0 := by rw [hone]; simp
      rw [hdeg] at hz
      have hpos : 0 < ∑ i, (pb i).dim :=
        Finset.sum_pos (fun i _ => (pb i).dim_pos) Finset.univ_nonempty
      omega
    let small := r %ₘ modulus
    have hsmallNat : small.natDegree < N := by
      have hlt := Polynomial.natDegree_modByMonic_lt r hmonic hmodulus_ne_one
      have hdeg : modulus.natDegree = ∑ i, (pb i).dim := by
        rw [Polynomial.natDegree_prod_of_monic
          (s := Finset.univ) (f := fun i => minpoly K (y i))
          (fun i _ => minpoly.monic (hyint i))]
        apply Finset.sum_congr rfl
        intro i _
        simpa [hgen i] using (pb i).natDegree_minpoly
      rw [hdeg] at hlt
      exact hlt.trans_le hsum
    have hsmallDegree : small.degree < (N : WithBot ℕ) := by
      by_cases hz : small = 0
      · simp [hz]
      · rw [Polynomial.degree_eq_natDegree hz]
        exact_mod_cast hsmallNat
    refine ⟨⟨small, Polynomial.mem_degreeLT.mpr hsmallDegree⟩, ?_⟩
    funext i
    change f i small = values i
    have hmodzero : f i modulus = 0 := by
      change (Polynomial.aeval (y i)) modulus = 0
      rw [← minpoly.dvd_iff]
      exact Finset.dvd_prod_of_mem (fun j => minpoly K (y j)) (Finset.mem_univ i)
    change f i (r %ₘ modulus) = values i
    rw [Polynomial.modByMonic_eq_sub_mul_div, map_sub, map_mul, hmodzero,
      zero_mul, sub_zero, hreval]
  · letI : IsEmpty I := ⟨fun i => hI ⟨i⟩⟩
    refine ⟨0, ?_⟩
    funext i
    exact isEmptyElim i

/-- A simultaneous bounded evaluation onto every component field charges
the sum of full field degrees to one specialized Sylvester corank. -/
theorem sum_finrank_le_sylvester_corank_of_surjective
    [∀ i, FiniteDimensional K (E i)]
    (p q : Polynomial K) (m n : ℕ) (y : ∀ i, E i)
    (hp : p.natDegree ≤ m) (hq : q.natDegree ≤ n)
    (hsurj : Function.Surjective
      (evaluationToFamily (K := K) E (m + n) y))
    (hpy : ∀ i, Polynomial.eval₂ (algebraMap K (E i)) (y i) p = 0)
    (hqy : ∀ i, Polynomial.eval₂ (algebraMap K (E i)) (y i) q = 0) :
    (∑ i, Module.finrank K (E i)) ≤
      m + n - (Polynomial.sylvester p q m n).rank := by
  let Eval := evaluationToFamily (K := K) E (m + n) y
  let Syl := Polynomial.sylvesterMap p q hp hq
  have hcontain : LinearMap.range Syl ≤ LinearMap.ker Eval := by
    rintro P ⟨input, rfl⟩
    rw [LinearMap.mem_ker]
    funext i
    change Polynomial.eval₂ (algebraMap K (E i)) (y i)
      (p * (input.2 : Polynomial K) + q * (input.1 : Polynomial K)) = 0
    simp only [Polynomial.eval₂_add, Polynomial.eval₂_mul, hpy i, hqy i,
      zero_mul, zero_add]
  have hevalrank : Module.finrank K (LinearMap.range Eval) =
      ∑ i, Module.finrank K (E i) := by
    rw [LinearMap.range_eq_top.mpr hsurj, finrank_top,
      Module.finrank_pi_fintype]
  have hnull := LinearMap.finrank_range_add_finrank_ker Eval
  have hfin : Module.finrank K (Polynomial.degreeLT K (m + n)) = m + n :=
    finrank_degreeLT_poly (K := K) (m + n)
  rw [hevalrank, hfin] at hnull
  have hmono := Submodule.finrank_mono hcontain
  have hmatrix := sylvester_rank_eq_finrank_range_poly p q m n hp hq
  change (Polynomial.sylvester p q m n).rank =
    Module.finrank K (LinearMap.range Syl) at hmatrix
  omega

theorem sum_finrank_le_sylvester_corank_of_powerBases
    [DecidableEq I] [∀ i, FiniteDimensional K (E i)]
    (p q : Polynomial K) (m n : ℕ) (y : ∀ i, E i)
    (pb : ∀ i, PowerBasis K (E i)) (hgen : ∀ i, (pb i).gen = y i)
    (hp : p.natDegree ≤ m) (hq : q.natDegree ≤ n)
    (hkernels : Function.Injective (fun i => RingHom.ker
      (Polynomial.eval₂RingHom (algebraMap K (E i)) (y i))))
    (hsum : (∑ i, (pb i).dim) ≤ m + n)
    (hpy : ∀ i, Polynomial.eval₂ (algebraMap K (E i)) (y i) p = 0)
    (hqy : ∀ i, Polynomial.eval₂ (algebraMap K (E i)) (y i) q = 0) :
    (∑ i, Module.finrank K (E i)) ≤
      m + n - (Polynomial.sylvester p q m n).rank := by
  apply sum_finrank_le_sylvester_corank_of_surjective E p q m n y hp hq
  · exact evaluationToFamily_surjective_of_powerBases E (m + n) y pb hgen
      hkernels hsum
  · exact hpy
  · exact hqy

end Family

end

end ProximityPrize.SubmissionLower.PlaneSylvesterFieldDegree

#print axioms ProximityPrize.SubmissionLower.PlaneSylvesterFieldDegree.evaluationToExtension_surjective
#print axioms ProximityPrize.SubmissionLower.PlaneSylvesterFieldDegree.finrank_le_sylvester_corank
#print axioms ProximityPrize.SubmissionLower.PlaneSylvesterFieldDegree.sum_finrank_le_sylvester_corank_of_surjective
#print axioms ProximityPrize.SubmissionLower.PlaneSylvesterFieldDegree.sum_finrank_le_sylvester_corank_of_powerBases
