import ProximityPrize.Benchmark.TargetLower
import ProximityPrize.SubmissionLower.NormValuation
import ProximityPrize.SubmissionLower.LocalMathlib_FieldTheory_RatFunc_Valuation




/-!
# An actual projective-line product formula

Model label: gpt-5.

Finite places are the actual height-one ideals generated by monic
irreducible polynomials. Their orders are the pinned discrete valuations,
not assigned exponents. Infinity uses RatFunc.inftyValuation. Polynomial
factorization proves the weighted finite sum plus the infinity order is
zero. Every height-one ideal is represented, and all nonzero finite
orders belong to the explicitly constructed finite factor support.

This file does not assume a product-formula structure. It proves the
base-field identity needed before transporting norms to a fixed curve's
finite and infinite normalization charts.
-/

namespace ProximityPrize.SubmissionLower.RatFuncProductFormula

open scoped BigOperators Classical
open UniqueFactorizationMonoid IsDedekindDomain

noncomputable section

variable (K : Type*) [Field K]

local instance : DecidableEq K := Classical.decEq K

/-- The actual finite place of a nonconstant irreducible polynomial. -/
def primePlace (p : Polynomial K) (hp : Irreducible p) :
    HeightOneSpectrum (Polynomial K) :=
  ⟨Ideal.span {p}, (Ideal.span_singleton_prime hp.ne_zero).mpr hp.prime,
    by simpa using hp.ne_zero⟩

/-- Canonical transport to the fraction-ring type used by NormValuation. -/
def asFraction (x : RatFunc K) : FractionRing (Polynomial K) :=
  RatFunc.toFractionRingAlgEquiv K (Polynomial K) x

def finiteOrder (p : Polynomial K) (hp : Irreducible p) (x : RatFunc K) : ℤ :=
  NormValuation.orderAt (primePlace K p hp) (asFraction K x)

def infinityOrder (x : RatFunc K) : ℤ :=
  -(RatFunc.inftyValuation K x).log

/-- Actual finite-place orders equal the numerator-minus-denominator
factor counts for monic irreducible polynomial representatives. -/
theorem finiteOrder_eq_factorCounts
    (p : Polynomial K) (hp : Irreducible p) (hmonic : p.Monic)
    (x : RatFunc K) (hx : x ≠ 0) :
    finiteOrder K p hp x =
      ((normalizedFactors x.num).count p : ℤ) -
        ((normalizedFactors x.denom).count p : ℤ) := by
  classical
  have hrepr : asFraction K x =
      algebraMap (Polynomial K) (FractionRing (Polynomial K)) x.num /
        algebraMap (Polynomial K) (FractionRing (Polynomial K)) x.denom := by
    have h := congrArg (RatFunc.toFractionRingAlgEquiv K (Polynomial K))
      (RatFunc.num_div_denom x)
    simpa only [asFraction, map_div₀, AlgEquiv.commutes] using h.symm
  rw [finiteOrder, hrepr,
    NormValuation.orderAt_div _ _ _ (by simp [RatFunc.num_ne_zero hx])
      (by simp [x.denom_ne_zero]),
    NormValuation.orderAt_algebraMap _ x.num (RatFunc.num_ne_zero hx),
    NormValuation.orderAt_algebraMap _ x.denom x.denom_ne_zero]
  change ((normalizedFactors (Ideal.span {x.num})).count (Ideal.span {p}) : ℤ) -
      ((normalizedFactors (Ideal.span {x.denom})).count (Ideal.span {p}) : ℤ) = _
  rw [Ideal.count_span_normalizedFactors_eq (RatFunc.num_ne_zero hx) hp.prime,
    Ideal.count_span_normalizedFactors_eq x.denom_ne_zero hp.prime,
    hmonic.normalize_eq_self]

theorem infinityOrder_eq_neg_intDegree (x : RatFunc K) (hx : x ≠ 0) :
    infinityOrder K x = -x.intDegree := by
  rw [infinityOrder, RatFunc.inftyValuation_apply,
    RatFunc.inftyValuation_of_nonzero K hx, WithZero.log_exp]

/-- Actual coverage of every finite height-one place by a monic
irreducible representative; this is not a completeness assumption. -/
theorem exists_monic_primePlace (v : HeightOneSpectrum (Polynomial K)) :
    ∃ p : Polynomial K, ∃ hp : Irreducible p,
      p.Monic ∧ primePlace K p hp = v := by
  classical
  let g := Submodule.IsPrincipal.generator v.asIdeal
  have hg : Prime g := Ideal.prime_generator_of_prime v.prime
  have hp : Irreducible (normalize g) :=
    (normalize_associated g).irreducible_iff.mpr hg.irreducible
  refine ⟨normalize g, hp,
    Polynomial.monic_normalize (R := K) (p := g) hg.ne_zero, ?_⟩
  apply HeightOneSpectrum.ext_iff.mpr
  change Ideal.span {normalize g} = v.asIdeal
  calc
    _ = Ideal.span {g} :=
      Ideal.span_singleton_eq_span_singleton.mpr (normalize_associated g)
    _ = _ := Ideal.span_singleton_generator v.asIdeal

/-- Monic representatives do not count the same finite place twice. -/
theorem primePlace_injective
    (p q : Polynomial K) (hp : Irreducible p) (hq : Irreducible q)
    (hpm : p.Monic) (hqm : q.Monic)
    (h : primePlace K p hp = primePlace K q hq) : p = q := by
  have hassoc : Associated p q := Ideal.span_singleton_eq_span_singleton.mp
    (congrArg HeightOneSpectrum.asIdeal h)
  exact hassoc.eq_of_normalized hpm.normalize_eq_self hqm.normalize_eq_self

theorem sum_factor_degrees (p : Polynomial K) (hp : p ≠ 0) :
    ((normalizedFactors p).map Polynomial.natDegree).sum = p.natDegree := by
  have h := Polynomial.natDegree_eq_of_degree_eq <|
    Polynomial.degree_eq_degree_of_associated (prod_normalizedFactors hp)
  rw [Polynomial.natDegree_multiset_prod _ (zero_notMem_normalizedFactors _)] at h
  exact h

/-- A finite superset of the true polynomial factors gives the same
degree sum, with zero contribution from any extra representatives. -/
theorem sum_factorCounts_mul_degree
    (p : Polynomial K) (hp : p ≠ 0) (s : Finset (Polynomial K))
    (hs : (normalizedFactors p).toFinset ⊆ s) :
    ∑ q ∈ s, q.natDegree * (normalizedFactors p).count q = p.natDegree := by
  classical
  have h := sum_factor_degrees K p hp
  rw [Finset.sum_multiset_map_count] at h
  simp only [nsmul_eq_mul] at h
  norm_cast at h
  have hsum :
      (∑ q ∈ (normalizedFactors p).toFinset,
        (normalizedFactors p).count q * q.natDegree) =
      ∑ q ∈ s, (normalizedFactors p).count q * q.natDegree := by
    apply Finset.sum_subset hs
    intro q _ hq
    have hc : (normalizedFactors p).count q = 0 :=
      Multiset.count_eq_zero.mpr (by simpa using hq)
    simp [hc]
  rw [hsum] at h
  simpa only [Nat.mul_comm] using h

/-- The explicit polynomial representatives that can have nonzero order. -/
def factorSupport (x : RatFunc K) : Finset (Polynomial K) := by
  classical
  exact (normalizedFactors x.num).toFinset ∪ (normalizedFactors x.denom).toFinset

theorem factorSupport_primes (x : RatFunc K) (hx : x ≠ 0)
    (p : Polynomial K) (hp : p ∈ factorSupport K x) : Irreducible p ∧ p.Monic := by
  classical
  rcases Finset.mem_union.mp hp with hnum | hden
  · have h := (Polynomial.mem_normalizedFactors_iff
      (R := K) (p := p) (q := x.num) (RatFunc.num_ne_zero hx)).mp
      (Multiset.mem_toFinset.mp hnum)
    exact ⟨h.1, h.2.1⟩
  · have h := (Polynomial.mem_normalizedFactors_iff
      (R := K) (p := p) (q := x.denom) x.denom_ne_zero).mp
      (Multiset.mem_toFinset.mp hden)
    exact ⟨h.1, h.2.1⟩

theorem finiteOrder_eq_zero_of_not_mem
    (p : Polynomial K) (hp : Irreducible p) (hmonic : p.Monic)
    (x : RatFunc K) (hx : x ≠ 0) (hout : p ∉ factorSupport K x) :
    finiteOrder K p hp x = 0 := by
  classical
  have hn : p ∉ normalizedFactors x.num := by
    intro h
    exact hout (Finset.mem_union_left _ (Multiset.mem_toFinset.mpr h))
  have hd : p ∉ normalizedFactors x.denom := by
    intro h
    exact hout (Finset.mem_union_right _ (Multiset.mem_toFinset.mpr h))
  rw [finiteOrder_eq_factorCounts K p hp hmonic x hx,
    Multiset.count_eq_zero.mpr hn, Multiset.count_eq_zero.mpr hd]
  simp

/-- Every nonzero actual finite-place order is represented in the finite
set above. This includes places not initially named by a polynomial. -/
theorem nonzero_order_has_supported_representative
    (x : RatFunc K) (hx : x ≠ 0) (v : HeightOneSpectrum (Polynomial K))
    (hv : NormValuation.orderAt v (asFraction K x) ≠ 0) :
    ∃ p ∈ factorSupport K x, ∃ hp : Irreducible p,
      p.Monic ∧ primePlace K p hp = v := by
  obtain ⟨p, hp, hm, hplace⟩ := exists_monic_primePlace K v
  refine ⟨p, ?_, hp, hm, hplace⟩
  by_contra hout
  have hzero := finiteOrder_eq_zero_of_not_mem K p hp hm x hx hout
  exact hv (by simpa [finiteOrder, hplace] using hzero)

theorem finite_support_actual_orders (x : RatFunc K) (hx : x ≠ 0) :
    Function.HasFiniteSupport
      (fun v : HeightOneSpectrum (Polynomial K) ↦
        NormValuation.orderAt v (asFraction K x)) := by
  classical
  let f : {p : Polynomial K // p ∈ factorSupport K x} →
      HeightOneSpectrum (Polynomial K) := fun p ↦
    primePlace K p.1 (factorSupport_primes K x hx p.1 p.2).1
  apply (Set.finite_range f).subset
  intro v hv
  obtain ⟨p, hmem, hp, _, hplace⟩ :=
    nonzero_order_has_supported_representative K x hx v hv
  exact ⟨⟨p, hmem⟩, hplace⟩

/-- Weighted sum of the actual finite-place orders, allowing any extra
monic irreducible representatives with zero contribution. -/
theorem weighted_finite_order_sum
    (x : RatFunc K) (hx : x ≠ 0) (s : Finset (Polynomial K))
    (hs : ∀ p ∈ s, Irreducible p ∧ p.Monic)
    (hnum : (normalizedFactors x.num).toFinset ⊆ s)
    (hden : (normalizedFactors x.denom).toFinset ⊆ s) :
    (∑ p ∈ s.attach, (p.1.natDegree : ℤ) *
      finiteOrder K p.1 (hs p.1 p.2).1 x) = x.intDegree := by
  classical
  have hterms :
      (∑ p ∈ s.attach, (p.1.natDegree : ℤ) *
        finiteOrder K p.1 (hs p.1 p.2).1 x) =
      ∑ p ∈ s, (p.natDegree : ℤ) *
        (((normalizedFactors x.num).count p : ℤ) -
          ((normalizedFactors x.denom).count p : ℤ)) := by
    calc
      _ = ∑ p ∈ s.attach, (p.1.natDegree : ℤ) *
          (((normalizedFactors x.num).count p.1 : ℤ) -
            ((normalizedFactors x.denom).count p.1 : ℤ)) := by
        apply Finset.sum_congr rfl
        intro p _
        rw [finiteOrder_eq_factorCounts K p.1 (hs p.1 p.2).1 (hs p.1 p.2).2 x hx]
      _ = _ := Finset.sum_attach s (fun p : Polynomial K ↦
        (p.natDegree : ℤ) *
          (((normalizedFactors x.num).count p : ℤ) -
            ((normalizedFactors x.denom).count p : ℤ)))
  rw [hterms]
  simp only [mul_sub, Finset.sum_sub_distrib]
  have hn : (∑ p ∈ s, (p.natDegree : ℤ) *
      ((normalizedFactors x.num).count p : ℤ)) = (x.num.natDegree : ℤ) := by
    exact_mod_cast sum_factorCounts_mul_degree K x.num (RatFunc.num_ne_zero hx) s hnum
  have hd : (∑ p ∈ s, (p.natDegree : ℤ) *
      ((normalizedFactors x.denom).count p : ℤ)) = (x.denom.natDegree : ℤ) := by
    exact_mod_cast sum_factorCounts_mul_degree K x.denom x.denom_ne_zero s hden
  rw [hn, hd]
  rfl

/-- The base projective-line product formula, constructed from actual
finite valuations and the actual valuation at infinity. The finite sum
covers every nonzero finite-place order and has no duplicate places. -/
theorem projective_line_order_sum (x : RatFunc K) (hx : x ≠ 0) :
    (∑ p ∈ (factorSupport K x).attach, (p.1.natDegree : ℤ) *
      finiteOrder K p.1 (factorSupport_primes K x hx p.1 p.2).1 x) +
      infinityOrder K x = 0 := by
  classical
  rw [weighted_finite_order_sum K x hx (factorSupport K x)
    (factorSupport_primes K x hx)
    Finset.subset_union_left Finset.subset_union_right,
    infinityOrder_eq_neg_intDegree K x hx, add_neg_cancel]

end

end ProximityPrize.SubmissionLower.RatFuncProductFormula
