/-
Copyright (c) 2026 Proximity Prize Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ProximityPrize.Benchmark.TargetUpper

/-!
# Coordinate-kernel gate for odd collision folds

Let `f` be a rational map and let `C` be an irreducible component of its
off-diagonal collision curve `f(x) = f(y)`.  Suppose that a subgroup of
`mu_512 x mu_512` stabilizes `C`.  A coordinate-kernel element `(1, eta)`
has a consequence special to collision curves:

* on `C`, both `f(x) = f(y)` and `f(x) = f(eta*y)` hold;
* dominance of `C -> P^1_y` therefore gives the rational-function identity
  `f(y) = f(eta*y)`;
* the scaling group generated by `eta` is consequently a deck subgroup of
  `f`, so its order divides `deg(f)`.

The kernel order also divides 512.  Thus it is one for every odd map degree.
Both coordinate projections of the stabilizer are injective and the descent
degree is at most 512.  This is stronger than the generic-fibre estimate
`kernelOrder | collisionCoordinateDegree`, and removes the apparent descent
degrees 1024 in degree seven and 4096 in degree nine.

The function-field implication producing `kernelOrder | mapDegree` is kept as
an explicit hypothesis below.  The finite arithmetic, exact parameter choices,
and numerical consumers are fully checked here.  The accompanying executable
ledger is `scripts/upper-odd-fold-stabilizer-audit.py`.
-/

namespace ProximityPrize.SubmissionUpper.OddFoldStabilizerKernelGate

def subgroupOrder : Nat := 512
def baseCharacteristic : Nat := 2130706433

/-- Once a coordinate-kernel symmetry is known to be a deck symmetry, coprimality
with the ambient subgroup order makes the coordinate kernel trivial. -/
theorem collision_kernel_trivial_of_coprime_map_degree
    (mapDegree kernelOrder : Nat)
    (hcoprime : Nat.Coprime mapDegree subgroupOrder)
    (hmap : kernelOrder ∣ mapDegree)
    (hsubgroup : kernelOrder ∣ subgroupOrder) : kernelOrder = 1 := by
  exact Nat.eq_one_of_dvd_coprimes hcoprime hmap hsubgroup

/-- On the full residual component the same coordinate kernel acts freely on
the generic `(deg(f)-1)`-point off-diagonal fibre.  Combining that divisibility
with the deck divisibility makes the kernel trivial in every map degree, not
only odd degrees. -/
theorem full_collision_kernel_trivial
    (mapDegree collisionCoordinateDegree kernelOrder : Nat)
    (hsucc : mapDegree = collisionCoordinateDegree + 1)
    (hmap : kernelOrder ∣ mapDegree)
    (hcollision : kernelOrder ∣ collisionCoordinateDegree) : kernelOrder = 1 := by
  have hcoprime : Nat.Coprime mapDegree collisionCoordinateDegree := by
    rw [hsucc, Nat.add_comm]
    exact Nat.coprime_add_self_left.mpr (Nat.coprime_one_left _)
  exact Nat.eq_one_of_dvd_coprimes hcoprime hmap hcollision

theorem septic_collision_kernel_trivial
    (kernelOrder : Nat) (hmap : kernelOrder ∣ 7)
    (hsubgroup : kernelOrder ∣ subgroupOrder) : kernelOrder = 1 := by
  exact collision_kernel_trivial_of_coprime_map_degree 7 kernelOrder
    (by norm_num [subgroupOrder]) hmap hsubgroup

theorem nonic_collision_kernel_trivial
    (kernelOrder : Nat) (hmap : kernelOrder ∣ 9)
    (hsubgroup : kernelOrder ∣ subgroupOrder) : kernelOrder = 1 := by
  exact collision_kernel_trivial_of_coprime_map_degree 9 kernelOrder
    (by norm_num [subgroupOrder]) hmap hsubgroup

/-- First-isomorphism cardinal accounting: if the coordinate kernel is a deck
subgroup of an odd-degree map, the collision-component stabilizer has order at
most the order of its coordinate projection, hence at most 512. -/
theorem stabilizer_order_le_subgroup_of_coprime_map_degree
    (mapDegree stabilizerOrder projectionOrder kernelOrder : Nat)
    (hcoprime : Nat.Coprime mapDegree subgroupOrder)
    (hcard : stabilizerOrder = projectionOrder * kernelOrder)
    (hprojection : projectionOrder ≤ subgroupOrder)
    (hmap : kernelOrder ∣ mapDegree)
    (hsubgroup : kernelOrder ∣ subgroupOrder) : stabilizerOrder ≤ subgroupOrder := by
  have hkernel : kernelOrder = 1 :=
    collision_kernel_trivial_of_coprime_map_degree mapDegree kernelOrder
      hcoprime hmap hsubgroup
  calc
    stabilizerOrder = projectionOrder := by simpa [hkernel] using hcard
    _ ≤ subgroupOrder := hprojection

theorem no_septic_descent_degree_1024
    (projectionOrder kernelOrder : Nat)
    (hcard : 1024 = projectionOrder * kernelOrder)
    (hprojection : projectionOrder ≤ subgroupOrder)
    (hmap : kernelOrder ∣ 7)
    (hsubgroup : kernelOrder ∣ subgroupOrder) : False := by
  have hle : 1024 ≤ subgroupOrder :=
    stabilizer_order_le_subgroup_of_coprime_map_degree 7 1024 projectionOrder kernelOrder
      (by norm_num [subgroupOrder]) hcard hprojection hmap hsubgroup
  norm_num [subgroupOrder] at hle

theorem no_nonic_descent_degree_4096
    (projectionOrder kernelOrder : Nat)
    (hcard : 4096 = projectionOrder * kernelOrder)
    (hprojection : projectionOrder ≤ subgroupOrder)
    (hmap : kernelOrder ∣ 9)
    (hsubgroup : kernelOrder ∣ subgroupOrder) : False := by
  have hle : 4096 ≤ subgroupOrder :=
    stabilizer_order_le_subgroup_of_coprime_map_degree 9 4096 projectionOrder kernelOrder
      (by norm_num [subgroupOrder]) hcard hprojection hmap hsubgroup
  norm_num [subgroupOrder] at hle

namespace Septic

def mapDegree : Nat := 7
def collisionCoordinateDegree : Nat := 6
def powerCoordinateDegree : Nat := 3072
def eulerCharacteristicCap : Nat := 72
def fullFibres : Nat := 73
def requiredCollisions : Nat := 3066

def parameterH : Nat := 6
def parameterK : Nat := 2
def parameterN : Nat := 20
def clearedParameterizedCap : Nat := 101088

theorem parameter_denominator_receipt :
    parameterH * parameterK + parameterH + parameterK = parameterN := by
  norm_num [parameterH, parameterK, parameterN]

theorem proposition_characteristic_condition_receipt :
    powerCoordinateDegree * parameterH + powerCoordinateDegree * parameterK <
      baseCharacteristic := by
  norm_num [powerCoordinateDegree, parameterH, parameterK, baseCharacteristic]

theorem parameterized_cap_receipt :
    2 * (parameterH + 2 * parameterK) * powerCoordinateDegree +
        2 * parameterK * powerCoordinateDegree +
        (parameterN - 1) * parameterN * eulerCharacteristicCap =
      clearedParameterizedCap := by
  norm_num [parameterH, parameterK, parameterN, powerCoordinateDegree,
    eulerCharacteristicCap, clearedParameterizedCap]

theorem collision_receipt : fullFibres * mapDegree * collisionCoordinateDegree =
    requiredCollisions := by
  norm_num [fullFibres, mapDegree, collisionCoordinateDegree, requiredCollisions]

theorem quotient_coordinate_degree_not_le_two
    (descentDegree quotientCoordinateDegree : Nat)
    (hdegree : descentDegree * quotientCoordinateDegree = powerCoordinateDegree)
    (hdescent : descentDegree ≤ subgroupOrder)
    (hlow : quotientCoordinateDegree ≤ parameterK) : False := by
  have hmul : descentDegree * quotientCoordinateDegree ≤ subgroupOrder * parameterK :=
    Nat.mul_le_mul hdescent hlow
  norm_num [hdegree, powerCoordinateDegree, subgroupOrder, parameterK] at hmul

theorem required_collisions_break_parameterized_cap :
    2 * parameterN * requiredCollisions > clearedParameterizedCap := by
  norm_num [parameterN, requiredCollisions, clearedParameterizedCap]

theorem no_full_fibres_of_parameterized_cap
    (collisionGcd : Nat)
    (hfull : requiredCollisions ≤ collisionGcd)
    (hparameterized : 2 * parameterN * collisionGcd ≤ clearedParameterizedCap) : False := by
  have hrequired : 2 * parameterN * requiredCollisions ≤
      2 * parameterN * collisionGcd := Nat.mul_le_mul_left _ hfull
  have := hrequired.trans hparameterized
  norm_num [parameterN, requiredCollisions, clearedParameterizedCap] at this

end Septic

namespace SepticComponents

/-!
For degree seven, the non-2-transitive affine monodromy groups have point-
stabilizer suborbits of sizes one (`C7`), two (`D14`), or three (`F21`).
An `s`-suborbit gives a collision component of bidegree `(s,s)` and receives
`73 * 7 * s = 511*s` points from the 73 full fibres.  The deck-kernel gate
still bounds every component descent degree by 512.

The size-two and size-three components are excluded below by asymmetric
exact parameters.  A size-one component is a deck graph.  Its 511 subgroup
points exceed the non-toric `(1,1)` bound 305; a toric graph would be a
scaling or inversion, whose order cannot be seven.
-/

def dihedralCoordinateDegree : Nat := 2
def dihedralPowerCoordinateDegree : Nat := 1024
def dihedralEulerCharacteristicCap : Nat := 8
def dihedralRequiredCollisions : Nat := 1022

def dihedralParameterH : Nat := 3
def dihedralParameterK : Nat := 1
def dihedralParameterN : Nat := 7
def dihedralClearedCap : Nat := 12624

theorem dihedral_component_collision_receipt :
    Septic.fullFibres * Septic.mapDegree * dihedralCoordinateDegree =
      dihedralRequiredCollisions := by
  norm_num [Septic.fullFibres, Septic.mapDegree, dihedralCoordinateDegree,
    dihedralRequiredCollisions]

theorem dihedral_parameter_denominator_receipt :
    dihedralParameterH * dihedralParameterK + dihedralParameterH +
      dihedralParameterK = dihedralParameterN := by
  norm_num [dihedralParameterH, dihedralParameterK, dihedralParameterN]

theorem dihedral_parameterized_cap_receipt :
    2 * (dihedralParameterH + 2 * dihedralParameterK) *
          dihedralPowerCoordinateDegree +
        2 * dihedralParameterK * dihedralPowerCoordinateDegree +
        (dihedralParameterN - 1) * dihedralParameterN *
          dihedralEulerCharacteristicCap = dihedralClearedCap := by
  norm_num [dihedralParameterH, dihedralParameterK, dihedralParameterN,
    dihedralPowerCoordinateDegree, dihedralEulerCharacteristicCap, dihedralClearedCap]

theorem dihedral_quotient_degree_not_le_one
    (descentDegree quotientCoordinateDegree : Nat)
    (hdegree : descentDegree * quotientCoordinateDegree =
      dihedralPowerCoordinateDegree)
    (hdescent : descentDegree ≤ subgroupOrder)
    (hlow : quotientCoordinateDegree ≤ dihedralParameterK) : False := by
  have hmul : descentDegree * quotientCoordinateDegree ≤
      subgroupOrder * dihedralParameterK := Nat.mul_le_mul hdescent hlow
  norm_num [hdegree, dihedralPowerCoordinateDegree, subgroupOrder,
    dihedralParameterK] at hmul

theorem dihedral_required_breaks_cap :
    2 * dihedralParameterN * dihedralRequiredCollisions > dihedralClearedCap := by
  norm_num [dihedralParameterN, dihedralRequiredCollisions, dihedralClearedCap]

theorem no_dihedral_component_of_parameterized_cap
    (componentPoints : Nat)
    (hfull : dihedralRequiredCollisions ≤ componentPoints)
    (hcap : 2 * dihedralParameterN * componentPoints ≤ dihedralClearedCap) : False := by
  have hscaled : 2 * dihedralParameterN * dihedralRequiredCollisions ≤
      2 * dihedralParameterN * componentPoints := Nat.mul_le_mul_left _ hfull
  have := hscaled.trans hcap
  norm_num [dihedralParameterN, dihedralRequiredCollisions, dihedralClearedCap] at this

def frobeniusCoordinateDegree : Nat := 3
def frobeniusPowerCoordinateDegree : Nat := 1536
def frobeniusEulerCharacteristicCap : Nat := 18
def frobeniusRequiredCollisions : Nat := 1533

def frobeniusParameterH : Nat := 6
def frobeniusParameterK : Nat := 2
def frobeniusParameterN : Nat := 20
def frobeniusClearedCap : Nat := 43704

theorem frobenius_component_collision_receipt :
    Septic.fullFibres * Septic.mapDegree * frobeniusCoordinateDegree =
      frobeniusRequiredCollisions := by
  norm_num [Septic.fullFibres, Septic.mapDegree, frobeniusCoordinateDegree,
    frobeniusRequiredCollisions]

theorem frobenius_parameter_denominator_receipt :
    frobeniusParameterH * frobeniusParameterK + frobeniusParameterH +
      frobeniusParameterK = frobeniusParameterN := by
  norm_num [frobeniusParameterH, frobeniusParameterK, frobeniusParameterN]

theorem frobenius_parameterized_cap_receipt :
    2 * (frobeniusParameterH + 2 * frobeniusParameterK) *
          frobeniusPowerCoordinateDegree +
        2 * frobeniusParameterK * frobeniusPowerCoordinateDegree +
        (frobeniusParameterN - 1) * frobeniusParameterN *
          frobeniusEulerCharacteristicCap = frobeniusClearedCap := by
  norm_num [frobeniusParameterH, frobeniusParameterK, frobeniusParameterN,
    frobeniusPowerCoordinateDegree, frobeniusEulerCharacteristicCap, frobeniusClearedCap]

theorem frobenius_quotient_degree_not_le_two
    (descentDegree quotientCoordinateDegree : Nat)
    (hdegree : descentDegree * quotientCoordinateDegree =
      frobeniusPowerCoordinateDegree)
    (hdescent : descentDegree ≤ subgroupOrder)
    (hlow : quotientCoordinateDegree ≤ frobeniusParameterK) : False := by
  have hmul : descentDegree * quotientCoordinateDegree ≤
      subgroupOrder * frobeniusParameterK := Nat.mul_le_mul hdescent hlow
  norm_num [hdegree, frobeniusPowerCoordinateDegree, subgroupOrder,
    frobeniusParameterK] at hmul

theorem frobenius_required_breaks_cap :
    2 * frobeniusParameterN * frobeniusRequiredCollisions > frobeniusClearedCap := by
  norm_num [frobeniusParameterN, frobeniusRequiredCollisions, frobeniusClearedCap]

theorem no_frobenius_component_of_parameterized_cap
    (componentPoints : Nat)
    (hfull : frobeniusRequiredCollisions ≤ componentPoints)
    (hcap : 2 * frobeniusParameterN * componentPoints ≤ frobeniusClearedCap) : False := by
  have hscaled : 2 * frobeniusParameterN * frobeniusRequiredCollisions ≤
      2 * frobeniusParameterN * componentPoints := Nat.mul_le_mul_left _ hfull
  have := hscaled.trans hcap
  norm_num [frobeniusParameterN, frobeniusRequiredCollisions, frobeniusClearedCap] at this

def cyclicGraphRequiredCollisions : Nat := 511
def nonToricGraphCap : Nat := 305
def graphEulerCharacteristicCap : Nat := 2

theorem cyclic_component_collision_receipt :
    Septic.fullFibres * Septic.mapDegree = cyclicGraphRequiredCollisions := by
  norm_num [Septic.fullFibres, Septic.mapDegree, cyclicGraphRequiredCollisions]

theorem graph_first_branch_receipt :
    54 * subgroupOrder ^ 2 * graphEulerCharacteristicCap < nonToricGraphCap ^ 3 := by
  norm_num [subgroupOrder, graphEulerCharacteristicCap, nonToricGraphCap]

theorem graph_second_branch_receipt :
    12 * subgroupOrder ^ 2 < nonToricGraphCap * baseCharacteristic := by
  norm_num [subgroupOrder, nonToricGraphCap, baseCharacteristic]

theorem cyclic_required_breaks_graph_cap :
    cyclicGraphRequiredCollisions > nonToricGraphCap := by
  norm_num [cyclicGraphRequiredCollisions, nonToricGraphCap]

theorem no_cyclic_component_of_graph_cap
    (componentPoints : Nat)
    (hfull : cyclicGraphRequiredCollisions ≤ componentPoints)
    (hcap : componentPoints ≤ nonToricGraphCap) : False := by
  have := hfull.trans hcap
  norm_num [cyclicGraphRequiredCollisions, nonToricGraphCap] at this

/-- A toric scaling graph cannot simultaneously have order seven and have
its scaling constant in the order-512 subgroup. -/
theorem septic_scaling_trivial {F : Type*} [Field F] {r : F}
    (hseven : r ^ 7 = 1) (hsubgroup : r ^ subgroupOrder = 1) : r = 1 := by
  exact (pow_eq_one_iff_of_coprime (by norm_num [subgroupOrder] : Nat.Coprime 7 512)).mp
    ⟨hseven, by simpa [subgroupOrder] using hsubgroup⟩

end SepticComponents

namespace Nonic

def mapDegree : Nat := 9
def collisionCoordinateDegree : Nat := 8
def powerCoordinateDegree : Nat := 4096
def eulerCharacteristicCap : Nat := 128
def fullFibres : Nat := 56
def requiredCollisions : Nat := 4032

def parameterH : Nat := 6
def parameterK : Nat := 1
def parameterN : Nat := 13
def clearedParameterizedCap : Nat := 93696

theorem parameter_denominator_receipt :
    parameterH * parameterK + parameterH + parameterK = parameterN := by
  norm_num [parameterH, parameterK, parameterN]

theorem proposition_characteristic_condition_receipt :
    powerCoordinateDegree * parameterH + powerCoordinateDegree * parameterK <
      baseCharacteristic := by
  norm_num [powerCoordinateDegree, parameterH, parameterK, baseCharacteristic]

theorem parameterized_cap_receipt :
    2 * (parameterH + 2 * parameterK) * powerCoordinateDegree +
        2 * parameterK * powerCoordinateDegree +
        (parameterN - 1) * parameterN * eulerCharacteristicCap =
      clearedParameterizedCap := by
  norm_num [parameterH, parameterK, parameterN, powerCoordinateDegree,
    eulerCharacteristicCap, clearedParameterizedCap]

theorem collision_receipt : fullFibres * mapDegree * collisionCoordinateDegree =
    requiredCollisions := by
  norm_num [fullFibres, mapDegree, collisionCoordinateDegree, requiredCollisions]

theorem quotient_coordinate_degree_not_le_one
    (descentDegree quotientCoordinateDegree : Nat)
    (hdegree : descentDegree * quotientCoordinateDegree = powerCoordinateDegree)
    (hdescent : descentDegree ≤ subgroupOrder)
    (hlow : quotientCoordinateDegree ≤ parameterK) : False := by
  have hmul : descentDegree * quotientCoordinateDegree ≤ subgroupOrder * parameterK :=
    Nat.mul_le_mul hdescent hlow
  norm_num [hdegree, powerCoordinateDegree, subgroupOrder, parameterK] at hmul

theorem required_collisions_break_parameterized_cap :
    2 * parameterN * requiredCollisions > clearedParameterizedCap := by
  norm_num [parameterN, requiredCollisions, clearedParameterizedCap]

theorem no_full_fibres_of_parameterized_cap
    (collisionGcd : Nat)
    (hfull : requiredCollisions ≤ collisionGcd)
    (hparameterized : 2 * parameterN * collisionGcd ≤ clearedParameterizedCap) : False := by
  have hrequired : 2 * parameterN * requiredCollisions ≤
      2 * parameterN * collisionGcd := Nat.mul_le_mul_left _ hfull
  have := hrequired.trans hparameterized
  norm_num [parameterN, requiredCollisions, clearedParameterizedCap] at this

end Nonic

namespace NonicComponents

/-!
There is a classification-free route through the reducible residual cases in
degree nine.  A primitive permutation action of composite degree nine cannot
have a nontrivial suborbit of size one: equality of two point stabilizers gives
a block relation, and the resulting regular alternative is imprimitive in
degree nine.  Hence every collision component of a primitive degree-nine map
has coordinate degree `s` between two and eight.

For all seven values at once, take `h=12`, `k=1`, and `n=25`.  Triviality of
the odd-degree coordinate kernel gives quotient coordinate degree at least
`s`, so the low alternative (which would require it to be at most one) is
impossible.  With `chi <= 2*s^2`, the cleared useful bound is

`15360*s + 1200*s^2 < 50*(504*s)` for `2 <= s <= 8`.

If the degree-nine monodromy is imprimitive, the rational map decomposes as
degrees three after three.  Each of the 56 full nine-point fibres contains
three full fibres of the inner cubic, giving 168 full cubic fibres.  The final
receipts show that these already exceed both cubic collision caps.
-/

def componentParameterH : Nat := 12
def componentParameterK : Nat := 1
def componentParameterN : Nat := 25

def usedSubgroupPoints : Nat := 504
def cubicInnerFullFibres : Nat := 168
def cubicIrreducibleCollisionCap : Nat := 768
def cubicGraphCollisionCap : Nat := 305

theorem component_parameter_denominator_receipt :
    componentParameterH * componentParameterK + componentParameterH +
      componentParameterK = componentParameterN := by
  norm_num [componentParameterH, componentParameterK, componentParameterN]

theorem component_characteristic_condition_receipt (s : Nat) (hs : s ≤ 8) :
    subgroupOrder * s * componentParameterH +
        subgroupOrder * s * componentParameterK < baseCharacteristic := by
  norm_num [subgroupOrder, componentParameterH, componentParameterK,
    baseCharacteristic]
  omega

theorem component_cap_identity (s : Nat) :
    2 * (componentParameterH + 2 * componentParameterK) * (subgroupOrder * s) +
        2 * componentParameterK * (subgroupOrder * s) +
        (componentParameterN - 1) * componentParameterN * (2 * s ^ 2) =
      15360 * s + 1200 * s ^ 2 := by
  norm_num [componentParameterH, componentParameterK, componentParameterN,
    subgroupOrder]
  ring

theorem component_cap_below_required (s : Nat) (hlow : 2 ≤ s) (hhigh : s ≤ 8) :
    15360 * s + 1200 * s ^ 2 < 2 * componentParameterN * (usedSubgroupPoints * s) := by
  interval_cases s <;>
    norm_num [componentParameterN, usedSubgroupPoints]

theorem no_primitive_component_of_parameterized_cap
    (s componentPoints : Nat) (hlow : 2 ≤ s) (hhigh : s ≤ 8)
    (hfull : usedSubgroupPoints * s ≤ componentPoints)
    (hcap : 2 * componentParameterN * componentPoints ≤
      15360 * s + 1200 * s ^ 2) : False := by
  have hscaled : 2 * componentParameterN * (usedSubgroupPoints * s) ≤
      2 * componentParameterN * componentPoints := Nat.mul_le_mul_left _ hfull
  have hupper := hscaled.trans hcap
  exact (Nat.not_le_of_lt (component_cap_below_required s hlow hhigh)) hupper

theorem component_quotient_degree_not_le_one
    (s descentDegree quotientCoordinateDegree : Nat)
    (hs : 2 ≤ s)
    (hdegree : descentDegree * quotientCoordinateDegree = subgroupOrder * s)
    (hdescent : descentDegree ≤ subgroupOrder)
    (hlow : quotientCoordinateDegree ≤ componentParameterK) : False := by
  have hmul : descentDegree * quotientCoordinateDegree ≤
      subgroupOrder * componentParameterK := Nat.mul_le_mul hdescent hlow
  rw [hdegree] at hmul
  norm_num [subgroupOrder, componentParameterK] at hmul
  omega

theorem cubic_inner_fibre_receipt : Nonic.fullFibres * 3 = cubicInnerFullFibres := by
  norm_num [Nonic.fullFibres, cubicInnerFullFibres]

theorem cubic_inner_irreducible_breaks_cap :
    cubicInnerFullFibres * 3 * 2 > cubicIrreducibleCollisionCap := by
  norm_num [cubicInnerFullFibres, cubicIrreducibleCollisionCap]

theorem cubic_inner_graph_breaks_cap :
    cubicInnerFullFibres * 3 > cubicGraphCollisionCap := by
  norm_num [cubicInnerFullFibres, cubicGraphCollisionCap]

end NonicComponents

namespace PrimeComponents

/-!
The same component ledger continues through the next two prime degrees.
For a prime-degree primitive action, a size-one suborbit is the regular cyclic
case; every other component has coordinate degree at least two.  Since 11 and
13 are coprime to 512, the coordinate-kernel/deck argument bounds every
component descent degree by 512.

The one choice `h=5`, `k=1`, `n=11` handles every non-graph component:

`8192*s + 220*s^2`

is the cleared cap.  Degree eleven uses 506 subgroup inputs and component
degrees `2 <= s <= 10`; degree thirteen uses 507 inputs and
`2 <= s <= 12`.  The regular cyclic graph is treated by the same 305-point
non-toric graph cap as in degree seven, with the toric scaling order excluded
by coprimality with 512.
-/

def parameterH : Nat := 5
def parameterK : Nat := 1
def parameterN : Nat := 11

def degreeElevenUsedPoints : Nat := 506
def degreeThirteenUsedPoints : Nat := 507
def graphCap : Nat := 305

theorem parameter_denominator_receipt :
    parameterH * parameterK + parameterH + parameterK = parameterN := by
  norm_num [parameterH, parameterK, parameterN]

theorem characteristic_condition_receipt (s : Nat) (hs : s ≤ 12) :
    subgroupOrder * s * parameterH + subgroupOrder * s * parameterK <
      baseCharacteristic := by
  norm_num [subgroupOrder, parameterH, parameterK, baseCharacteristic]
  omega

theorem component_cap_identity (s : Nat) :
    2 * (parameterH + 2 * parameterK) * (subgroupOrder * s) +
        2 * parameterK * (subgroupOrder * s) +
        (parameterN - 1) * parameterN * (2 * s ^ 2) =
      8192 * s + 220 * s ^ 2 := by
  norm_num [parameterH, parameterK, parameterN, subgroupOrder]
  ring

theorem degree_eleven_cap_below_required
    (s : Nat) (hlow : 2 ≤ s) (hhigh : s ≤ 10) :
    8192 * s + 220 * s ^ 2 <
      2 * parameterN * (degreeElevenUsedPoints * s) := by
  interval_cases s <;>
    norm_num [parameterN, degreeElevenUsedPoints]

theorem degree_thirteen_cap_below_required
    (s : Nat) (hlow : 2 ≤ s) (hhigh : s ≤ 12) :
    8192 * s + 220 * s ^ 2 <
      2 * parameterN * (degreeThirteenUsedPoints * s) := by
  interval_cases s <;>
    norm_num [parameterN, degreeThirteenUsedPoints]

theorem quotient_coordinate_degree_not_le_one
    (s descentDegree quotientCoordinateDegree : Nat)
    (hs : 2 ≤ s)
    (hdegree : descentDegree * quotientCoordinateDegree = subgroupOrder * s)
    (hdescent : descentDegree ≤ subgroupOrder)
    (hlow : quotientCoordinateDegree ≤ parameterK) : False := by
  have hmul : descentDegree * quotientCoordinateDegree ≤ subgroupOrder * parameterK :=
    Nat.mul_le_mul hdescent hlow
  rw [hdegree] at hmul
  norm_num [subgroupOrder, parameterK] at hmul
  omega

theorem no_degree_eleven_component_of_parameterized_cap
    (s componentPoints : Nat) (hlow : 2 ≤ s) (hhigh : s ≤ 10)
    (hfull : degreeElevenUsedPoints * s ≤ componentPoints)
    (hcap : 2 * parameterN * componentPoints ≤ 8192 * s + 220 * s ^ 2) : False := by
  have hscaled : 2 * parameterN * (degreeElevenUsedPoints * s) ≤
      2 * parameterN * componentPoints := Nat.mul_le_mul_left _ hfull
  have hupper := hscaled.trans hcap
  exact (Nat.not_le_of_lt (degree_eleven_cap_below_required s hlow hhigh)) hupper

theorem no_degree_thirteen_component_of_parameterized_cap
    (s componentPoints : Nat) (hlow : 2 ≤ s) (hhigh : s ≤ 12)
    (hfull : degreeThirteenUsedPoints * s ≤ componentPoints)
    (hcap : 2 * parameterN * componentPoints ≤ 8192 * s + 220 * s ^ 2) : False := by
  have hscaled : 2 * parameterN * (degreeThirteenUsedPoints * s) ≤
      2 * parameterN * componentPoints := Nat.mul_le_mul_left _ hfull
  have hupper := hscaled.trans hcap
  exact (Nat.not_le_of_lt (degree_thirteen_cap_below_required s hlow hhigh)) hupper

theorem degree_eleven_cyclic_graph_breaks_cap : degreeElevenUsedPoints > graphCap := by
  norm_num [degreeElevenUsedPoints, graphCap]

theorem degree_thirteen_cyclic_graph_breaks_cap : degreeThirteenUsedPoints > graphCap := by
  norm_num [degreeThirteenUsedPoints, graphCap]

theorem no_degree_eleven_cyclic_graph_of_cap
    (componentPoints : Nat)
    (hfull : degreeElevenUsedPoints ≤ componentPoints)
    (hcap : componentPoints ≤ graphCap) : False := by
  have := hfull.trans hcap
  norm_num [degreeElevenUsedPoints, graphCap] at this

theorem no_degree_thirteen_cyclic_graph_of_cap
    (componentPoints : Nat)
    (hfull : degreeThirteenUsedPoints ≤ componentPoints)
    (hcap : componentPoints ≤ graphCap) : False := by
  have := hfull.trans hcap
  norm_num [degreeThirteenUsedPoints, graphCap] at this

theorem degree_eleven_scaling_trivial {F : Type*} [Field F] {r : F}
    (hdegree : r ^ 11 = 1) (hsubgroup : r ^ subgroupOrder = 1) : r = 1 := by
  exact (pow_eq_one_iff_of_coprime (by norm_num [subgroupOrder] : Nat.Coprime 11 512)).mp
    ⟨hdegree, by simpa [subgroupOrder] using hsubgroup⟩

theorem degree_thirteen_scaling_trivial {F : Type*} [Field F] {r : F}
    (hdegree : r ^ 13 = 1) (hsubgroup : r ^ subgroupOrder = 1) : r = 1 := by
  exact (pow_eq_one_iff_of_coprime (by norm_num [subgroupOrder] : Nat.Coprime 13 512)).mp
    ⟨hdegree, by simpa [subgroupOrder] using hsubgroup⟩

end PrimeComponents

end ProximityPrize.SubmissionUpper.OddFoldStabilizerKernelGate

open ProximityPrize.SubmissionUpper.OddFoldStabilizerKernelGate

#print axioms septic_collision_kernel_trivial
#print axioms full_collision_kernel_trivial
#print axioms no_nonic_descent_degree_4096
#print axioms Septic.no_full_fibres_of_parameterized_cap
#print axioms SepticComponents.frobenius_required_breaks_cap
#print axioms SepticComponents.septic_scaling_trivial
#print axioms Nonic.no_full_fibres_of_parameterized_cap
#print axioms NonicComponents.component_cap_below_required
#print axioms NonicComponents.cubic_inner_irreducible_breaks_cap
#print axioms PrimeComponents.no_degree_eleven_component_of_parameterized_cap
#print axioms PrimeComponents.no_degree_thirteen_component_of_parameterized_cap
