/-
Copyright (c) 2026 Proximity Prize Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import ProximityPrize.Benchmark.TargetUpper

/-!
# Keeping both residual divisors in the Wronskian gcd ledger

The proof of Corvaja--Zannier's parameterized function-field gcd estimate
contains a little more information than its stated conclusion.  The exact
source is Proposition 2.1, equation (2.5), of their 2008 JAG paper; the proof
of Proposition 2 in their 2013 JEMS paper says that the same estimates apply
in positive characteristic once the Wronskian independence condition is met.
Put

`q = (1-u)/(1-v)`

and, away from the zero and pole set `S` of `u,v`, let `P` and `Z` be the
degrees of the pole and zero divisors of `q`.  If `G` is the common-zero
divisor of `1-u,1-v`, divisor cancellation gives

`P + G <= H(v)` and `Z + G <= H(u)`.

The signed `S`-valuation in (2.5) is unrestricted (it is not a positive-part
height).  The product formula therefore turns it into `P-Z`, and the
Wronskian calculation becomes

`h*k*H(v) <= C + (n-k)*P + k*Z`,

where `n=h*k+h+k` and `C=n*(n-1)/2*chi`.  Substituting *both* divisor bounds,
instead of first replacing the full height of `q` by `H(u)+H(v)`, yields

`n*G <= C + h*H(v) + k*H(u)`.

The elementary cancellation is proved below over the integers.  Applying it
geometrically still requires a smooth complete normalization, `S` containing
all zeros and poles, multiplicative independence modulo constants, exclusion
of the low branch, descent to the field generated by `u,v`, and in
characteristic `p` the condition `h*H(v)+k*H(u)<p`.  Those inputs and the
descent from the collision curve remain explicit obligations.  This file does
not import either lower-bound submission or assert them.

For a full irreducible degree-fifteen collision curve, the symmetric choice
`h=k=2`, `n=8` gives the cleared cap `39648`, whereas 34 full fibres require
`8*7140=57120`.  Thus the refined ledger closes the previous 56-unit
frontier with margin 17472, without needing a one-unit Euler-characteristic
improvement.
-/

namespace ProximityPrize.SubmissionUpper.WronskianGcdRefinement

/-- Pure divisor-bookkeeping consequence of the pre-Proposition Wronskian
inequality.  Integer coefficients avoid any rounding or division. -/
theorem refined_gcd_bound_of_wronskian_ledger
    (n h k C poleDegree zeroDegree gcdDegree heightU heightV : ℤ)
    (hn : n = h * k + h + k)
    (hnk : 0 ≤ n - k) (hk : 0 ≤ k)
    (hpole : poleDegree + gcdDegree ≤ heightV)
    (hzero : zeroDegree + gcdDegree ≤ heightU)
    (hwronskian : h * k * heightV ≤
      C + (n - k) * poleDegree + k * zeroDegree) :
    n * gcdDegree ≤ C + h * heightV + k * heightU := by
  have hpoleScaled := mul_le_mul_of_nonneg_left hpole hnk
  have hzeroScaled := mul_le_mul_of_nonneg_left hzero hk
  have hdivisors :
      (n - k) * (poleDegree + gcdDegree) +
          k * (zeroDegree + gcdDegree) ≤
        (n - k) * heightV + k * heightU :=
    add_le_add hpoleScaled hzeroScaled
  have hcombined :
      h * k * heightV + n * gcdDegree ≤
        C + (n - k) * heightV + k * heightU := by
    calc
      h * k * heightV + n * gcdDegree ≤
          (C + (n - k) * poleDegree + k * zeroDegree) +
            n * gcdDegree := by
        simpa [add_comm, add_left_comm, add_assoc] using
          (add_le_add_right hwronskian (n * gcdDegree))
      _ = C + ((n - k) * (poleDegree + gcdDegree) +
          k * (zeroDegree + gcdDegree)) := by
        rw [hn]
        ring
      _ ≤ C + ((n - k) * heightV + k * heightU) :=
        by
          simpa [add_comm, add_left_comm, add_assoc] using
            (add_le_add_left hdivisors C)
      _ = C + (n - k) * heightV + k * heightU := by ring
  have hcoefficient : n - k = h * k + h := by
    rw [hn]
    ring
  rw [hcoefficient] at hcombined
  nlinarith

def subgroupOrder : Nat := 512
def collisionCoordinateDegree : Nat := 14
def coordinatePowerDegree : Nat := 7168
def fullFibres : Nat := 34
def requiredCollisions : Nat := 7140

def parameterH : Nat := 2
def parameterK : Nat := 2
def parameterN : Nat := 8
def maximalEulerCharacteristic : Nat := 392
def wronskianTerm : Nat := 10976
def refinedClearedCap : Nat := 39648

theorem parameter_denominator_receipt :
    parameterH * parameterK + parameterH + parameterK = parameterN := by
  norm_num [parameterH, parameterK, parameterN]

theorem wronskian_term_receipt :
    parameterN * (parameterN - 1) / 2 * maximalEulerCharacteristic =
      wronskianTerm := by
  norm_num [parameterN, maximalEulerCharacteristic, wronskianTerm]

theorem refined_cap_receipt :
    (parameterH + parameterK) * coordinatePowerDegree + wronskianTerm =
      refinedClearedCap := by
  norm_num [parameterH, parameterK, coordinatePowerDegree, wronskianTerm,
    refinedClearedCap]

theorem degree_fifteen_collision_receipt :
    fullFibres * 15 * collisionCoordinateDegree = requiredCollisions := by
  norm_num [fullFibres, collisionCoordinateDegree, requiredCollisions]

theorem refined_degree_fifteen_margin_receipt :
    parameterN * requiredCollisions - refinedClearedCap = 17472 := by
  norm_num [parameterN, requiredCollisions, refinedClearedCap]

/-- Numerical consumer for a descended Wronskian ledger with maximal generic
geometry. -/
theorem no_34_full_fibres_of_refined_cap
    (collisionGcd : Nat)
    (hfull : requiredCollisions ≤ collisionGcd)
    (hrefined : parameterN * collisionGcd ≤ refinedClearedCap) : False := by
  have hrequired : parameterN * requiredCollisions ≤
      parameterN * collisionGcd := Nat.mul_le_mul_left _ hfull
  have := hrequired.trans hrefined
  norm_num [parameterN, requiredCollisions, refinedClearedCap] at this

end ProximityPrize.SubmissionUpper.WronskianGcdRefinement

#print axioms ProximityPrize.SubmissionUpper.WronskianGcdRefinement.refined_gcd_bound_of_wronskian_ledger
#print axioms ProximityPrize.SubmissionUpper.WronskianGcdRefinement.no_34_full_fibres_of_refined_cap
